#!/usr/bin/env python3
"""Generate Chapter 4 Global Malabsorption (Book p18-29).

Source: uploads/01.pdf PDF30-41 = Book p18-29, read sheet by sheet in printed order.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DATA.mkdir(exist_ok=True)

CHAPTER = 4
TITLE = "Global Malabsorption"
PAGES = "18-29"

U1 = "Global Malabsorption: Overview"
U2 = "Celiac Disease: Features & Iceberg Phenomenon"
U3 = "Celiac Disease: Types"
U4 = "Celiac Pathophysiology & Disease Progression"
U5 = "Celiac Clinical Features"
U6 = "Celiac Associations"
U7 = "Celiac Diagnosis: Serology & Biopsy"
U8 = "Celiac Interpretation, Complications & Treatment"
U9 = "Whipple's Disease: Presentation"
U10 = "Whipple's Disease: Clinical Features"
U11 = "Whipple's Disease: Diagnosis & Treatment"
U12 = "Tropical Sprue: Pathogenesis"
U13 = "Tropical Sprue: Features, Investigations & Treatment"
U14 = "Bile Acid Diarrhea & Fatty Acid Diarrhea"
U15 = "Short Bowel Syndrome: Definition & Etiology"
U16 = "Short Bowel Syndrome: Clinical Presentation"
U17 = "Short Bowel Syndrome: Deficiencies & Management"
U18 = "SIBO: Physiology, Pathology & Etiology"
U19 = "SIBO: Presentation, Investigations & Management"

RAW = [
    # ----------------------------------------------------------------- p18
    (U1, 18, "recall", "Global malabsorption means defective absorption of:",
     ["Carbohydrate, fat and protein",
      "Fat only",
      "Carbohydrate only",
      "Vitamin B12 only"],
     0, "Global malabsorption: defective absorption of a. carbohydrate, b. fat, c. protein. (Book p18)"),
    (U1, 18, "recall", "Among the nutrients in global malabsorption, fat is described as:",
     ["Most sensitive & specific, and the most energy dense nutrient",
      "Least sensitive but most specific",
      "The least energy dense nutrient",
      "Only a marker of pancreatic disease"],
     0, "b. Fat: most sensitive & specific, most energy dense nutrient. (Book p18)"),
    (U1, 18, "recall", "Global malabsorption results from:",
     ["Small intestinal mucosal dysfunction",
      "Gastric acid hypersecretion",
      "Colonic mucosal inflammation",
      "Biliary obstruction alone"],
     0, "Global malabsorption: small intestinal mucosal dysfunction. (Book p18)"),
    (U1, 18, "recall", "The three causes of global malabsorption listed are:",
     ["Celiac disease, Whipple's disease and tropical sprue",
      "Chronic pancreatitis, SIBO and cirrhosis",
      "Cystinuria, Hartnup disease and enterokinase deficiency",
      "Crohn's disease, tuberculosis and amyloidosis"],
     0, "Causes: a. celiac disease, b. Whipple's disease, c. tropical sprue. (Book p18)"),
    (U1, 18, "oddoneout", "Pick the ODD ONE OUT — one is not a listed cause of global malabsorption:",
     ["Chronic pancreatitis", "Celiac disease", "Whipple's disease", "Tropical sprue"],
     0, "Global malabsorption causes: celiac disease, Whipple's disease, tropical sprue. Chronic pancreatitis is a luminal defect. (Book p18)"),

    (U2, 18, "recall", "Celiac disease is also known as:",
     ["Celiac sprue / gluten sensitive enteropathy / non-tropical sprue",
      "Tropical sprue",
      "Blind loop syndrome",
      "Microscopic colitis"],
     0, "Features: AKA celiac sprue / gluten sensitive enteropathy / non-tropical sprue. (Book p18)"),
    (U2, 18, "numeric", "In the iceberg phenomenon, what proportion present with classical features?",
     ["50%", "90%", "10%", "80%"],
     0, "Iceberg phenomenon: only 50% present with classical features. (Book p18)"),
    (U2, 18, "recall", "The iceberg phenomenon is attributed to:",
     ["Physician unawareness, so cases are missed",
      "Patient denial of symptoms",
      "A very low prevalence of the disease",
      "Lack of a diagnostic test"],
     0, "Iceberg phenomenon: only 50% present with classical features; due to physician unawareness — diagnosis missed. (Book p18)"),
    (U2, 18, "recall", "The most important predisposition to celiac disease is:",
     ["HLA DQ2 / DQ8", "HLA DRB1*13", "HLA B27", "HLA DR4"],
     0, "HLA DQ2 / DQ8: most important predisposition. (Book p18)"),
    (U2, 18, "recall", "Celiac disease is described as a ____ small intestinal disease.",
     ["Proximal", "Distal", "Pan-intestinal with distal predominance", "Colonic"],
     0, "Celiac disease is a proximal small intestinal disease. (Book p18)"),
    (U2, 18, "fillup", "In the celiac iceberg image, EMA stands for ____ antibody.",
     ["endomysial", "epidermal", "eosinophilic", "enterocyte"],
     0, "Image key: EMA — endomysial antibody; Ig — immunoglobulin; tTG — tissue transglutaminase. (Book p18)"),
    (U2, 18, "fillup", "In the celiac iceberg image, tTG stands for tissue ____.",
     ["transglutaminase", "transpeptidase", "transferrin", "trypsinogen"],
     0, "Image key: tTG — tissue transglutaminase. (Book p18)"),

    (U3, 18, "match",
     "Match the celiac type to the printed definition — 1) Classical 2) Atypical 3) Silent 4) Latent … A) Asymptomatic, serology positive B) 50% of cases present with symptoms of malabsorption C) Asymptomatic, antibodies negative D) Presents with symptoms other than malabsorption",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "Classical: 50% of cases present with symptoms of malabsorption; atypical: symptoms other than malabsorption; silent: asymptomatic with positive serology; latent: asymptomatic with negative antibodies. (Book p18)"),
    (U3, 18, "recall", "Classical celiac disease is defined as:",
     ["50% of cases presenting with symptoms of malabsorption",
      "Asymptomatic disease with positive serology",
      "Disease with negative antibodies",
      "Disease confined to the skin"],
     0, "Classical celiac disease: 50% of cases present with symptoms of malabsorption. (Book p18)"),
    (U3, 18, "recall", "Atypical celiac disease presents with:",
     ["Symptoms other than malabsorption",
      "Classical steatorrhea",
      "No symptoms at all",
      "Only cutaneous disease"],
     0, "Atypical celiac disease: presents with symptoms other than malabsorption. (Book p18)"),
    (U3, 18, "recall", "Silent celiac disease is:",
     ["Asymptomatic with positive serology",
      "Asymptomatic with negative antibodies",
      "Symptomatic with negative serology",
      "Symptomatic with normal mucosa"],
     0, "Silent celiac disease: asymptomatic, serology positive. (Book p18)"),
    (U3, 18, "recall", "Latent celiac disease is:",
     ["Asymptomatic with negative antibodies but presence of HLA susceptibility",
      "Asymptomatic with positive serology",
      "Symptomatic with villous atrophy",
      "Refractory disease despite gluten withdrawal"],
     0, "Latent celiac disease: asymptomatic; antibodies negative; presence of HLA susceptibility. (Book p18)"),
    (U3, 18, "match",
     "Match the celiac spectrum label to the printed triad item — 1) Silent celiac 2) Latent celiac … A) Genetic susceptibility HLA-DQ2 or -DQ8 B) Intestinal mucosal abnormality with IgA EMA or tTG antibody positive",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Silent celiac: intestinal mucosal abnormality with IgA EMA or tTG antibody positive; latent celiac: genetic susceptibility HLA-DQ2 or -DQ8 in a healthy individual. (Book p18)"),

    # ----------------------------------------------------------------- p19
    (U4, 19, "recall", "The pathophysiology flow chart begins with:",
     ["HLA DQ2 or HLA DQ8 susceptibility",
      "Consumption of gluten containing foods",
      "Deamidation by tissue transglutaminase",
      "Activation of T cells"],
     0, "Pathophysiology: HLA DQ2 or HLA DQ8 susceptibility → consumption of gluten containing foods (wheat, barley, rye, oats). (Book p19)"),
    (U4, 19, "recall", "The gluten containing foods listed are:",
     ["Wheat, barley, rye and oats",
      "Rice, corn, maize and potato",
      "Soybean, millet and buckwheat",
      "Maize, rice and tapioca"],
     0, "Consumption of gluten containing foods (wheat, barley, rye, oats). (Book p19)"),
    (U4, 19, "recall", "The most toxic protein fraction of gluten is the:",
     ["Prolamine", "Albumin", "Globulin", "Glutenin"],
     0, "Proteins → prolamine (most toxic). (Book p19)"),
    (U4, 19, "recall", "The chief antigen of gluten is:",
     ["Gliadin", "Glutenin", "Albumin", "Secalin"],
     0, "Prolamine → gliadin (chief antigen of gluten). (Book p19)"),
    (U4, 19, "fillup", "Gliadin with glutamine is modified by ____ in the intestinal epithelium.",
     ["Tissue transglutaminase", "Pancreatic elastase", "Enterokinase", "Brush border lactase"],
     0, "Gliadin + glutamine → tissue transglutaminase → deamidation in the intestinal epithelium. (Book p19)"),
    (U4, 19, "recall", "Tissue transglutaminase acts on gliadin-bound glutamine by:",
     ["Deamidation", "Phosphorylation", "Glycosylation", "Decarboxylation"],
     0, "Tissue transglutaminase causes deamidation in the intestinal epithelium. (Book p19)"),
    (U4, 19, "match",
     "Order the printed pathway — 1) Prolamine 2) Gliadin + glutamine 3) Tissue transglutaminase 4) Deamidated glutamine dipeptide 5) Activates T cells … A) Activates T cells B) Prolamine C) Deamidated glutamine dipeptide D) Gliadin + glutamine E) Tissue transglutaminase",
     ["1-B, 2-D, 3-E, 4-C, 5-A", "1-A, 2-B, 3-C, 4-D, 5-E", "1-E, 2-D, 3-C, 4-B, 5-A", "1-B, 2-C, 3-D, 4-E, 5-A"],
     0, "Prolamine (most toxic) → gliadin (chief antigen) with glutamine → tissue transglutaminase → deamidated glutamine dipeptide → activates T cells → celiac disease. (Book p19)"),
    (U4, 19, "recall", "Polymeric IgA, which forms a dimer in this pathway, is produced from:",
     ["MALT", "Bone marrow", "Thymus", "Spleen"],
     0, "Polymeric IgA (produced from MALT) forms a dimer. (Book p19)"),
    (U4, 19, "recall", "Monomeric IgA is produced in the:",
     ["Bone marrow", "MALT", "Liver", "Peyer's patches"],
     0, "Note: monomeric IgA is produced in bone marrow. (Book p19)"),
    (U4, 19, "recall", "Which features are NOT seen in celiac disease, and why?",
     ["Vitamin B12, magnesium and bile acid deficiency — they are reabsorbed from the distal small intestine",
      "Steatorrhea — the distal ileum is normal",
      "Iron deficiency anemia — iron is absorbed distally",
      "Osteopenia — vitamin D is absorbed distally"],
     0, "Note: vitamin B12, Mg2+ and bile acid are reabsorbed from the distal small intestine → features not seen in celiac disease. (Book p19)"),
    (U4, 19, "numeric", "On a gluten-free diet, what proportion of patients revert to normalcy?",
     ["90%", "10%", "50%", "75%"],
     0, "Disease progression on a gluten-free diet: 90% revert to normalcy. (Book p19)"),
    (U4, 19, "recall", "Among the 90% who respond, clinical reversion occurs in:",
     ["3 weeks", "3 days", "6 months", "2 years"],
     0, "Reverts to normalcy: clinically 3 weeks. (Book p19)"),
    (U4, 19, "recall", "Among the 90% who respond, histological reversion occurs in:",
     ["6 months", "3 weeks", "1 week", "5 years"],
     0, "Reverts to normalcy: clinically 3 weeks, histologically 6 months. (Book p19)"),
    (U4, 19, "numeric", "What proportion show no improvement on a gluten-free diet?",
     ["10%", "90%", "30%", "50%"],
     0, "10% show no improvement → refractory celiac disease. (Book p19)"),
    (U4, 19, "recall", "Refractory celiac disease is treated with:",
     ["Steroids", "Azathioprine", "Co-trimoxazole", "Rifaximin"],
     0, "10% no improvement → refractory celiac disease → Rx: steroid. (Book p19)"),

    # ----------------------------------------------------------------- p20
    (U5, 20, "recall", "Classical / typical celiac disease presents with:",
     ["Osmotic diarrhea, abdominal distension, foul smelling stool and weight loss",
      "Short stature, fractures and ataxia",
      "Asymptomatic disease with positive serology",
      "Perianal fistulae and skip lesions"],
     0, "Classical/typical celiac: osmotic diarrhea, abdominal distension, foul smelling stool, weight loss. (Book p20)"),
    (U5, 20, "numeric", "What proportion of celiac patients have symptoms of IBS?",
     ["30%", "3%", "60%", "90%"],
     0, "Classical/typical celiac: symptoms of IBS (30%). (Book p20)"),
    (U5, 20, "recall", "Atypical celiac in children presents with:",
     ["Short stature and failure to thrive",
      "Perianal disease",
      "Painless rectal bleeding",
      "Obstructive jaundice"],
     0, "Atypical celiac: short stature, failure to thrive in children. (Book p20)"),
    (U5, 20, "recall", "Fracture and osteopenia in atypical celiac are attributed to:",
     ["↓ vitamin D and Ca2+ absorption", "↓ vitamin E", "↓ vitamin K", "↓ vitamin A"],
     0, "Atypical celiac: fracture, osteopenia — ↓ vitamin D, Ca2+ absorption. (Book p20)"),
    (U5, 20, "recall", "Ataxia and peripheral neuropathy in atypical celiac are attributed to:",
     ["↓ vitamin E", "↓ vitamin D", "↓ vitamin K", "↓ vitamin C"],
     0, "Atypical celiac: ataxia, peripheral neuropathy — ↓ vitamin E. (Book p20)"),
    (U5, 20, "recall", "Iron deficiency anemia is an atypical feature of celiac disease:",
     ["If it is not due to blood loss",
      "Only when there is overt bleeding",
      "Only in children",
      "Never — it excludes celiac disease"],
     0, "Atypical celiac: iron deficiency anemia (if not due to blood loss). (Book p20)"),
    (U5, 20, "match",
     "Match the atypical feature to its printed mechanism — 1) Fracture, osteopenia 2) Ataxia, peripheral neuropathy 3) Iron deficiency anemia … A) Not due to blood loss B) ↓ vitamin D and Ca2+ absorption C) ↓ vitamin E",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Fracture/osteopenia = ↓ vitamin D and Ca2+; ataxia/neuropathy = ↓ vitamin E; iron deficiency anemia = when not due to blood loss. (Book p20)"),
    (U5, 20, "recall", "Secondary hyperparathyroidism in celiac disease is due to:",
     ["↓ vitamin D and calcium", "↓ vitamin K", "↓ phosphate", "↑ calcitonin"],
     0, "Other features: secondary hyperparathyroidism — ↓ vitamin D, Ca2+. (Book p20)"),
    (U5, 20, "recall", "Cerebral calcifications in celiac disease are seen with:",
     ["Secondary hyperparathyroidism", "Vitamin E deficiency", "Folate deficiency", "Iron overload"],
     0, "Other features: calcifications in the brain seen with secondary hyperparathyroidism. (Book p20)"),
    (U5, 20, "recall", "Hyposplenism in celiac disease is identified by:",
     ["Presence of Howell-Jolly bodies", "Absence of platelets", "Low IgM", "Splenomegaly on scan"],
     0, "Other features: hyposplenism — presence of Howell-Jolly bodies. (Book p20)"),
    (U5, 20, "recall", "Follicular hyperkeratosis in celiac disease reflects deficiency of:",
     ["Vitamin A", "Vitamin E", "Vitamin K", "Vitamin C"],
     0, "Other features: follicular hyperkeratosis — ↓ vitamin A. (Book p20)"),
    (U5, 20, "recall", "Edema and ascites in celiac disease reflect:",
     ["Protein malabsorption", "Fat malabsorption", "Carbohydrate malabsorption", "Bile acid loss"],
     0, "Other features: edema and ascites — protein malabsorption. (Book p20)"),
    (U5, 20, "recall", "Cryptogenic cirrhosis in celiac disease is suggested by:",
     ["Raised LFT", "Low albumin alone", "Raised amylase", "Raised creatine kinase"],
     0, "Other features: cryptogenic cirrhosis — raised LFT. (Book p20)"),
    (U5, 20, "recall", "Amenorrhea, infertility and impotence are listed under:",
     ["Other features of celiac disease", "Definite associations", "Probable associations", "Complications"],
     0, "Other features of celiac disease: amenorrhea, infertility, impotence. (Book p20)"),

    (U6, 20, "recall", "The most important definite association of celiac disease is:",
     ["Dermatitis herpetiformis", "Down syndrome", "IgA nephropathy", "Type I diabetes mellitus"],
     0, "Definite associations: dermatitis herpetiformis (most important). (Book p20)"),
    (U6, 20, "recall", "The skin lesions of dermatitis herpetiformis are:",
     ["Papulovesicular lesions on the extensor aspect",
      "Maculopapular lesions on the flexor aspect",
      "Target lesions on the palms",
      "Nodular lesions on the trunk"],
     0, "Dermatitis herpetiformis features: papulovesicular lesions in extensor aspect. (Book p20)"),
    (U6, 20, "recall", "The immunofluorescence finding in dermatitis herpetiformis is:",
     ["Linear IgA deposits in the dermoepidermal junction",
      "Granular IgG deposits in the dermoepidermal junction",
      "IgM deposits in vessel walls",
      "C3 deposits along the basement membrane"],
     0, "Dermatitis herpetiformis: linear IgA deposits in dermoepidermal junction. (Book p20)"),
    (U6, 20, "recall", "Cryptogenic transaminitis / cirrhosis appears in the celiac association list as a:",
     ["Probable association", "Definite association", "Complication", "Exclusion criterion"],
     0, "Probable associations: cryptogenic transaminitis/cirrhosis, idiopathic short stature, refractory iron deficiency anemia, cerebellar ataxia. (Book p20)"),
    (U6, 20, "oddoneout", "All of the following are probable associations of celiac disease EXCEPT:",
     ["Lymphocytic colitis", "Idiopathic short stature", "Refractory iron deficiency anemia", "Cerebellar ataxia"],
     0, "Probable associations: cryptogenic transaminitis/cirrhosis, idiopathic short stature, refractory iron deficiency anemia, cerebellar ataxia. Lymphocytic colitis is a definite association. (Book p20)"),
    (U6, 20, "oddoneout", "Pick the ODD ONE OUT — one is a probable, not definite, association of celiac disease:",
     ["Cerebellar ataxia", "Type I diabetes mellitus", "IgA deficiency", "Bird-fancier lung"],
     0, "Probable associations: cryptogenic transaminitis/cirrhosis, idiopathic short stature, refractory iron deficiency anemia, cerebellar ataxia. The others are definite. (Book p20)"),
    (U6, 20, "recall", "Hypersensitivity pneumonitis in the celiac association list is also called:",
     ["Bird-fancier lung", "Farmer's lung", "Bagassosis", "Byssinosis"],
     0, "Definite associations: hypersensitivity pneumonitis / bird-fancier lung. (Book p20)"),

    # ----------------------------------------------------------------- p21
    (U7, 21, "recall", "The serological test described as most important for diagnosis and monitoring is:",
     ["Anti-TTG antibody (IgA)",
      "Anti-endomysial antibody (IgA)",
      "Anti-deamidated glutamine dipeptide (IgG)",
      "Anti-gliadin antibody"],
     0, "Serology: 1. anti-TTG antibody (IgA) — most important for diagnosis, monitoring. (Book p21)"),
    (U7, 21, "numeric", "The specificity of anti-TTG antibody quoted in the book is:",
     ["98%", "73%", "99%", "50%"],
     0, "Anti-TTG antibody (IgA): high sensitivity, high specificity (98%). (Book p21)"),
    (U7, 21, "recall", "Anti-endomysial antibody testing is performed by:",
     ["Indirect immunofluorescence", "ELISA alone", "Western blot", "PCR"],
     0, "2. Anti-endomysial antibody (IgA): done by indirect immunofluorescence. (Book p21)"),
    (U7, 21, "numeric", "The sensitivity quoted for anti-endomysial antibody is:",
     ["99%", "73%", "98%", "50%"],
     0, "Anti-endomysial antibody (IgA): high sensitivity (99%). (Book p21)"),
    (U7, 21, "numeric", "The specificity quoted for anti-endomysial antibody is:",
     ["73%", "98%", "99%", "90%"],
     0, "Anti-endomysial antibody (IgA): poor specificity (73%). (Book p21)"),
    (U7, 21, "recall", "The disadvantages listed for anti-endomysial antibody are:",
     ["Subjective interpretation and cumbersome procedure",
      "Requires radiation exposure",
      "Needs a mucosal biopsy",
      "Only detect IgG"],
     0, "Anti-endomysial antibody — disadvantage: subjective interpretation and cumbersome procedure. (Book p21)"),
    (U7, 21, "recall", "Anti-deamidated glutamine dipeptide antibody is of which isotype, and when is it used?",
     ["IgG — in patients with IgA deficiency",
      "IgA — as the first line test",
      "IgM — in children",
      "IgE — in dermatitis herpetiformis"],
     0, "3. Anti-deamidated glutamine dipeptide (IgG): done in patients with IgA deficiency. (Book p21)"),
    (U7, 21, "recall", "The sensitivity and specificity of anti-deamidated glutamine dipeptide antibody are described as:",
     ["Low", "High", "Moderate and high", "Not established"],
     0, "Anti-deamidated glutamine dipeptide (IgG): low sensitivity, specificity. (Book p21)"),
    (U7, 21, "recall", "Anti-gliadin antibody testing is described as:",
     ["Obsolete", "Gold standard", "Most specific", "The preferred screening test"],
     0, "4. Anti-gliadin: obsolete. (Book p21)"),
    (U7, 21, "match",
     "Match the celiac serology to its printed isotype — 1) Anti-TTG 2) Anti-endomysial 3) Anti-deamidated glutamine dipeptide … A) IgG B) IgA C) IgA",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Anti-TTG — IgA; anti-endomysial — IgA; anti-deamidated glutamine dipeptide — IgG. (Book p21)"),
    (U7, 21, "recall", "The biopsy note states that the findings of celiac disease are localised to the:",
     ["Mucosa", "Submucosa", "Muscularis propria", "Serosa"],
     0, "Biopsy: 1. findings localised to mucosa. (Book p21)"),
    (U7, 21, "recall", "The two principal mucosal biopsy findings listed are:",
     ["Total villous atrophy and crypt hyperplasia",
      "Transmural inflammation and granulomas",
      "Pyloric metaplasia and fibrosis",
      "Crypt abscesses and fissures"],
     0, "Biopsy: 2. total villous atrophy, 3. crypt hyperplasia. (Book p21)"),
    (U7, 21, "recall", "Mucosal thickness in celiac biopsy is:",
     ["Normal", "Increased", "Decreased", "Replaced by fibrosis"],
     0, "Biopsy: 4. normal mucosal thickness. (Book p21)"),
    (U7, 21, "recall", "Lymphocyte infiltrates in celiac biopsy are seen in the:",
     ["Lamina propria", "Muscularis mucosa", "Submucosa", "Myenteric plexus"],
     0, "Biopsy: 5. lymphocyte infiltrates in lamina propria. (Book p21)"),
    (U7, 21, "recall", "The biopsy finding described as non-specific is:",
     ["Vascular degeneration of surface epithelium", "Total villous atrophy", "Crypt hyperplasia", "Lymphocyte infiltrates"],
     0, "Biopsy: 6. vascular degeneration of surface epithelium (non-specific). (Book p21)"),
    (U7, 21, "fillup", "The grading system shown next to the celiac biopsy image is the ____ score.",
     ["Marsh", "Mayo", "Truelove & Witts", "Child-Pugh"],
     0, "Biopsy image: celiac disease during reversibility with the Marsh score. (Book p21)"),

    # ----------------------------------------------------------------- p22
    (U8, 22, "match",
     "Interpret the serology and biopsy combinations as printed — 1) Both positive 2) Both negative 3) Serology positive, biopsy negative 4) Serology negative, biopsy positive … A) Repeat biopsy B) Celiac disease C) Not celiac disease; biopsy findings non-specific D) Not celiac disease; if features suggestive, test HLA DQ2/DQ8",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "Both +ve → celiac disease; both −ve → not celiac disease (if features suggestive → HLA DQ2/DQ8); serology +ve/biopsy −ve → repeat biopsy; serology −ve/biopsy +ve → not celiac disease, biopsy findings non-specific. (Book p22)"),
    (U8, 22, "recall", "When both serology and biopsy are negative but features still suggest celiac disease, the book advises:",
     ["HLA DQ2 / DQ8 testing",
      "Immediate gluten-free diet",
      "Repeat biopsy after gluten challenge",
      "No further testing"],
     0, "Both −ve → not celiac disease; if features suggestive of celiac disease → HLA DQ2/DQ8. (Book p22)"),
    (U8, 22, "recall", "Serology negative but biopsy positive is interpreted as:",
     ["Not celiac disease — the biopsy findings are non-specific",
      "Celiac disease",
      "Refractory celiac disease",
      "Latent celiac disease"],
     0, "Serology −ve, biopsy +ve → not celiac disease; biopsy findings are non-specific. (Book p22)"),
    (U8, 22, "recall", "The examples given of non-specific biopsy findings with negative serology are:",
     ["Tropical sprue and cow's milk intolerance",
      "Crohn's disease and tuberculosis",
      "SIBO and chronic pancreatitis",
      "Amyloidosis and lymphoma"],
     0, "Non-specific biopsy findings e.g.: tropical sprue, cow's milk intolerance. (Book p22)"),
    (U8, 22, "recall", "Complications of celiac disease are seen in:",
     ["Refractory celiac disease", "Silent celiac disease", "Latent celiac disease", "Dermatitis herpetiformis"],
     0, "Complications: seen in refractory celiac disease. (Book p22)"),
    (U8, 22, "recall", "The most common malignancy complicating celiac disease is:",
     ["Enteropathy associated T-cell lymphoma",
      "Small intestinal adenocarcinoma",
      "Esophageal squamous cell carcinoma",
      "Cholangiocarcinoma"],
     0, "It is a premalignant condition: enteropathy associated T-cell lymphoma (m/c). (Book p22)"),
    (U8, 22, "recall", "Besides lymphoma, the premalignant complications listed are:",
     ["Small intestinal adenocarcinoma and esophageal squamous cell carcinoma",
      "Gastric adenocarcinoma and colorectal carcinoma",
      "Hepatocellular carcinoma and cholangiocarcinoma",
      "Pancreatic adenocarcinoma and carcinoid"],
     0, "Premalignant: enteropathy associated T-cell lymphoma (m/c), small intestinal adenocarcinoma, esophageal squamous cell carcinoma. (Book p22)"),
    (U8, 22, "recall", "The diet advised in celiac treatment is based on:",
     ["Rice, corn, maize, potato and soybean",
      "Wheat, barley, rye and oats",
      "Milk and cheese",
      "Red meat and eggs"],
     0, "Treatment — diet: rice, corn, maize, potato, soybean based. (Book p22)"),
    (U8, 22, "recall", "The dietary restriction in celiac disease is of:",
     ["Wheat, barley, rye and oats", "Rice and maize", "Potato and soybean", "Milk and cheese"],
     0, "Treatment — diet: restriction of wheat, barley, rye, oats. (Book p22)"),
    (U8, 22, "scenario",
     "A patient with biopsy-proven celiac disease has persistent villous atrophy after 12 months of strict gluten withdrawal. The book's next step is:",
     ["Steroids for refractory celiac disease",
      "Co-trimoxazole",
      "Total parenteral nutrition",
      "Procto-colectomy"],
     0, "10% show no improvement → refractory celiac disease → Rx: steroid. (Book p22)"),

    (U9, 22, "recall", "Whipple's disease is described as:",
     ["Chronic multisystem involvement of joints, GIT, CNS and CVS",
      "An isolated large bowel diarrhea",
      "A purely cutaneous disorder",
      "A disease of the biliary tree"],
     0, "Whipple's disease — presentation: chronic multisystem involvement (joints, GIT, CNS, CVS). (Book p22)"),
    (U9, 22, "recall", "The demographic described for Whipple's disease is:",
     ["M > F, 50-60 years", "F > M, 20-30 years", "Equal sex ratio, 5-15 years", "F > M, 70-80 years"],
     0, "Presentation: M > F, 50-60 yrs. (Book p22)"),
    (U9, 22, "recall", "The intestinal involvement in Whipple's disease is:",
     ["Pan-intestinal, proximal more than distal",
      "Confined to the rectum",
      "Confined to the distal ileum",
      "Confined to the colon"],
     0, "Presentation: pan-intestinal — proximal > distal. (Book p22)"),
    (U9, 22, "recall", "The organism causing Whipple's disease is:",
     ["Tropheryma whipplei — a gram positive actinobacterium",
      "Mycobacterium avium complex",
      "Actinomyces israelii",
      "Nocardia asteroides"],
     0, "Tropheryma whipplei: gram +ve actinobacterium. (Book p22)"),
    (U9, 22, "recall", "Tropheryma whipplei cannot be cultured because of its:",
     ["Slow doubling time", "Obligate intracellular location", "Requirement for microaerophilic conditions", "Inability to grow on any known medium"],
     0, "Tropheryma whipplei: gram +ve actinobacterium that cannot be cultured d/t slow doubling time. (Book p22)"),
    (U9, 22, "recall", "Diagnosis of Whipple's disease is by:",
     ["Biopsy", "Serology", "Stool culture", "Barium study"],
     0, "Whipple's disease — Dx: biopsy. (Book p22)"),

    # ----------------------------------------------------------------- p23
    (U10, 23, "numeric", "Joint symptoms are the first symptom in what proportion of Whipple's disease?",
     [">80%", "40%", "10%", "50%"],
     0, "Joints: first symptom in >80% cases. (Book p23)"),
    (U10, 23, "recall", "The joints predominantly involved in Whipple's disease are:",
     ["Large joints, especially the knee", "Small joints of the hand", "Sacroiliac joints", "Temporomandibular joints"],
     0, "Joints: predominance — large joints (knee). (Book p23)"),
    (U10, 23, "recall", "The joint pattern in Whipple's disease is:",
     ["Migratory arthralgia more than arthritis",
      "Symmetrical destructive arthritis",
      "Ankylosing spondylitis like axial disease",
      "Monoarthritis of the hip"],
     0, "Joints: pattern — migratory arthralgia > arthritis. (Book p23)"),
    (U10, 23, "recall", "Gastrointestinal features appear:",
     ["2-3 years after the joint features",
      "Simultaneously with joint features",
      "Before the joint features",
      "Only in the terminal phase"],
     0, "GIT: 2-3 yrs after joint features. (Book p23)"),
    (U10, 23, "recall", "The most consistent gastrointestinal feature of Whipple's disease is:",
     ["Diarrhea", "Constipation", "Haematemesis", "Jaundice"],
     0, "GIT: diarrhea (most consistent). (Book p23)"),
    (U10, 23, "recall", "Besides diarrhea and weight loss, the GIT column lists:",
     ["Abdominal pain with mesenteric lymphadenopathy",
      "Perianal fistulae",
      "Toxic megacolon",
      "Painless rectal bleeding"],
     0, "GIT: diarrhea (most consistent), weight loss, abdominal pain + mesenteric lymphadenopathy. (Book p23)"),
    (U10, 23, "numeric", "Neurological involvement occurs in what proportion of Whipple's disease?",
     ["40%", "4%", "80%", "10%"],
     0, "Neuro Whipple's (40%). (Book p23)"),
    (U10, 23, "recall", "The most common neurological manifestation of Whipple's disease is:",
     ["Rapidly progressive dementia",
      "Oculomasticatory myorhythmia",
      "Supranuclear ophthalmoplegia",
      "Peripheral neuropathy"],
     0, "Neuro Whipple's: m/c neurological manifestation — rapidly progressive dementia. (Book p23)"),
    (U10, 23, "recall", "The most specific neurological manifestation of Whipple's disease is:",
     ["Oculomasticatory myorhythmia, then oculofacial myorhythmia",
      "Rapidly progressive dementia",
      "Cerebellar ataxia",
      "Generalised seizures"],
     0, "Neuro Whipple's: m/c specific manifestation — oculomasticatory myorhythmia > oculofacial myorhythmia. (Book p23)"),
    (U10, 23, "recall", "Oculomasticatory myorhythmia consists of:",
     ["Pendular nystagmus and masticatory arrhythmias",
      "Ptosis and diplopia",
      "Hemifacial spasm and dysphagia",
      "Opsoclonus and myoclonus"],
     0, "Oculomasticatory myorhythmia: pendular nystagmus + masticatory arrhythmias. (Book p23)"),
    (U10, 23, "recall", "Oculomasticatory myorhythmia is associated with:",
     ["Supranuclear ophthalmoplegia", "Internuclear ophthalmoplegia", "Optic neuritis", "Horner syndrome"],
     0, "Oculomasticatory myorhythmia is associated with supranuclear ophthalmoplegia. (Book p23)"),
    (U10, 23, "recall", "Relapse with CNS manifestations in Whipple's disease indicates:",
     ["Bad prognosis", "Good prognosis", "Need for surgery", "Coeliac disease"],
     0, "Relapse associated with CNS manifestations: bad prognosis. (Book p23)"),
    (U10, 23, "recall", "The CVS lesion of Whipple's disease is:",
     ["Culture negative endocarditis, mitral valve more than myocarditis more than pericarditis",
      "Culture positive aortic valve endocarditis",
      "Constrictive pericarditis",
      "Dilated cardiomyopathy"],
     0, "CVS: culture negative endocarditis — mitral valve > myocarditis > pericarditis. (Book p23)"),
    (U10, 23, "recall", "Culture negative endocarditis in Whipple's disease is caused by which group?",
     ["HACEK group", "Viridans streptococci", "Enterococci", "Staphylococcus aureus"],
     0, "Culture negative endocarditis: HACEK group. (Book p23)"),
    (U10, 23, "match",
     "Match the HACEK organisms as printed — 1) H 2) A 3) C 4) E 5) K … A) Aggregatibacter actinomycetemcomitans B) Haemophilus C) Kingella D) Cardiobacter E) Eikenella",
     ["1-B, 2-A, 3-D, 4-E, 5-C", "1-A, 2-B, 3-C, 4-D, 5-E", "1-E, 2-D, 3-C, 4-B, 5-A", "1-B, 2-E, 3-A, 4-C, 5-D"],
     0, "HACEK: Haemophilus, Aggregatibacter actinomycetemcomitans, Cardiobacter, Eikenella, Kingella. (Book p23)"),
    (U10, 23, "recall", "The tetrad illustrated for Whipple's disease consists of:",
     ["Joint symptoms, diarrhea, weight loss, and abdominal pain with mesenteric lymphadenopathy",
      "Dementia, ophthalmoplegia, myorhythmia and ataxia",
      "Fever, rash, arthritis and serositis",
      "Steatorrhea, anemia, osteopenia and dermatitis"],
     0, "Whipple's tetrad: joint symptoms, diarrhea, weight loss, abdominal pain + mesenteric lymphadenopathy. (Book p23)"),
    (U10, 23, "recall", "Upper GI endoscopy with biopsy is described as diagnostic in what proportion?",
     ["100%", "50%", "90%", "73%"],
     0, "Diagnosis: upper GI endoscopy — biopsy: 100%. (Book p23)"),
    (U10, 23, "recall", "The PCR test in Whipple's disease identifies:",
     ["Tropheryma whipplei", "Mycobacterium tuberculosis", "HLA DQ2", "Tropheryma DNA in blood only"],
     0, "Diagnosis: PCR — identification of Tropheryma whipplei. (Book p23)"),
    (U10, 23, "match",
     "Match the differential of Whipple's disease to the system — 1) Joint symptoms 2) GIT symptoms … A) TB B) Spondyloarthritis",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Differential diagnosis: joint symptoms — spondyloarthritis; GIT symptoms — TB. (Book p23)"),

    # ----------------------------------------------------------------- p24
    (U11, 24, "recall", "The best induction regimen for Whipple's disease is:",
     ["IV ceftriaxone 2 g for 14 days",
      "Oral co-trimoxazole for 6 months",
      "IV meropenem for 3 days",
      "Oral rifaximin for 7 days"],
     0, "Treatment — induction: IV ceftriaxone 2 g × 14 days: best regimen. (Book p24)"),
    (U11, 24, "recall", "Alternatives listed for induction in Whipple's disease are:",
     ["Meropenem, and penicillin plus streptomycin",
      "Rifaximin and neomycin",
      "Co-trimoxazole and metronidazole",
      "Tetracycline and folic acid"],
     0, "Induction: IV ceftriaxone 2 g × 14 days (best), meropenem, penicillin + streptomycin. (Book p24)"),
    (U11, 24, "recall", "Maintenance therapy in Whipple's disease is with:",
     ["Co-trimoxazole", "Ceftriaxone", "Rifaximin", "Doxycycline"],
     0, "Maintenance: co-trimoxazole (DOC). (Book p24)"),
    (U11, 24, "recall", "The stated advantages of co-trimoxazole maintenance are:",
     ["Prevents relapse and has good CNS penetration",
      "Sterilises the gut and corrects folate deficiency",
      "Is cheap and once weekly",
      "Avoids the need for induction"],
     0, "Maintenance: co-trimoxazole — prevent relapse, good CNS penetration. (Book p24)"),
    (U11, 24, "recall", "The diagnostic biopsy in Whipple's disease shows:",
     ["PAS positive foamy macrophages in epithelium, lamina propria and submucosa",
      "Non-caseating granulomas",
      "Total villous atrophy with crypt hyperplasia",
      "Vacuolation of enterocytes"],
     0, "Biopsy: PAS +ve foamy macrophages seen in epithelium, lamina propria, submucosa; macrophages contain the organism. (Book p24)"),
    (U11, 24, "recall", "The villi in the Whipple's biopsy image are described as:",
     ["Enlarged", "Atrophic", "Absent", "Bridge-forming"],
     0, "Biopsy image: PAS +ve foamy macrophages with enlarged villi. (Book p24)"),

    (U12, 24, "recall", "Tropical sprue is the most common cause of malabsorption in:",
     ["India, Bangladesh and Pakistan", "North America and Western Europe", "Sub-Saharan Africa", "Australia"],
     0, "Tropical sprue: m/c cause of malabsorption in India, Bangladesh, Pakistan. (Book p24)"),
    (U12, 24, "recall", "Histologically, tropical sprue resembles:",
     ["Celiac disease", "Whipple's disease", "Crohn's disease", "Microscopic colitis"],
     0, "Tropical sprue: histological features similar to celiac disease. (Book p24)"),
    (U12, 24, "recall", "The initiating event in the printed pathogenesis of tropical sprue is:",
     ["Infective diarrhea",
      "Gluten ingestion",
      "Autoimmune villous atrophy",
      "Bile acid malabsorption"],
     0, "Pathogenesis: infective diarrhea → presence of toxigenic coliform in intestine. (Book p24)"),
    (U12, 24, "recall", "The toxigenic coliforms implicated in tropical sprue are:",
     ["E. coli and Klebsiella", "Salmonella and Shigella", "Campylobacter and Vibrio", "Bacteroides and Clostridium"],
     0, "Presence of toxigenic coliform in intestine (E. coli, Klebsiella). (Book p24)"),
    (U12, 24, "recall", "The major fermentation product implicated in tropical sprue is:",
     ["Ethanol", "Lactate", "Methane", "Short chain fatty acids"],
     0, "Fermentation products (major product: ethanol). (Book p24)"),
    (U12, 24, "recall", "Structural damage to the small intestine in tropical sprue impairs absorption of:",
     ["Folic acid", "Vitamin K", "Vitamin A", "Iron"],
     0, "Structural damage to small intestine → impairs absorption of folic acid. (Book p24)"),
    (U12, 24, "recall", "The interval after which pan-intestinal involvement develops is:",
     ["2-3 weeks", "2-3 days", "2-3 months", "2-3 years"],
     0, "Impaired folic acid absorption → 2-3 weeks → pan-intestinal involvement. (Book p24)"),
    (U12, 24, "recall", "Pan-intestinal involvement causes defective absorption of:",
     ["Vitamin B12, bile acid and Mg2+", "Iron only", "Vitamin K only", "Vitamin C and folate"],
     0, "Pan-intestinal involvement → defective B12, bile acid, Mg2+ absorption. (Book p24)"),

    # ----------------------------------------------------------------- p25
    (U13, 25, "recall", "The diarrhea of tropical sprue is described as:",
     ["Chronic small bowel diarrhea that is watery and voluminous",
      "Large bowel diarrhea with blood and mucus",
      "Factitious diarrhea with normal stool osmolality",
      "Nocturnal secretory diarrhea only"],
     0, "Clinical features: chronic small bowel diarrhea (watery, voluminous). (Book p25)"),
    (U13, 25, "recall", "The most prominent deficiency in tropical sprue is:",
     ["Folic acid deficiency", "Vitamin B12 deficiency", "Vitamin K deficiency", "Iron deficiency"],
     0, "Clinical features: folic acid deficiency (most prominent). (Book p25)"),
    (U13, 25, "recall", "Hyperpigmentation in tropical sprue is attributed to:",
     ["Vitamin B12 deficiency", "Folic acid deficiency", "Iron overload", "ACTH excess"],
     0, "Clinical features: hyperpigmentation — d/t B12 deficiency. (Book p25)"),
    (U13, 25, "recall", "Biopsy in tropical sprue shows:",
     ["Features of celiac disease", "Non-caseating granulomas", "PAS positive macrophages", "Normal mucosa"],
     0, "Investigations: biopsy — features of celiac disease. (Book p25)"),
    (U13, 25, "recall", "Serology in tropical sprue is:",
     ["Negative", "Positive for anti-TTG", "Positive for anti-endomysial", "Positive for ASCA"],
     0, "Investigations: serology — negative. (Book p25)"),
    (U13, 25, "recall", "Stool examination in tropical sprue is performed for:",
     ["Ova, cyst and trophozoite to rule out giardiasis",
      "Occult blood",
      "Fecal elastase",
      "Reducing substances"],
     0, "Investigations: stool examination for ova, cyst, trophozoite (to rule out giardiasis). (Book p25)"),
    (U13, 25, "recall", "The treatment of tropical sprue is:",
     ["Folic acid 5 mg daily plus tetracycline 250 mg QID for 3-6 months",
      "Gluten-free diet alone",
      "Co-trimoxazole for 14 days",
      "Medium chain triglyceride diet alone"],
     0, "Treatment: folic acid 5 mg daily + tetracycline 250 mg QID for 3-6 months. (Book p25)"),
    (U13, 25, "numeric", "The dose of folic acid used in tropical sprue is:",
     ["5 mg daily", "50 mg daily", "0.5 mg daily", "500 mg daily"],
     0, "Treatment: folic acid 5 mg daily. (Book p25)"),
    (U13, 25, "numeric", "The dose and frequency of tetracycline used in tropical sprue is:",
     ["250 mg QID", "250 mg BD", "500 mg TID", "1 g once weekly"],
     0, "Treatment: tetracycline 250 mg QID. (Book p25)"),
    (U13, 25, "recall", "The duration of tropical sprue treatment is:",
     ["3-6 months", "7-10 days", "14 days", "Lifelong"],
     0, "Treatment: folic acid + tetracycline for 3-6 months. (Book p25)"),
    (U13, 25, "numeric", "Relapse occurs in what proportion of treated tropical sprue?",
     ["20%", "2%", "50%", "90%"],
     0, "Note: relapse in 20% of cases. (Book p25)"),
    (U13, 25, "recall", "In SIBO the organism uses vitamin B12 and therefore:",
     ["Synthesises folic acid", "Destroys folate", "Blocks folate absorption", "Converts folate to B12"],
     0, "Note: in SIBO the organism uses B12 → synthesises folic acid. (Book p25)"),

    (U14, 25, "recall", "Bile acid diarrhea is also known as:",
     ["Cholorrhea", "Steatorrhea", "Lientery", "Melena"],
     0, "Bile acid diarrhea: AKA cholorrhea. (Book p25)"),
    (U14, 25, "recall", "Bile acid diarrhea is seen in:",
     ["Tropical sprue", "Celiac disease", "Whipple's disease", "Cystinuria"],
     0, "Bile acid diarrhea: seen in tropical sprue. (Book p25)"),
    (U14, 25, "recall", "Bile acid diarrhea is due to defective:",
     ["FGF-19", "GLP-1", "Peptide YY", "Gastrin"],
     0, "Bile acid diarrhea: due to defective FGF-19. (Book p25)"),
    (U14, 25, "recall", "Defective FGF-19 leads to:",
     ["↓ bile acid released in the ileum", "↑ bile acid synthesis in the colon", "Bile duct destruction", "Loss of the ileocecal valve"],
     0, "Pathology: defective FGF-19 → ↓ bile acid released in the ileum. (Book p25)"),
    (U14, 26, "recall", "In limited ileal disease, FGF-19 is present in limited quantity so the liver:",
     ["Produces excess bile acid as compensation",
      "Stops producing bile acid",
      "Produces lithocholic acid only",
      "Excretes bile acid into urine"],
     0, "Limited ileal disease: FGF-19 +ve in limited quantity → liver produces excess bile acid (compensatory). (Book p26)"),
    (U14, 26, "recall", "In bile acid diarrhea, bile acid in the intestinal lumen removes:",
     ["Na+, Cl− and K+ from the intestinal epithelium",
      "Calcium and oxalate from the lumen",
      "Bicarbonate from the pancreas",
      "Folate from the diet"],
     0, "Bile acid removes Na+, Cl−, K+ from intestinal epithelium → bile acid diarrhea. (Book p26)"),
    (U14, 26, "recall", "The statement made about bile acid diarrhea is that there is:",
     ["No steatorrhea or malabsorption",
      "Severe steatorrhea",
      "Massive protein loss",
      "Frank rectal bleeding"],
     0, "Bile acid diarrhea: no steatorrhea / malabsorption. (Book p26)"),
    (U14, 26, "recall", "Fatty acid diarrhea occurs with:",
     ["Severe ileal disease", "Limited ileal disease", "Gastric resection", "Coeliac disease"],
     0, "Fatty acid diarrhea: severe ileal disease. (Book p26)"),
    (U14, 26, "match",
     "Order the printed fatty acid diarrhea pathway — 1) Severe ileal disease 2) Impaired reabsorption of bile acid 3) No compensatory release 4) Malabsorption 5) Fatty acid in colon … A) Malabsorption B) Severe ileal disease C) Fatty acid in colon D) No compensatory release E) Impaired reabsorption of bile acid",
     ["1-B, 2-E, 3-D, 4-A, 5-C", "1-A, 2-B, 3-C, 4-D, 5-E", "1-E, 2-D, 3-C, 4-B, 5-A", "1-B, 2-D, 3-E, 4-C, 5-A"],
     0, "Severe ileal disease → impaired reabsorption of bile acid → no compensatory release → malabsorption → fatty acid in colon. (Book p26)"),
    (U14, 26, "numeric", "The steatorrhea of fatty acid diarrhea is quantified in the book as:",
     ["> 20 g", "> 7 g", "> 50 g", "> 100 g"],
     0, "Fatty acid diarrhea: fatty acid in colon → steatorrhea (> 20 g). (Book p26)"),
    (U14, 26, "match",
     "Match the treatment response as printed — 1) Bile acid diarrhea 2) Fatty acid diarrhea … A) Responds to low-fat diet B) Responds to cholestyramine",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Response to cholestyramine: yes in bile acid diarrhea, no in fatty acid diarrhea; response to low-fat diet: no in bile acid diarrhea, yes in fatty acid diarrhea. (Book p26)"),
    (U14, 26, "scenario",
     "A patient with ileal disease has watery diarrhea without steatorrhea. Cholestyramine abolishes the diarrhea. This fits:",
     ["Bile acid diarrhea", "Fatty acid diarrhea", "Factitious diarrhea", "Osmotic diarrhea from lactase deficiency"],
     0, "Bile acid diarrhea: no steatorrhea and responds to cholestyramine. (Book p26)"),

    (U15, 26, "numeric", "Short bowel syndrome is defined as a small intestinal length below:",
     ["200 cm", "100 cm", "400 cm", "50 cm"],
     0, "Length of small intestine: short bowel syndrome < 200 cm. (Book p26)"),
    (U15, 26, "numeric", "Very severe short bowel syndrome is defined as a length below:",
     ["100 cm", "200 cm", "50 cm", "150 cm"],
     0, "Very severe short bowel syndrome: < 100 cm. (Book p26)"),
    (U15, 26, "recall", "The most common cause of short bowel syndrome in adults is:",
     ["Mesenteric vascular disease (ischemia of bowel with resection), more than Crohn's disease",
      "Crohn's disease, more than mesenteric vascular disease",
      "Trauma",
      "Radiation enteritis"],
     0, "Etiology (m/c) — adult: mesenteric vascular disease (ischemia of bowel → resection) > Crohn's disease. (Book p26)"),
    (U15, 26, "recall", "The most common cause of short bowel syndrome in children is:",
     ["Necrotising enterocolitis", "Intussusception", "Meckel's diverticulum", "Hirschsprung disease"],
     0, "Etiology (m/c) — child: necrotising enterocolitis. (Book p26)"),

    # ----------------------------------------------------------------- p27
    (U16, 27, "recall", "In normal physiology, oxalate and calcium form an ____ that is excreted.",
     ["insoluble complex", "absorbable complex", "osmotic agent", "bile salt"],
     0, "Normal physiology: oxalate + Ca2+ → insoluble → excreted. (Book p27)"),
    (U16, 27, "recall", "When the proximal small intestine is absent, unabsorbed long chain fatty acids bind calcium so that:",
     ["Free oxalate enters the blood and produces oxalate stones",
      "Oxalate is excreted normally",
      "Calcium oxalate precipitates in the gut",
      "Oxalate is converted to citrate"],
     0, "Absent proximal small intestine: unabsorbed LCFA bind Ca2+ → free oxalate → into blood → oxalate stones in urine. (Book p27)"),
    (U16, 27, "match",
     "Order the printed hyperoxaluria pathway — 1) Unabsorbed LCFA 2) Free oxalate 3) Into blood 4) Oxalate stones in urine … A) Into blood B) Unabsorbed LCFA C) Oxalate stones in urine D) Free oxalate",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "Unabsorbed long chain fatty acids → free oxalate → into blood → oxalate stones in urine. (Book p27)"),
    (U16, 27, "recall", "Cholesterol gallstones in short bowel syndrome are attributed to:",
     ["Absent ileum, so bile acids and vitamin B12 are not absorbed, causing supersaturation",
      "Excess cholesterol synthesis",
      "Haemolysis",
      "Chronic cholecystitis"],
     0, "Cholesterol gallstones: absent ileum → bile acids, vitamin B12 not absorbed → supersaturation. (Book p27)"),
    (U16, 27, "recall", "Physiologically the colon forms which lactate isomer, and which organism is the normal flora named?",
     ["L-lactate, with Bacteroides fragilis",
      "D-lactate, with Lactobacillus",
      "L-lactate, with Lactobacillus",
      "D-lactate, with Bacteroides fragilis"],
     0, "D-lactic acidosis — physiological: L-lactate formed; flora of colon: Bacteroides fragilis. (Book p27)"),
    (U16, 27, "recall", "D-lactic acidosis follows excessive fermentation by:",
     ["Gram positive anaerobes", "Gram negative aerobes", "Fungi", "Mycobacteria"],
     0, "Excessive fermentation by gram positive anaerobes → ↓ pH in the colonic lumen. (Book p27)"),
    (U16, 27, "recall", "The bacterial overgrowth producing D-lactate is attributed to:",
     ["Lactobacillus and Bifidobacterium", "Bacteroides fragilis", "E. coli and Klebsiella", "Pseudomonas"],
     0, "Bacterial overgrowth (Lactobacillus, Bifidobacterium) → D-lactate (not metabolised). (Book p27)"),
    (U16, 27, "recall", "D-lactate is absorbed into blood and produces:",
     ["D-lactic acidosis with CNS manifestations",
      "Metabolic alkalosis",
      "Lactic acidosis that is easily metabolised",
      "Hyperchloraemic acidosis without symptoms"],
     0, "D-lactate (not metabolised) → absorbed into blood → D-lactic acidosis → CNS manifestations. (Book p27)"),
    (U16, 27, "recall", "Hypergastrinemia in short bowel syndrome arises because:",
     ["Absent small bowel reduces intestinal hormones, leaving gastrin uninhibited",
      "A gastrinoma develops",
      "H. pylori infection supervenes",
      "Renal failure reduces gastrin clearance"],
     0, "Hypergastrinemia: absent small bowel → ↓ intestinal hormones → gastrin uninhibited. (Book p27)"),
    (U16, 27, "recall", "Hypomagnesemia in short bowel syndrome is due to:",
     ["No Mg2+ absorption from the ileum", "Renal magnesium wasting", "Poor dietary intake", "Vitamin D deficiency"],
     0, "Hypomagnesemia: no Mg2+ absorption from ileum. (Book p27)"),
    (U16, 27, "recall", "Defective ileal break produces:",
     ["↑ gastric emptying", "↓ gastric emptying", "Pyloric stenosis", "Gastroparesis"],
     0, "6. ↑ gastric emptying: defective ileal break. (Book p27)"),
    (U16, 27, "recall", "The physiology of the ileal break is mediated by:",
     ["GLP-1, GLP-2 and peptide YY, which reduce motility and slow gastric emptying",
      "Gastrin and histamine",
      "Motilin and ghrelin",
      "Secretin and CCK"],
     0, "Physiology: GLP-1, GLP-2, peptide YY → ↓ motility → ↓ gastric emptying (ileal break). (Book p27)"),
    (U16, 27, "fillup", "The ileal break is triggered when unabsorbed ____ enters the ileum.",
     ["fat", "carbohydrate", "protein", "bile acid"],
     0, "Ileal break: ↑ unabsorbed fat enters ileum. (Book p27)"),

    # ----------------------------------------------------------------- p28
    (U17, 28, "recall", "Iron deficiency in short bowel syndrome occurs with absence of:",
     ["Duodenum more than jejunum", "Ileum more than colon", "Colon more than stomach", "Jejunum more than duodenum"],
     0, "Deficiencies: Fe — in absent duodenum > jejunum. (Book p28)"),
    (U17, 28, "recall", "Calcium, folate and vitamins A, D and E deficiency occur with absence of the:",
     ["Jejunum", "Ileum", "Colon", "Stomach"],
     0, "Deficiencies: Ca2+, folate, vitamin A, D, E — in absent jejunum. (Book p28)"),
    (U17, 28, "recall", "Vitamin K deficiency is rare in short bowel syndrome because:",
     ["It is synthesised by bacteria that migrate when the ileocecal valve is absent",
      "It is absorbed in the stomach",
      "It has large body stores",
      "It is given routinely in parenteral nutrition"],
     0, "Vitamin K: rare d/t synthesis (absent ileocecal valve → migration of bacteria). (Book p28)"),
    (U17, 28, "recall", "SIBO in short bowel syndrome is attributed to:",
     ["Loss of the ileocecal valve", "Loss of the pylorus", "Loss of the colon", "Loss of the gallbladder"],
     0, "SIBO: d/t loss of ileocecal valve. (Book p28)"),
    (U17, 28, "recall", "In the diet column, medium chain fatty acids are recommended because:",
     ["Lipolysis is not required for their absorption",
      "They are the most energy dense",
      "They supply essential fatty acids",
      "They stimulate the ileal break"],
     0, "Diet: medium chain fatty acids (lipolysis not required for its absorption). (Book p28)"),
    (U17, 28, "recall", "Complex carbohydrates are useful in short bowel syndrome because they are:",
     ["Absorbed in the colon as short chain fatty acids",
      "Absorbed without digestion in the duodenum",
      "Converted to glucose by bacteria in the stomach",
      "The only source of essential fatty acids"],
     0, "Diet: complex carbohydrates (absorbed in colon as short chain fatty acids). (Book p28)"),
    (U17, 28, "recall", "When the colon is absent, the management column advises:",
     ["Total parenteral nutrition", "High residue diet", "Oral rehydration alone", "Medium chain triglycerides alone"],
     0, "Diet table: colon absent → total parenteral nutrition. (Book p28)"),
    (U17, 28, "recall", "The medical therapy listed for short bowel syndrome is:",
     ["Teduglutide — an oral GLP-2 analogue",
      "Octreotide — a somatostatin analogue",
      "Loperamide",
      "Cholestyramine"],
     0, "Medical: teduglutide (oral GLP-2 analogue). (Book p28)"),

    (U18, 28, "recall", "SIBO is also known as:",
     ["Blind loop syndrome or stagnant bowel syndrome",
      "Short bowel syndrome",
      "Dumping syndrome",
      "Irritable bowel syndrome"],
     0, "SIBO: AKA blind loop syndrome, stagnant bowel syndrome. (Book p28)"),
    (U18, 28, "match",
     "Match the region to its printed normal bacterial content — 1) Proximal small intestine 2) Ileum 3) Colon … A) Anaerobes B) No bacteria C) Enterobacteriaceae",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Physiology: proximal small intestine — no bacteria; ileum — Enterobacteriaceae; colon — anaerobes. (Book p28)"),
    (U18, 28, "recall", "The organisms causing bacterial overgrowth in SIBO are:",
     ["Non-toxigenic anaerobes such as Bacteroides fragilis, Enterobacteriaceae and Pseudomonas",
      "Toxigenic aerobes such as E. coli and Klebsiella",
      "Fungi and mycobacteria",
      "Viruses and spirochaetes"],
     0, "Pathology: non-toxigenic anaerobes (Bacteroides fragilis, Enterobacteriaceae, Pseudomonas). (Book p28)"),
    (U18, 28, "recall", "In SIBO the overgrowth occurs in the:",
     ["Proximal small intestine", "Colon", "Stomach", "Terminal ileum only"],
     0, "Pathology: bacterial overgrowth in the proximal small intestine. (Book p28)"),
    (U18, 28, "recall", "The anatomical defects listed as causes of SIBO are:",
     ["Fistula and ileocecal valve removal",
      "Stricture and diverticulum",
      "Volvulus and adhesions",
      "Hernia and intussusception"],
     0, "Etiology: 1. anatomical defect — fistula, ileocecal valve removal. (Book p28)"),
    (U18, 28, "recall", "Irritable bowel syndrome predisposes to SIBO through:",
     ["A defective migratory motor complex",
      "Excess acid secretion",
      "Bile acid malabsorption",
      "Loss of the ileocecal valve"],
     0, "Functional and motility disorders: irritable bowel syndrome — defective migratory motor complex. (Book p28)"),
    (U18, 28, "recall", "The motility disorders listed under SIBO etiology are:",
     ["IBS, scleroderma, diabetes mellitus and amyloidosis",
      "IBS, achalasia, gastroparesis and Hirschsprung disease",
      "Scleroderma, myasthenia and polymyositis",
      "Diabetes mellitus, hypothyroidism and Addison disease"],
     0, "Functional and motility disorders: irritable bowel syndrome (IBS), scleroderma, diabetes mellitus, amyloidosis. (Book p28)"),

    # ----------------------------------------------------------------- p29
    (U19, 29, "recall", "The immunodeficiency states listed under SIBO etiology are:",
     ["Common variable immune deficiency and IgA deficiency",
      "Bruton agammaglobulinaemia and SCID",
      "HIV and AIDS alone",
      "Neutropenia and asplenia"],
     0, "4. Immunodeficiency: common variable immune deficiency (CVID), IgA deficiency. (Book p29)"),
    (U19, 29, "recall", "The multifactorial cause listed under SIBO etiology is:",
     ["HIV", "Diabetes mellitus", "Scleroderma", "Amyloidosis"],
     0, "5. Multifactorial: HIV. (Book p29)"),
    (U19, 29, "recall", "Luminal bacteria in SIBO harm the host by:",
     ["Competing for host nutrients and consuming B12, proteins and vitamins",
      "Producing a toxigenic diarrheal toxin",
      "Destroying the brush border directly",
      "Blocking bile acid synthesis"],
     0, "Bacteria in lumen → compete for host nutrients → consume B12, proteins, vitamins. (Book p29)"),
    (U19, 29, "recall", "The most common symptom of SIBO is:",
     ["Bloating and belching", "Steatorrhea", "Haematochezia", "Fever"],
     0, "Bloating, belching: m/c symptom. (Book p29)"),
    (U19, 29, "recall", "Bloating and belching in SIBO are attributed to:",
     ["Unabsorbed carbohydrates", "Bile acid malabsorption", "Protein malabsorption", "Fat malabsorption"],
     0, "Bloating, belching: d/t unabsorbed carbohydrates. (Book p29)"),
    (U19, 29, "recall", "The clinical features listed for SIBO are:",
     ["Vitamin B12 deficiency, macrocytic anemia, steatorrhea and unexplained diarrhea",
      "Iron deficiency, microcytic anemia and constipation",
      "Vitamin K deficiency, bleeding and bruising",
      "Vitamin A deficiency and night blindness"],
     0, "Clinical presentation: deficiency of vitamin B12, macrocytic anemia, steatorrhea, unexplained diarrhea. (Book p29)"),
    (U19, 29, "recall", "Occult malabsorption in SIBO means some cases present with:",
     ["Only weight loss", "Only fever", "Only steatorrhea", "Only anemia"],
     0, "Occult malabsorption: some cases present with only weight loss. (Book p29)"),
    (U19, 29, "match",
     "Compare SIBO with tropical sprue as printed — 1) Organisms in the small intestine 2) Vitamin B12 deficiency 3) Folate deficiency … A) Tropical sprue: prominent B) SIBO: non-toxigenic anaerobes / tropical sprue: toxigenic aerobes C) SIBO: prominent",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Organisms in SI — SIBO: non-toxigenic anaerobes, tropical sprue: toxigenic aerobes; vitamin B12 deficiency is prominent in SIBO; folate deficiency is prominent in tropical sprue. (Book p29)"),
    (U19, 29, "recall", "The gold standard investigation for SIBO is:",
     ["Jejunal fluid aspirate", "Lactulose hydrogen breath test", "Urinary indican", "Serum folate"],
     0, "1. Jejunal fluid aspirate: >10^3 CFU/mL (gold standard). (Book p29)"),
    (U19, 29, "numeric", "The diagnostic colony count on jejunal fluid aspirate is:",
     [">10^3 CFU/mL", ">10^5 CFU/mL", ">10^1 CFU/mL", ">10^7 CFU/mL"],
     0, "Jejunal fluid aspirate: >10^3 CFU/mL (gold standard). (Book p29)"),
    (U19, 29, "recall", "The preferred test for SIBO is:",
     ["Lactulose hydrogen breath test, because it is easy to perform",
      "Jejunal fluid aspirate",
      "Urinary indican levels",
      "Serum vitamin B12"],
     0, "2. Lactulose hydrogen breath test: easy to perform (preferred). (Book p29)"),
    (U19, 29, "recall", "Urinary indican levels for SIBO are described as:",
     ["Obsolete", "Gold standard", "Preferred", "The most specific"],
     0, "3. Urinary indican levels: obsolete. (Book p29)"),
    (U19, 29, "recall", "Serum vitamin B12 in SIBO is:",
     ["Decreased", "Increased", "Normal", "Undetectable"],
     0, "4. Serum vitamin B12: decreased. (Book p29)"),
    (U19, 29, "recall", "Serum folate and vitamin K in SIBO are:",
     ["Increased", "Decreased", "Normal", "Undetectable"],
     0, "5. S. folate and vitamin K: increased. (Book p29)"),
    (U19, 29, "recall", "The duration of antibiotic therapy for SIBO is:",
     ["7-10 days", "3-6 months", "A single dose", "14-21 days"],
     0, "Management: antibiotics 7-10 days. (Book p29)"),
    (U19, 29, "recall", "The drug of choice for SIBO is:",
     ["Rifaximin 550 mg BD", "Neomycin 500 mg BD", "Metronidazole 250 mg TID", "Amoxicillin-clavulanic acid 500 mg TID"],
     0, "Tab rifaximin 550 mg BD (DOC). (Book p29)"),
    (U19, 29, "numeric", "The dose of rifaximin used in SIBO is:",
     ["550 mg BD", "550 mg OD", "250 mg TID", "500 mg TID"],
     0, "Tab rifaximin 550 mg BD (DOC). (Book p29)"),
    (U19, 29, "recall", "The combination regimen listed for SIBO is:",
     ["Rifaximin 550 mg plus neomycin 500 mg BD",
      "Rifaximin plus metronidazole",
      "Amoxicillin-clavulanic acid plus neomycin",
      "Tetracycline plus metronidazole"],
     0, "Tab rifaximin 550 mg + tab neomycin 500 mg BD. (Book p29)"),
    (U19, 29, "match",
     "Match the persistence/recurrence regimen to its printed dose — 1) Amoxicillin-clavulanic acid 2) Tetracycline 3) Metronidazole … A) 250 mg QID B) 500 mg TID C) 250 mg TID",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     0, "On persistence/recurrence: amoxicillin-clavulanic acid 500 mg TID, tetracycline 250 mg QID, metronidazole 250 mg TID. (Book p29)"),
    (U19, 29, "recall", "The class of antibiotics the book says to avoid in SIBO is:",
     ["Macrolides", "Nitroimidazoles", "Tetracyclines", "Aminoglycosides"],
     0, "Avoid macrolides. (Book p29)"),
    (U19, 29, "scenario",
     "A patient with prior ileocecal valve resection has macrocytic anemia, steatorrhea and bloating. Serum B12 is low and folate is high. The book's diagnosis is:",
     ["SIBO", "Tropical sprue", "Coeliac disease", "Pernicious anemia"],
     0, "SIBO: organisms use B12 and synthesise folate — low B12, high folate, macrocytic anemia and steatorrhea. (Book p29)"),
]


GUIDES = {
    U1: ("Global Malabsorption: Overview",
         "Defective absorption of carbohydrate, fat and protein from small intestinal mucosal dysfunction.\nFat is the most sensitive, most specific and most energy dense nutrient.\nThree causes: celiac disease, Whipple's disease, tropical sprue."),
    U2: ("Celiac Disease: Features & Iceberg Phenomenon",
         "AKA celiac sprue / gluten sensitive enteropathy / non-tropical sprue.\nIceberg phenomenon: only 50% present classically, missed through physician unawareness.\nHLA DQ2/DQ8 is the most important predisposition; the disease is proximal small intestinal."),
    U3: ("Celiac Disease: Types",
         "Classical: 50% present with symptoms of malabsorption.\nAtypical: symptoms other than malabsorption; silent: asymptomatic, serology positive.\nLatent: asymptomatic, antibodies negative, HLA susceptibility present."),
    U4: ("Celiac Pathophysiology & Disease Progression",
         "HLA DQ2/DQ8 → gluten (wheat, barley, rye, oats) → prolamine (most toxic) → gliadin (chief antigen).\nTissue transglutaminase deamidates gliadin-bound glutamine → activates T cells.\nGluten-free diet: 90% revert (clinically 3 weeks, histologically 6 months); 10% refractory → steroids."),
    U5: ("Celiac Clinical Features",
         "Classical: osmotic diarrhea, distension, foul smelling stool, weight loss; IBS symptoms in 30%.\nAtypical: short stature, fracture/osteopenia, ataxia/neuropathy, iron deficiency anemia not due to blood loss.\nOther: secondary hyperparathyroidism, cerebral calcification, hyposplenism with Howell-Jolly bodies, follicular hyperkeratosis, edema/ascites, cryptogenic cirrhosis."),
    U6: ("Celiac Associations",
         "Definite: dermatitis herpetiformis (most important), Down syndrome, type I DM, IgA nephropathy, IgA deficiency, bird-fancier lung, lymphocytic colitis, cerebral calcification with epilepsy.\nDermatitis herpetiformis: papulovesicular extensor lesions with linear IgA at the dermoepidermal junction.\nProbable: cryptogenic transaminitis, idiopathic short stature, refractory iron deficiency anemia, cerebellar ataxia."),
    U7: ("Celiac Diagnosis: Serology & Biopsy",
         "Anti-TTG IgA: most important for diagnosis and monitoring; specificity 98%.\nAnti-endomysial IgA: indirect immunofluorescence, sensitivity 99%, specificity 73%, subjective and cumbersome.\nAnti-deamidated gliadin peptide IgG for IgA deficiency; anti-gliadin obsolete. Biopsy: mucosal total villous atrophy, crypt hyperplasia, normal thickness, lamina propria lymphocytes, Marsh score."),
    U8: ("Celiac Interpretation, Complications & Treatment",
         "Both positive = celiac; both negative = not celiac (test HLA DQ2/DQ8 if suggestive).\nSerology positive/biopsy negative: repeat biopsy; serology negative/biopsy positive: non-specific (tropical sprue, cow's milk intolerance).\nRefractory disease is premalignant: EATL, small intestinal adenocarcinoma, esophageal squamous cell carcinoma; diet is rice/corn/maize/potato/soybean with gluten restriction."),
    U9: ("Whipple's Disease: Presentation",
         "Chronic multisystem disease of joints, GIT, CNS and CVS; M > F, 50-60 years.\nPan-intestinal, proximal more than distal; Tropheryma whipplei is a gram positive actinobacterium that cannot be cultured because of slow doubling time.\nDiagnosis is by biopsy."),
    U10: ("Whipple's Disease: Clinical Features",
         "Joints first in >80%: large joints, migratory arthralgia > arthritis.\nGIT 2-3 years later: diarrhea (most consistent), weight loss, abdominal pain with mesenteric lymphadenopathy.\nNeuro 40%: rapidly progressive dementia (m/c) and oculomasticatory myorhythmia (m/c specific); CVS: culture negative endocarditis, mitral valve > myocarditis > pericarditis, HACEK group."),
    U11: ("Whipple's Disease: Diagnosis & Treatment",
         "Upper GI endoscopy with biopsy is 100% diagnostic; PCR identifies Tropheryma whipplei.\nPAS positive foamy macrophages in epithelium, lamina propria and submucosa with enlarged villi.\nInduction IV ceftriaxone 2 g for 14 days (best); maintenance co-trimoxazole prevents relapse and penetrates the CNS."),
    U12: ("Tropical Sprue: Pathogenesis",
         "Most common cause of malabsorption in India, Bangladesh and Pakistan.\nInfective diarrhea → toxigenic coliforms (E. coli, Klebsiella) → fermentation products, mainly ethanol.\nStructural damage impairs folic acid absorption → 2-3 weeks → pan-intestinal involvement with defective B12, bile acid and Mg2+ absorption."),
    U13: ("Tropical Sprue: Features, Investigations & Treatment",
         "Chronic watery voluminous small bowel diarrhea, steatorrhea, weight loss, prominent folic acid deficiency, hyperpigmentation from B12 deficiency.\nBiopsy resembles celiac disease but serology is negative; stool examined for ova, cyst and trophozoite to rule out giardiasis.\nFolic acid 5 mg daily plus tetracycline 250 mg QID for 3-6 months; relapse in 20%."),
    U14: ("Bile Acid Diarrhea & Fatty Acid Diarrhea",
         "Bile acid diarrhea (cholorrhea) is seen in tropical sprue from defective FGF-19; limited ileal disease leaves compensatory excess hepatic bile acid removing Na+, Cl− and K+.\nFatty acid diarrhea needs severe ileal disease: no compensatory release → malabsorption → fatty acid in colon → steatorrhea >20 g.\nCholestyramine helps bile acid diarrhea; a low-fat diet helps fatty acid diarrhea."),
    U15: ("Short Bowel Syndrome: Definition & Etiology",
         "Short bowel syndrome: < 200 cm; very severe: < 100 cm.\nAdult: mesenteric vascular disease (ischemia with resection) more than Crohn's disease.\nChild: necrotising enterocolitis."),
    U16: ("Short Bowel Syndrome: Clinical Presentation",
         "Hyperoxaluria: unabsorbed LCFA bind calcium, free oxalate is absorbed and forms oxalate stones.\nAbsent ileum → cholesterol gallstones from supersaturation.\nD-lactic acidosis from gram positive anaerobes (Lactobacillus, Bifidobacterium) causing CNS features; hypergastrinemia; hypomagnesemia; defective ileal break with rapid gastric emptying."),
    U17: ("Short Bowel Syndrome: Deficiencies & Management",
         "Iron: absent duodenum > jejunum; Ca2+, folate, vitamins A, D, E: absent jejunum; vitamin K rarely because bacteria migrate when the ileocecal valve is lost.\nSIBO from loss of the ileocecal valve.\nDiet: medium chain fatty acids and complex carbohydrates; total parenteral nutrition when the colon is absent; teduglutide is an oral GLP-2 analogue."),
    U18: ("SIBO: Physiology, Pathology & Etiology",
         "AKA blind loop syndrome / stagnant bowel syndrome.\nProximal small intestine normally has no bacteria; ileum has Enterobacteriaceae; colon has anaerobes.\nOvergrowth of non-toxigenic anaerobes proximally; causes are anatomical defects, motility disorders (IBS, scleroderma, diabetes, amyloidosis), immunodeficiency and HIV."),
    U19: ("SIBO: Presentation, Investigations & Management",
         "Bacteria compete for nutrients and consume B12: bloating and belching are most common; B12 deficiency, macrocytic anemia, steatorrhea, unexplained diarrhea.\nJejunal aspirate >10^3 CFU/mL is gold standard; lactulose H2 breath test is preferred; indican is obsolete; B12 low, folate and vitamin K high.\nRifaximin 550 mg BD for 7-10 days; avoid macrolides."),
}


def main():
    questions = []
    for index, (sec, page, fmt, stem, opts, ans, exp) in enumerate(RAW, 1):
        questions.append({
            "id": f"MED-C{CHAPTER}-{index:02d}",
            "sec": sec,
            "page": page,
            "fmt": fmt,
            "q": stem,
            "opts": opts,
            "ans": ans,
            "exp": exp,
        })
    ordered = []
    for sec, *_ in RAW:
        if sec not in ordered:
            ordered.append(sec)
    units = []
    for n, sec in enumerate(ordered, 1):
        title_text, guide = GUIDES[sec]
        units.append({
            "id": f"MED-U{CHAPTER}-{n}",
            "ch": CHAPTER,
            "n": n,
            "title": title_text,
            "sec": sec,
            "guide": guide,
            "qs": [q["id"] for q in questions if q["sec"] == sec],
        })
    out = DATA / f"ch{CHAPTER:02d}.json"
    out.write_text(json.dumps({
        "chapter": CHAPTER, "title": TITLE, "pageRange": PAGES,
        "questions": questions, "units": units,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out.name}: {len(questions)} questions / {len(units)} units")


if __name__ == "__main__":
    main()
