#!/usr/bin/env python3
"""Generate Chapter 2 Physiology of GIT Absorption and Selective Malabsorption (Book p6-13).

Source: uploads/01.pdf PDF18-25 = Book p6-13, read sheet by sheet in printed order.
Every question maps to one inventoried printed point; explanations cite (Book pN).
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
AUDIT = ROOT / "audit"
DATA.mkdir(exist_ok=True)
AUDIT.mkdir(exist_ok=True)

CHAPTER = 2
TITLE = "Physiology of GIT Absorption and Selective Malabsorption"
PAGES = "6-13"

S1 = "Basics of Absorption & Stages"
S2 = "Anatomy of the Small Intestine"
S3 = "Histology: Mucosa"
S4 = "Small Intestine Layers & Peyer's Patches"
S5 = "Fat Absorption: Luminal Phase"
S6 = "Bile Acid Physiology"
S7 = "Defects in Luminal & Mucosal Phase"
S8 = "Post-Mucosal Phase & Types of Fatty Acids"
S9 = "Carbohydrate Absorption Mechanism"
S10 = "Defects in Carbohydrate Absorption"
S11 = "Protein Absorption & Selective Defects"
S12 = "Lactose Intolerance: Physiology to Pathogenesis"
S13 = "Lactose Intolerance: Presentation & Investigations"
S14 = "Abetalipoproteinemia"
S15 = "Intestinal Lymphangiectasia"

# (section, page, format, stem, options, answer index, explanation)
RAW = [
    # ------------------------------------------------------------------ p6
    (S1, 6, "recall", "The book lists the stages of absorption, in order, as:",
     ["1. Luminal, 2. Mucosal, 3. Post mucosal",
      "1. Mucosal, 2. Luminal, 3. Post mucosal",
      "1. Luminal, 2. Post mucosal, 3. Mucosal",
      "1. Gastric, 2. Luminal, 3. Mucosal"],
     0, "Stages of absorption: 1. Luminal, 2. Mucosal, 3. Post mucosal. (Book p6)"),
    (S1, 6, "match",
     "Match the numbered stage of absorption to its descriptor — 1) Stage 1 2) Stage 2 3) Stage 3 … A) Mucosal B) Post mucosal C) Luminal",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     0, "Stage 1 = Luminal (enzymes mediated), Stage 2 = Mucosal (small intestinal enterocyte), Stage 3 = Post mucosal (into blood). (Book p6)"),
    (S1, 6, "recall", "The luminal stage of absorption is described as:",
     ["Enzymes mediated", "Carrier mediated only", "Lymphatic transport", "Passive paracellular diffusion"],
     0, "1. Luminal: Enzymes mediated. (Book p6)"),
    (S1, 6, "fillup", "In the mucosal stage the villi ____ contains enzymes.",
     ["brush border", "crypt base", "lamina propria", "serosa"],
     0, "Mucosal: small intestinal mucosal — enterocyte; villi brush border contains enzymes. (Book p6)"),
    (S1, 6, "recall", "The cell type named for the mucosal stage of absorption is the:",
     ["Enterocyte", "Goblet cell", "Paneth cell", "Parietal cell"],
     0, "2. Mucosal: small intestinal mucosal — Enterocyte, with brush border enzymes. (Book p6)"),
    (S1, 6, "truefalse",
     "TRUE or FALSE — the book defines the post mucosal stage as movement from the mucosal epithelial cell into blood.",
     ["True — mucosal epithelial cell → into blood",
      "False — post mucosal is transport into lymph",
      "False — post mucosal is the luminal enzyme step",
      "True — but only for short chain fatty acids"],
     0, "3. Post mucosal: mucosal epithelial cell → into blood. (Book p6)"),
    (S1, 6, "oddoneout", "Pick the ODD ONE OUT — one of these is not a printed stage of absorption:",
     ["Post absorptive", "Luminal", "Mucosal", "Post mucosal"],
     0, "The three printed stages are Luminal, Mucosal and Post mucosal; 'post absorptive' is not listed. (Book p6)"),
    (S1, 6, "scenario",
     "A toxin selectively destroys the brush-border enzymes of the small intestinal enterocyte. Which stage of absorption is blocked?",
     ["Mucosal", "Luminal", "Post mucosal", "Colonic salvage"],
     0, "Brush border enzymes belong to the enterocyte — i.e. the mucosal stage. (Book p6)"),
    (S1, 6, "numeric", "How many stages of absorption does the book list?",
     ["Three", "Two", "Four", "Five"],
     0, "Three stages: Luminal, Mucosal, Post mucosal. (Book p6)"),

    (S2, 6, "recall", "The proximal two-thirds of the small intestine is described as the site of:",
     ["Maximum absorption (Jejunum > Duodenum)",
      "Bile acid and vitamin B12 absorption",
      "Water absorption only",
      "Vitamin K synthesis"],
     0, "Proximal (2/3): maximum absorption (Jejunum > Duodenum). (Book p6)"),
    (S2, 6, "fillup", "Proximal (2/3) of the small intestine shows maximum absorption (____ > Duodenum).",
     ["Jejunum", "Ileum", "Caecum", "Pylorus"],
     0, "Proximal (2/3): maximum absorption (Jejunum > Duodenum). (Book p6)"),
    (S2, 6, "recall", "The distal one-third of the small intestine (ileum) absorbs:",
     ["Bile acid, vitamin B12 and Mg2+",
      "Iron and folate only",
      "Glucose and galactose",
      "Vitamin K and biotin"],
     0, "Distal (1/3): absorption of bile acid, Vit B12, Mg2+ (ileum). (Book p6)"),
    (S2, 6, "oddoneout", "All of the following are absorbed in the distal one-third (ileum) EXCEPT:",
     ["Iron", "Bile acid", "Vitamin B12", "Magnesium"],
     0, "Distal (1/3) absorbs bile acid, Vit B12 and Mg2+; iron is absorbed proximally (duodenum > jejunum). (Book p6)"),
    (S2, 6, "match",
     "Match the small intestinal segment to its printed role — 1) Proximal 2/3 2) Distal 1/3 … A) Bile acid, Vit B12, Mg2+ (ileum) B) Maximum absorption (jejunum > duodenum)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Proximal 2/3 = maximum absorption (jejunum > duodenum); distal 1/3 = bile acid, Vit B12, Mg2+ (ileum). (Book p6)"),
    (S2, 6, "numeric", "What fraction of the small intestine is described as the proximal segment of maximum absorption?",
     ["2/3", "1/3", "1/2", "3/4"],
     0, "Proximal (2/3): maximum absorption (Jejunum > Duodenum). (Book p6)"),

    (S3, 6, "recall", "The specific feature of the small intestinal mucosa named by the book is:",
     ["Villi", "Haustrations", "Plicae semilunares", "Crypt abscesses"],
     0, "Enterocyte: villi (specific feature). (Book p6)"),
    (S3, 6, "fillup", "Villi are surrounded by crypts of ____.",
     ["Lieberkühn", "Luschka", "Brunner", "Kerckring"],
     0, "Villi (specific feature) are surrounded by crypts of Lieberkühn. (Book p6)"),
    (S3, 6, "recall", "The villi contain a:",
     ["Brush border", "Muscular sleeve", "Lymph node", "Serous acinus"],
     0, "Enterocyte villi contain the brush border. (Book p6)"),
    (S3, 6, "recall", "Paneth cells are located:",
     ["At the base of the crypts", "At the villus tip", "In the lamina propria", "In the muscularis mucosa"],
     0, "Crypts: Paneth cells (at base). (Book p6)"),
    (S3, 6, "recall", "Paneth cells produce immunological substances, namely:",
     ["Alpha defensins, lysozymes, phospholipase A2",
      "Mucus and trefoil peptides",
      "Gastrin and cholecystokinin",
      "Secretin and GIP"],
     0, "Paneth cells (at base) produce immunological substances: alpha defensins, lysozymes, phospholipase A2. (Book p6)"),
    (S3, 6, "oddoneout", "All of the following are listed Paneth-cell products EXCEPT:",
     ["Mucus", "Alpha defensins", "Lysozymes", "Phospholipase A2"],
     0, "Paneth cells produce alpha defensins, lysozymes and phospholipase A2; mucus comes from goblet cells. (Book p6)"),
    (S3, 6, "recall", "Besides Paneth cells, the crypts contain:",
     ["Enteroendocrine cells and goblet cells",
      "Chief cells and parietal cells",
      "Kupffer cells and Ito cells",
      "Podocytes and mesangial cells"],
     0, "Crypts: Paneth cells (at base), enteroendocrine cells, goblet cells. (Book p6)"),
    (S3, 6, "numeric", "Small intestinal epithelium shows continuous renewal every:",
     ["48-72 hrs", "12-24 hrs", "7-10 days", "21 days"],
     0, "Continuous renewal: every 48-72 hrs. (Book p6)"),
    (S3, 6, "recall", "The lamina propria of the small intestinal mucosa contains:",
     ["Glands and blood vessels", "Paneth cells only", "Smooth muscle bundles only", "Serous glands only"],
     0, "b. Lamina propria: glands, blood vessels. (Book p6)"),
    (S3, 6, "recall", "The muscularis mucosa of the small intestine is described as having:",
     ["Tight attachment", "Loose areolar plane", "No attachment", "A serosal covering"],
     0, "c. Muscularis mucosa: tight attachment. (Book p6)"),
    (S3, 6, "match",
     "Match the mucosal compartment to its printed content — 1) Lamina propria 2) Muscularis mucosa 3) Crypt … A) Paneth cells at base B) Glands, blood vessels C) Tight attachment",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Lamina propria = glands, blood vessels; muscularis mucosa = tight attachment; crypts contain Paneth cells at the base. (Book p6)"),
    (S3, 6, "recall", "Plica circularis is defined in the note as:",
     ["Visible mucosal folds on the luminal surface of the small intestine",
      "The pacemaker cell network of the gut",
      "Lymphoid aggregates of the ileum",
      "The smooth muscle coat of the colon"],
     0, "Note: plica circularis — visible mucosal folds on the luminal surface of the small intestine. (Book p6)"),
    (S3, 6, "recall", "Interstitial cells of Cajal in the small intestine are:",
     ["Pacemaker cells", "Mucus secreting cells", "Paneth-like immune cells", "Enteroendocrine cells"],
     0, "Interstitial cells of Cajal: pacemaker cells of the small intestine — basal electrical rhythm. (Book p6)"),
    (S3, 6, "fillup", "Interstitial cells of Cajal generate the ____ of the small intestine.",
     ["basal electrical rhythm", "migrating motor complex", "slow wave of the stomach", "rectoanal inhibitory reflex"],
     0, "Interstitial cells of Cajal: pacemaker cells of the small intestine → basal electrical rhythm. (Book p6)"),

    # ------------------------------------------------------------------ p7
    (S4, 7, "recall", "Peyer's patches are located in the:",
     ["Submucosa of the ileum", "Mucosa of the duodenum", "Muscularis propria of the jejunum", "Serosa of the colon"],
     0, "2. Submucosa: Peyer's patches (in ileum). (Book p7)"),
    (S4, 7, "recall", "Peyer's patches are described as:",
     ["Macroscopic lymphoid aggregates", "Microscopic lymphoid follicles", "Collections of Paneth cells", "Ectopic gastric mucosa"],
     0, "Peyer's patches (in ileum): macroscopic lymphoid aggregates. (Book p7)"),
    (S4, 7, "scenario", "At ileocolonoscopy a surgeon notes hypertrophied Peyer's patches. The book links this hypertrophy to:",
     ["Typhoid", "Tuberculosis", "Amoebiasis", "Coeliac disease"],
     0, "Peyer's patches (in ileum): in typhoid — hypertrophy. (Book p7)"),
    (S4, 7, "match",
     "Order the small intestinal layers as printed (innermost → outermost) — 1) Mucosa 2) Submucosa 3) Muscularis propria 4) Serosa … A) Serosa B) Mucosa C) Submucosa D) Muscularis propria",
     ["1-B, 2-C, 3-D, 4-A", "1-A, 2-B, 3-C, 4-D", "1-B, 2-D, 3-C, 4-A", "1-C, 2-B, 3-D, 4-A"],
     0, "Histology layers: 1. mucosa, 2. submucosa, 3. muscularis propria, 4. serosa. (Book p7)"),
    (S4, 7, "oddoneout", "Pick the ODD ONE OUT — one is not a printed layer of the small intestine:",
     ["Adventitia", "Mucosa", "Muscularis propria", "Serosa"],
     0, "The printed layers are mucosa, submucosa, muscularis propria and serosa; adventitia is not listed. (Book p7)"),

    (S5, 7, "recall", "The luminal phase of fat absorption requires:",
     ["Bile acids and pancreatic lipase",
      "Gastric lipase alone",
      "Colonic bacterial enzymes",
      "Enterokinase alone"],
     0, "Luminal phase mechanism: bile acids + pancreatic lipase act on triglyceride. (Book p7)"),
    (S5, 7, "fillup", "Pancreatic lipase acts on triglyceride (TGA) by the process of ____.",
     ["Lipolysis", "Esterification", "Deconjugation", "Deamidation"],
     0, "TGA → lipolysis (by pancreatic lipase) → fatty acids + glycerol. (Book p7)"),
    (S5, 7, "recall", "Lipolysis of triglyceride in the lumen yields:",
     ["Fatty acids + glycerol", "Chylomicrons + bile salts", "Monoglycerides + cholesterol", "Amino acids + peptides"],
     0, "Lipolysis of TGA gives fatty acids + glycerol. (Book p7)"),
    (S5, 7, "match",
     "Order the luminal fat steps as printed — 1) TGA 2) Lipolysis 3) Fatty acids + glycerol … A) Fatty acids + glycerol B) TGA C) Lipolysis",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     0, "Bile acids + pancreatic lipase act on TGA → lipolysis → fatty acids + glycerol. (Book p7)"),
    (S5, 7, "scenario",
     "A patient with chronic pancreatitis has steatorrhea. The book attributes this to loss of:",
     ["Pancreatic lipase with failed lipolysis",
      "Bile acid synthesis",
      "Chylomicron assembly",
      "Lactase activity"],
     0, "Defects in luminal absorption: 1. chronic pancreatitis → affects pancreatic lipase → lipolysis affected. (Book p7)"),
    (S5, 7, "truefalse",
     "TRUE or FALSE — the book shows micelles entering enterocytes by passive diffusion in the luminal phase.",
     ["True — passive diffusion of micelles into enterocytes",
      "False — uptake is active via SGLT1",
      "False — micelles are excluded from enterocytes",
      "True — but only for short chain fatty acids"],
     0, "Micelle → passive diffusion into enterocytes. (Book p7)"),

    (S6, 7, "numeric", "The bile acid body pool is:",
     ["4 g", "40 g", "0.4 g", "400 g"],
     0, "Bile acid physiology: body pool 4 g (maintained by enterohepatic circulation). (Book p7)"),
    (S6, 7, "fillup", "The bile acid body pool is maintained by the ____ circulation.",
     ["enterohepatic", "enteroenteric", "portosystemic", "lymphatic"],
     0, "Body pool: 4 g (maintained by enterohepatic circulation). (Book p7)"),
    (S6, 7, "recall", "The rate-limiting enzyme of bile acid synthesis is:",
     ["7α-hydroxylase", "HMG-CoA reductase", "Cholesterol esterase", "Lecithin-cholesterol acyltransferase"],
     0, "Synthesis: 7α-hydroxylase is the rate limiting step. (Book p7)"),
    (S6, 7, "recall", "The primary bile acids formed by synthesis are:",
     ["Cholic acid and chenodeoxycholic acid",
      "Deoxycholic acid and lithocholic acid",
      "Ursodeoxycholic acid and lithocholic acid",
      "Taurocholic acid and glycocholic acid"],
     0, "Synthesis produces cholic acid and chenodeoxycholic acid. (Book p7)"),
    (S6, 7, "recall", "Bile acids are conjugated with:",
     ["Glycine/taurine", "Sulphate/glucuronide", "Cholesterol/phospholipid", "Fatty acids/glycerol"],
     0, "Conjugation with glycine/taurine. (Book p7)"),
    (S6, 7, "recall", "After conjugation, bile acids are termed:",
     ["Bile salts", "Bile pigments", "Micelles", "Chylomicrons"],
     0, "Conjugation (glycine/taurine) → bile salts. (Book p7)"),
    (S6, 7, "recall", "Bacterial deconjugation in the colon produces:",
     ["Deoxycholic acid and lithocholic acid",
      "Cholic acid and chenodeoxycholic acid",
      "Glycocholic acid and taurocholic acid",
      "Ursodeoxycholic acid and cholic acid"],
     0, "Colon: bacterial deconjugation → deoxycholic acid, lithocholic acid. (Book p7)"),
    (S6, 7, "match",
     "Match the enterohepatic step to its printed product — 1) Synthesis (rate limiting) 2) Conjugation 3) Colonic bacterial deconjugation … A) Glycine/taurine → bile salts B) 7α-hydroxylase → cholic & chenodeoxycholic acid C) Deoxycholic & lithocholic acid",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     0, "Synthesis (7α-hydroxylase, rate limiting) → cholic/chenodeoxycholic acid; conjugation with glycine/taurine → bile salts; colonic bacterial deconjugation → deoxycholic and lithocholic acid. (Book p7)"),
    (S6, 7, "recall", "Reabsorbed bile acids return to the liver through the:",
     ["Portal circulation", "Thoracic duct", "Inferior vena cava", "Lymphatic lacteals"],
     0, "Bile salts are reabsorbed and returned via the portal circulation to the liver. (Book p7)"),
    (S6, 7, "scenario",
     "After ileal resection a patient develops bile-acid diarrhea. The enterohepatic step lost is:",
     ["Reabsorption", "Synthesis", "Conjugation", "Hepatic secretion"],
     0, "Ileal disease removes the reabsorption limb of the enterohepatic circulation. (Book p7)"),
    # ------------------------------------------------------------------ p8
    (S7, 8, "recall", "Chronic pancreatitis causes a luminal defect by affecting:",
     ["Pancreatic lipase, so lipolysis is affected",
      "Bile acid conjugation",
      "Chylomicron esterification",
      "Disaccharidase activity"],
     0, "1. Chronic pancreatitis → affects pancreatic lipase → lipolysis affected. (Book p8)"),
    (S7, 8, "recall", "The book's 'bile acid defect' may be a defect in:",
     ["Secretion, synthesis or reabsorption",
      "Esterification only",
      "Micelle diffusion only",
      "Lymphatic transport only"],
     0, "2. Bile acid defect: defect in secretion / synthesis / reabsorption. (Book p8)"),
    (S7, 8, "match",
     "Match the bile acid defect to the printed cause — 1) Destruction of bile ducts 2) Ileal dysfunction 3) Early deconjugation in the small intestine … A) TB/Crohn's B) Cirrhosis, primary biliary cholangitis, primary sclerosing cholangitis C) SIBO",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     0, "Secretion/synthesis defects: cirrhosis, primary biliary cholangitis, primary sclerosing cholangitis (destruction of bile ducts); reabsorption defects: TB/Crohn's (ileal dysfunction) and SIBO (early deconjugation). (Book p8)"),
    (S7, 8, "recall", "Early deconjugation of bile acids in the small intestine is listed under:",
     ["Small intestinal bacterial overgrowth (SIBO)",
      "Chronic pancreatitis",
      "Coeliac disease",
      "Tropical sprue"],
     0, "Defect in reabsorption: small intestinal bacterial overgrowth (SIBO) — early deconjugation in the small intestine. (Book p8)"),
    (S7, 8, "recall", "The mucosal phase of absorption is impaired in:",
     ["Coeliac disease, Whipple disease and tropical sprue",
      "Chronic pancreatitis and SIBO",
      "Abetalipoproteinaemia and lymphangiectasia",
      "Cystinuria and Hartnup disease"],
     0, "Mucosal phase — aetiology: coeliac disease, Whipple disease, tropical sprue. (Book p8)"),
    (S7, 8, "oddoneout", "Pick the ODD ONE OUT — one of these is not a mucosal phase aetiology in the book:",
     ["Chronic pancreatitis", "Coeliac disease", "Whipple disease", "Tropical sprue"],
     0, "Mucosal phase: coeliac disease, Whipple disease, tropical sprue. Chronic pancreatitis is a luminal defect. (Book p8)"),
    (S7, 8, "scenario",
     "A patient with a duodenal biopsy showing villous atrophy has a defect the book places in which phase?",
     ["Mucosal", "Luminal", "Post mucosal", "Colonic"],
     0, "Coeliac disease is listed under the mucosal phase of absorption. (Book p8)"),
    (S7, 8, "recall", "Tuberculosis and Crohn's disease produce a bile acid defect by causing:",
     ["Ileal dysfunction", "Bile duct destruction", "Early deconjugation", "Pancreatic lipase failure"],
     0, "Defect in reabsorption: TB/Crohn's — ileal dysfunction. (Book p8)"),

    (S8, 8, "recall", "In the post-mucosal phase, long chain fatty acids and glycerol undergo:",
     ["Esterification", "Lipolysis", "Deconjugation", "Deamination"],
     0, "Post mucosal: long chain fatty acids + glycerol → esterification → chylomicrons. (Book p8)"),
    (S8, 8, "recall", "Esterification of long chain fatty acids with glycerol forms:",
     ["Chylomicrons", "Micelles", "Bile salts", "VLDL alone"],
     0, "LCFA + glycerol → esterification → chylomicrons. (Book p8)"),
    (S8, 8, "recall", "Chylomicrons leave the enterocyte by transport via:",
     ["Intestinal lymphatics", "Portal venules", "Bile canaliculi", "Submucosal veins"],
     0, "Chylomicrons → transport via intestinal lymphatics. (Book p8)"),
    (S8, 8, "match",
     "Order the post-mucosal steps — 1) LCFA + glycerol 2) Esterification 3) Chylomicrons 4) Transport via intestinal lymphatics … A) Chylomicrons B) LCFA + glycerol C) Intestinal lymphatics D) Esterification",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "LCFA + glycerol → esterification → chylomicrons → transport via intestinal lymphatics. (Book p8)"),
    (S8, 8, "recall", "The two post-mucosal absorption disorders listed are:",
     ["Abetalipoproteinaemia and intestinal lymphangiectasia",
      "Coeliac disease and tropical sprue",
      "Chronic pancreatitis and SIBO",
      "Cystinuria and Hartnup disease"],
     0, "Post mucosal: 1. abetalipoproteinaemia, 2. intestinal lymphangiectasia. (Book p8)"),
    (S8, 8, "numeric", "Medium chain fatty acids have a carbon chain length of:",
     ["8-12", "<8", ">12", ">20"],
     0, "Types of fatty acids — carbon chain length: long chain >12, medium chain 8-12, short chain <8. (Book p8)"),
    (S8, 8, "numeric", "Short chain fatty acids have a carbon chain length of:",
     ["<8", "8-12", ">12", "12-16"],
     0, "Short chain fatty acids: carbon chain length <8. (Book p8)"),
    (S8, 8, "numeric", "Long chain fatty acids have a carbon chain length of:",
     [">12", "<8", "8-12", "exactly 10"],
     0, "Long chain fatty acids: carbon chain length >12. (Book p8)"),
    (S8, 8, "recall", "The primary absorption site of short chain fatty acids is the:",
     ["Colon", "Duodenum", "Jejunum", "Ileum"],
     0, "Short chain fatty acids: primary absorption site — colon. (Book p8)"),
    (S8, 8, "recall", "Short chain fatty acids arise from:",
     ["Bacterial degradation of unabsorbed carbohydrates in the colon",
      "Large quantities of dietary triglycerides",
      "Coconut oil in the diet",
      "Hepatic synthesis from acetyl-CoA"],
     0, "Short chain fatty acids: origin — bacterial degradation of unabsorbed carbohydrates in the colon. (Book p8)"),
    (S8, 8, "recall", "Medium chain fatty acids are present in small quantity in the diet as:",
     ["Coconut oil", "Butter fat", "Lard", "Fish oil"],
     0, "Medium chain: small quantity in diet (coconut oil). (Book p8)"),
    (S8, 8, "recall", "Long chain fatty acids are present in the diet in large quantity as:",
     ["Triglycerides", "Free glycerol", "Cholesterol esters", "Phospholipids"],
     0, "Long chain: large quantity in diet as triglycerides. (Book p8)"),
    (S8, 8, "truefalse",
     "TRUE or FALSE — medium chain fatty acids require pancreatic lipolysis for absorption.",
     ["False — lipolysis not required",
      "True — pancreatic lipase is essential",
      "True — but only in children",
      "False — they require bile acid conjugation instead"],
     0, "Require pancreatic lipolysis: long chain — yes; medium chain — no; short chain — no. (Book p8)"),
    (S8, 8, "truefalse",
     "TRUE or FALSE — short chain fatty acids require micelle formation for absorption.",
     ["False — not required",
      "True — micelles are essential",
      "True — but only above 8 carbons",
      "False — they require chylomicrons instead"],
     0, "Require micelle formation: long chain — yes; medium chain — no; short chain — no. (Book p8)"),
    (S8, 8, "recall", "Which fatty acid type is present in stool in substantial amount?",
     ["Short chain", "Long chain", "Medium chain", "None of them"],
     0, "Present in stool: long chain — minimal, medium chain — no, short chain — substantial. (Book p8)"),
    (S8, 8, "oddoneout", "Pick the ODD ONE OUT — only one fatty acid class requires BOTH pancreatic lipolysis and micelle formation:",
     ["Long chain", "Medium chain", "Short chain", "Both medium and short chain"],
     0, "Only long chain fatty acids require pancreatic lipolysis and micelle formation; medium and short chain require neither. (Book p8)"),
    # ------------------------------------------------------------------ p9
    (S9, 9, "recall", "Disaccharides are split into monosaccharides by:",
     ["Disaccharidases of the small intestinal brush border epithelium",
      "Pancreatic amylase in the lumen",
      "Colonic bacterial glycosidases",
      "Salivary amylase in the mouth"],
     0, "Mechanism of carbohydrate absorption: disaccharides → small intestinal brush border epithelium (disaccharidases) → monosaccharides. (Book p9)"),
    (S9, 9, "recall", "The disaccharidases listed in the book are:",
     ["Lactase, maltase, sucrase, trehalase",
      "Amylase, lipase, trypsin, elastase",
      "Enterokinase, pepsin, rennin, gelatinase",
      "Galactokinase, fructokinase, glucokinase, hexokinase"],
     0, "Disaccharidases: lactase, maltase, sucrase, trehalase. (Book p9)"),
    (S9, 9, "fillup", "Lactose is split by ____ into glucose + galactose.",
     ["Lactase", "Sucrase", "Maltase", "Trehalase"],
     0, "Lactose —(lactase)→ glucose + galactose. (Book p9)"),
    (S9, 9, "fillup", "Sucrose is split by sucrase into glucose + ____.",
     ["Fructose", "Galactose", "Maltose", "Trehalose"],
     0, "Sucrose —(sucrase)→ glucose + fructose. (Book p9)"),
    (S9, 9, "match",
     "Match the disaccharide to its printed monosaccharide pair — 1) Lactose 2) Sucrose … A) Glucose + fructose B) Glucose + galactose",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Lactose → glucose + galactose (lactase); sucrose → glucose + fructose (sucrase). (Book p9)"),
    (S9, 9, "recall", "In the gut, glucose and galactose are absorbed through:",
     ["Na+ glucose cotransporter 1 (SGLT1)",
      "GLUT5",
      "GLUT2",
      "GLUT4"],
     0, "Receptors for absorption in the gut: SGLT1 (sodium glucose cotransporter 1) carries glucose and galactose. (Book p9)"),
    (S9, 9, "recall", "Fructose is absorbed in the gut through:",
     ["GLUT5", "SGLT1", "GLUT2", "GLUT1"],
     0, "In the gut: fructose uses the facilitated transporter GLUT5. (Book p9)"),
    (S9, 9, "truefalse",
     "TRUE or FALSE — the book labels SGLT1-mediated uptake of galactose and glucose as active transport.",
     ["True — active transport via SGLT1",
      "False — SGLT1 is facilitated diffusion",
      "False — galactose uses GLUT5",
      "True — but only for fructose"],
     0, "In the gut: SGLT1 — active transport of galactose and glucose. (Book p9)"),
    (S9, 9, "fillup", "In the liver, galactose is phosphorylated by ____ to galactose-1-phosphate.",
     ["Galactokinase", "Fructokinase", "Glucokinase", "Hexokinase"],
     0, "In the liver: galactose + ATP —(galactokinase)→ galactose-1-phosphate + ADP. (Book p9)"),
    (S9, 9, "fillup", "In the liver, fructose + ATP is converted by ____ into fructose-1-phosphate + ADP.",
     ["Fructose-1-phosphate", "Glucose-6-phosphate", "Galactose-1-phosphate", "Fructose-6-phosphate"],
     0, "In the liver: fructose + ATP —(fructokinase)→ fructose-1-phosphate + ADP. (Book p9)"),
    (S9, 9, "fillup", "In the liver, glucose + ATP is phosphorylated by ____ to glucose-6-phosphate + ADP.",
     ["Glucose-6-phosphate", "Glucose-1-phosphate", "Fructose-6-phosphate", "Galactose-1-phosphate"],
     0, "In the liver: glucose + ATP —(glucokinase)→ glucose-6-phosphate + ADP. (Book p9)"),
    (S9, 9, "recall", "In the liver, monosaccharides enter the hepatocyte through:",
     ["GLUT2", "SGLT1", "GLUT5", "GLUT4"],
     0, "In the liver: glucose transporter (GLUT2) brings monosaccharides into the hepatocyte. (Book p9)"),
    (S9, 9, "scenario",
     "An infant has severe diarrhea from birth with glucose and galactose malabsorption but normal fructose handling. The book names this:",
     ["Familial glucose-galactose malabsorption syndrome (SGLT-1 defect)",
      "Lactase deficiency",
      "Cystinuria",
      "Abetalipoproteinaemia"],
     0, "Note: SGLT-1 defect → familial glucose-galactose malabsorption syndrome. (Book p9)"),
    (S9, 9, "oddoneout", "Pick the ODD ONE OUT — one is not a brush-border disaccharidase listed in the book:",
     ["Galactokinase", "Lactase", "Maltase", "Trehalase"],
     0, "Disaccharidases: lactase, maltase, sucrase, trehalase. Galactokinase is a liver enzyme. (Book p9)"),

    (S10, 9, "recall", "Congenital defects of carbohydrate absorption are described as:",
     ["Autosomal recessive", "Autosomal dominant", "X-linked recessive", "Mitochondrial"],
     0, "Defects in carbohydrate absorption — congenital: autosomal recessive. (Book p9)"),
    (S10, 9, "match",
     "Match the pattern of carbohydrate malabsorption to the printed example — 1) Selective 2) Global … A) Small intestinal mucosal defect (coeliac, Whipple's, tropical sprue) B) Lactase deficiency (primary/secondary)",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Selective = lactase deficiency (primary/secondary); global = small intestinal mucosal defect (coeliac disease, Whipple's disease, tropical sprue). (Book p9)"),
    (S10, 9, "oddoneout", "All of the following cause global carbohydrate malabsorption EXCEPT:",
     ["Lactase deficiency", "Coeliac disease", "Whipple's disease", "Tropical sprue"],
     0, "Global (small intestinal mucosal defect): coeliac disease, Whipple's disease, tropical sprue. Lactase deficiency is selective. (Book p9)"),
    (S10, 10, "recall", "The most common (m/c) acquired lactase deficiency is:",
     ["Primary — genetic defect (allele persistence)",
      "Secondary — post infective",
      "Secondary — due to coeliac disease",
      "Congenital — absent enzyme from birth"],
     0, "Acquired: ↓ enzyme activity — primary (m/c): genetic defect (allele persistence). (Book p10)"),
    (S10, 10, "recall", "Secondary lactase deficiency is listed with:",
     ["Infections and irritable bowel syndrome",
      "Coeliac disease and tropical sprue",
      "Chronic pancreatitis",
      "Cystinuria"],
     0, "Lactase deficiency, secondary: infections, irritable bowel syndrome (IBS). (Book p10)"),

    # ------------------------------------------------------------------ p10
    (S11, 10, "fillup", "Trypsinogen is converted to ____, which activates chymotrypsin and elastase.",
     ["Trypsin", "Chymotrypsinogen", "Enterokinase", "Proelastase"],
     0, "Mechanism of protein absorption: trypsinogen → trypsin → activates chymotrypsin and elastase. (Book p10)"),
    (S11, 10, "recall", "Trypsin activates:",
     ["Chymotrypsin and elastase", "Pepsinogen and gastricsin", "Enterokinase and enteropeptidase", "Amylase and lipase"],
     0, "Trypsinogen → trypsin → activate chymotrypsin and elastase. (Book p10)"),
    (S11, 10, "recall", "Enterokinase deficiency is listed as a cause of:",
     ["Selective protein malabsorption",
      "Global protein malabsorption",
      "Carbohydrate malabsorption",
      "Fat malabsorption"],
     0, "Defects in protein absorption — selective malabsorption: enterokinase deficiency. (Book p10)"),
    (S11, 10, "recall", "Neutral amino acid transport defect produces:",
     ["Hartnup's disease", "Cystinuria", "Pellagra of dietary origin", "Maple syrup urine disease"],
     0, "Neutral amino acid transport defect → Hartnup's disease. (Book p10)"),
    (S11, 10, "recall", "Hartnup's disease presents as pellagra with:",
     ["Diarrhoea, dermatitis, dementia",
      "Diarrhoea, dermatitis, diabetes",
      "Dermatitis, deafness, dementia",
      "Diarrhoea, dysphagia, dementia"],
     0, "Hartnup's disease: presents as pellagra — diarrhoea, dermatitis, dementia. (Book p10)"),
    (S11, 10, "recall", "Dibasic amino acid transport defect causes:",
     ["Cystinuria", "Hartnup's disease", "Enterokinase deficiency", "Fanconi syndrome"],
     0, "Dibasic amino acid transport defect → cystinuria. (Book p10)"),
    (S11, 10, "fillup", "Cystinuria causes excretion of COLA — cystine, ornithine, lysine and ____.",
     ["Arginine", "Alanine", "Asparagine", "Aspartate"],
     0, "Cystinuria → excretion of COLA (cystine, ornithine, lysine, arginine). (Book p10)"),
    (S11, 10, "match",
     "Match the selective protein defect to its printed consequence — 1) Hartnup's disease 2) Cystinuria … A) Excretion of COLA B) Pellagra: diarrhoea, dermatitis, dementia",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Hartnup's disease → pellagra (diarrhoea, dermatitis, dementia); cystinuria → excretion of COLA. (Book p10)"),
    (S11, 10, "oddoneout", "All of the following are in the COLA group excreted in cystinuria EXCEPT:",
     ["Histidine", "Cystine", "Ornithine", "Lysine"],
     0, "COLA = cystine, ornithine, lysine, arginine; histidine is not included. (Book p10)"),

    (S12, 10, "recall", "The dietary sources of lactose named in the book are:",
     ["Milk and cheese", "Wheat and barley", "Rice and maize", "Soybean and potato"],
     0, "Physiology: lactose (dietary — milk, cheese) → lactase (brush border) → glucose + galactose. (Book p10)"),
    (S12, 10, "fillup", "Lactase is a ____ enzyme that splits lactose into glucose and galactose.",
     ["brush border", "pancreatic", "lysosomal", "biliary"],
     0, "Lactase is a brush border enzyme: lactose → glucose + galactose. (Book p10)"),
    (S12, 10, "recall", "Congenital lactase deficiency is:",
     ["Autosomal recessive with absent enzyme from birth",
      "Autosomal dominant with reduced enzyme",
      "X-linked recessive",
      "Due to allele persistence"],
     0, "Congenital: autosomal recessive (absent enzyme from birth). (Book p10)"),
    (S12, 10, "recall", "Acquired lactase deficiency is characterised by:",
     ["↓ enzyme activity", "Absent enzyme from birth", "Excess enzyme activity", "Antibody mediated enzyme destruction"],
     0, "Acquired: ↓ enzyme activity. (Book p10)"),
    (S12, 10, "recall", "Primary acquired lactase deficiency (m/c) is due to:",
     ["A genetic defect — allele persistence",
      "Rotavirus infection",
      "Coeliac disease",
      "Bacterial overgrowth"],
     0, "Primary (m/c): genetic defect (allele persistence). (Book p10)"),
    (S12, 10, "recall", "Secondary lactase deficiency is listed with:",
     ["Infections and irritable bowel syndrome",
      "Coeliac disease and Whipple's disease",
      "Tropical sprue and SIBO",
      "Chronic pancreatitis and cirrhosis"],
     0, "Secondary: infections, irritable bowel syndrome (IBS). (Book p10)"),
    (S12, 11, "match",
     "Order the pathogenesis as printed — 1) Undigested carbohydrate 2) ↑ unabsorbed carbohydrates in colon 3) Fermented by colonic bacteria 4) ↑ acid and gases … A) ↑ acid and gases B) Undigested carbohydrate C) Fermentation by colonic bacteria D) ↑ unabsorbed carbohydrates in colon",
     ["1-B, 2-D, 3-C, 4-A", "1-A, 2-B, 3-C, 4-D", "1-C, 2-D, 3-B, 4-A", "1-B, 2-C, 3-D, 4-A"],
     0, "Pathogenesis: undigested carbohydrate → ↑ unabsorbed carbohydrates in colon → fermented by colonic bacteria → ↑ acid and gases (H2, methane, CO2). (Book p11)"),
    (S12, 11, "recall", "The colonic bacteria listed as fermenting unabsorbed carbohydrate are:",
     ["Bacteroides fragilis, bifidobacteria, lactobacillus",
      "E. coli, Klebsiella, Enterobacter",
      "Clostridium difficile, Salmonella, Shigella",
      "Pseudomonas, Proteus,Providencia"],
     0, "Fermented by colonic bacteria: Bacteroides fragilis, bifidobacteria, lactobacillus. (Book p11)"),
    (S12, 11, "oddoneout", "Pick the ODD ONE OUT — one organism is not listed among the colonic fermenters of lactose intolerance:",
     ["E. coli", "Bacteroides fragilis", "Bifidobacteria", "Lactobacillus"],
     0, "Listed colonic fermenters: Bacteroides fragilis, bifidobacteria, lactobacillus. E. coli is not listed. (Book p11)"),
    (S12, 11, "recall", "The gases produced by colonic fermentation are listed as:",
     ["H2, methane and CO2", "H2S, ammonia and NO", "O2, N2 and CO", "CO, ammonia and H2S"],
     0, "↑ acid and gases (H2, methane, CO2). (Book p11)"),
    (S12, 11, "numeric", "Symptoms of lactose intolerance appear at what interval after a meal?",
     ["90 min post prandial", "Immediately with the first bite", "6-8 hours later", "24 hours later"],
     0, "Clinical presentation: 90 min post prandial — abdominal distension, bloating, cramps. (Book p11)"),
    (S12, 11, "recall", "The 90-minute post-prandial symptoms described are:",
     ["Abdominal distension, bloating and cramps",
      "Haematochezia and tenesmus",
      "Jaundice and pruritus",
      "Haematuria and flank pain"],
     0, "90 min post prandial: abdominal distension, bloating, cramps. (Book p11)"),
    (S12, 11, "recall", "Diaper dermatitis in children with lactose intolerance is attributed to:",
     ["Acidic pH of the stool", "Alkaline pH of the stool", "Bile salt irritation", "Secondary fungal infection"],
     0, "Diaper dermatitis: in children due to acidic pH. (Book p11)"),
    (S12, 11, "recall", "Besides diaper dermatitis, children with lactose intolerance are described with:",
     ["Severe watery diarrhea, failure to thrive and irritability",
      "Constipation and megacolon",
      "Painless rectal bleeding",
      "Recurrent intussusception"],
     0, "In children: severe watery diarrhea, failure to thrive, irritability. (Book p11)"),

    (S13, 11, "recall", "Stool pH in lactose intolerance is:",
     ["Acidic", "Alkaline", "Neutral", "Unchanged from serum"],
     0, "Investigations: 1. stool pH — acidic. (Book p11)"),
    (S13, 11, "fillup",
     "Principle of the lactose hydrogen breath test: excess lactose in colon is fermented by bacteria to methane + H2, which is absorbed and tested on the ____.",
     ["breath", "urine", "serum", "stool"],
     0, "Excess lactose in colon → fermented by bacteria → methane + H2 → absorbed → tested on breath. (Book p11)"),
    (S13, 11, "numeric", "A positive lactose hydrogen breath test is defined as a rise in breath H2 of:",
     ["> 20 ppm", "> 5 ppm", "> 50 ppm", "> 90 ppm"],
     0, "Positive test: H2 > 20 ppm. (Book p11)"),
    (S13, 11, "recall", "The lactose-glucose blood test is described as:",
     ["Obsolete", "Gold standard", "The preferred screening test", "The most specific test"],
     0, "3. Lactose-glucose blood test: obsolete. (Book p11)"),
    (S13, 11, "recall", "Management of lactose intolerance in the book is:",
     ["Dietary management and calcium supplementation",
      "Lifelong antibiotics",
      "Pancreatic enzyme replacement",
      "Bile acid sequestrants"],
     0, "Management: dietary management, Ca2+ supplementation. (Book p11)"),
    (S13, 11, "oddoneout", "All of the following are listed investigations for lactose intolerance EXCEPT:",
     ["D-xylose test", "Stool pH", "Lactose hydrogen breath test", "Lactose-glucose blood test"],
     0, "Investigations listed: stool pH, lactose hydrogen breath test, lactose-glucose blood test (obsolete). D-xylose is a test of mucosal integrity. (Book p11)"),
    (S13, 11, "scenario",
     "A toddler develops abdominal distension and severe watery diarrhea 90 minutes after milk feeds, with acidic perianal dermatitis. The book's diagnosis is:",
     ["Lactose intolerance (lactase deficiency)",
      "Coeliac disease",
      "Abetalipoproteinaemia",
      "Intestinal lymphangiectasia"],
     0, "Lactose intolerance: 90 min post prandial distension, severe watery diarrhea, diaper dermatitis from acidic pH. (Book p11)"),
    (S13, 11, "management",
     "A child with confirmed lactose intolerance and poor weight gain should be managed by:",
     ["Dietary lactose restriction with calcium supplementation",
      "Oral corticosteroids",
      "Medium chain triglyceride diet",
      "Colectomy"],
     0, "Management: dietary management plus Ca2+ supplementation. (Book p11)"),
    (S13, 11, "recall", "The note lists the protein malabsorption mimics as:",
     ["Hartnup's disease (similar to pellagra) and cystinuria (COLA excretion)",
      "Coeliac disease and tropical sprue",
      "Kwashiorkor and marasmus",
      "Amyloidosis and lymphoma"],
     0, "Note: protein malabsorption — Hartnup's disease: similar to pellagra; cystinuria: excretion of COLA. (Book p11)"),

    # ------------------------------------------------------------------ p12
    (S14, 12, "recall", "Abetalipoproteinaemia is also known as:",
     ["Neuroacanthocytosis", "Bassen-Kornzweig variant of Wilson disease", "Tangier disease", "Familial acanthocytosis nigricans"],
     0, "Abetalipoproteinaemia — AKA neuroacanthocytosis. (Book p12)"),
    (S14, 12, "recall", "Inheritance of abetalipoproteinaemia is:",
     ["Autosomal recessive", "Autosomal dominant", "X-linked recessive", "Sporadic"],
     0, "Etiopathogenesis: autosomal recessive. (Book p12)"),
    (S14, 12, "fillup", "In abetalipoproteinaemia, apoB48 defect causes defective ____, so no chylomicron formation.",
     ["Esterification", "Lipolysis", "Conjugation", "Deconjugation"],
     0, "apoB48 → defective esterification → no chylomicron formation. (Book p12)"),
    (S14, 12, "recall", "Peripheral smear in abetalipoproteinaemia shows:",
     ["Acanthocytes", "Spherocytes", "Target cells", "Schistocytes"],
     0, "Investigations: 1. peripheral smear — acanthocytes. (Book p12)"),
    (S14, 12, "match",
     "Match the components of the printed triad — 1) Neurological 2) Retinopathy 3) GI … A) Steatorrhea B) Ataxia (vitamin E deficiency) C) Retinitis pigmentosa (night blindness)",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Clinical presentation: triad of neurological — ataxia (vitamin E deficiency), retinopathy — retinitis pigmentosa (night blindness), GI — steatorrhea. (Book p12)"),
    (S14, 12, "recall", "The investigation described as 100% diagnostic for abetalipoproteinaemia is:",
     ["Post prandial endoscopic biopsy",
      "Peripheral smear",
      "Fecal fat estimation",
      "Serum lipoprotein electrophoresis"],
     0, "2. Post prandial endoscopic biopsy: 100% diagnostic. (Book p12)"),
    (S14, 12, "recall", "The endoscopic biopsy in abetalipoproteinaemia shows:",
     ["Vacuolation in enterocytes",
      "Villous atrophy with crypt hyperplasia",
      "Non-caseating granulomas",
      "PAS-positive foamy macrophages"],
     0, "Post prandial endoscopic biopsy: 100% diagnostic; vacuolation in enterocytes. (Book p12)"),
    (S14, 12, "match",
     "Match the step in the vitamin E deficiency pathway — 1) ↓ chylomicron formation 2) Fat malabsorption 3) ↓ vitamin E absorption … A) ↓ vitamin E absorption (fat soluble) B) ↓ chylomicron formation C) Fat malabsorption",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-A, 3-C"],
     0, "Pathogenesis: ↓ chylomicron formation → fat malabsorption → ↓ vitamin E absorption (fat soluble). (Book p12)"),
    (S14, 12, "recall", "The other limb of vitamin E deficiency in abetalipoproteinaemia is:",
     ["↓ VLDL formation → ↓ secretion of vitamin E by the liver into blood",
      "↑ biliary excretion of vitamin E",
      "Renal loss of vitamin E",
      "Bacterial consumption of vitamin E"],
     0, "↓ VLDL formation → ↓ secretion of vitamin E by the liver into blood. (Book p12)"),
    (S14, 12, "recall", "Conditions the book says are diagnosed on biopsy are:",
     ["Whipple's disease, abetalipoproteinaemia and agammaglobulinaemia",
      "Coeliac disease, tropical sprue and SIBO",
      "Cystinuria, Hartnup disease and enterokinase deficiency",
      "Chronic pancreatitis, cirrhosis and SIBO"],
     0, "Note: conditions diagnosed with biopsy — Whipple's disease, abetalipoproteinaemia, agammaglobulinaemia. (Book p12)"),
    (S14, 12, "truefalse",
     "TRUE or FALSE — hypolipidemia is listed as a clinical feature of abetalipoproteinaemia.",
     ["True — hypolipidemia is listed",
      "False — lipids are markedly elevated",
      "False — lipids are always normal",
      "True — but only triglycerides are low"],
     0, "Clinical presentation: hypolipidemia, then the triad of ataxia, retinitis pigmentosa and steatorrhea. (Book p12)"),
    (S14, 12, "scenario",
     "A child with steatorrhea, ataxia and night blindness has acanthocytes on smear. The ataxia is most pronounced because of:",
     ["Vitamin E deficiency",
      "Vitamin B12 deficiency",
      "Vitamin K deficiency",
      "Folate deficiency"],
     0, "Vitamin E deficiency in abetalipoproteinaemia: clinical features — ataxia (pronounced). (Book p12)"),

    # ------------------------------------------------------------------ p13
    (S15, 13, "recall", "The physiology box for intestinal lymphangiectasia shows chylomicrons moving:",
     ["Across intestinal lymphatics into blood",
      "Across the portal vein into bile",
      "Into the colonic lumen for excretion",
      "Into enterocytes from the blood"],
     0, "Physiology: chylomicrons → across intestinal lymphatics → blood. (Book p13)"),
    (S15, 13, "recall", "Secondary intestinal lymphangiectasia follows:",
     ["Lymph node obstruction → ↑ lymphatic pressure → exudation",
      "Congenital absence of lacteals",
      "Portal hypertension",
      "Bile duct obstruction"],
     0, "Secondary: lymph node obstruction → ↑ lymphatic pressure → exudation. (Book p13)"),
    (S15, 13, "recall", "Secondary causes listed are:",
     ["Lymphoma and Crohn's disease",
      "Coeliac disease and tropical sprue",
      "Chronic pancreatitis and SIBO",
      "Cystinuria and Hartnup disease"],
     0, "Secondary: lymphoma, Crohn's disease. (Book p13)"),
    (S15, 13, "recall", "Primary intestinal lymphangiectasia is described as:",
     ["Abnormally dilated lymphatic channels with ↑ pressure and exudation into the intestinal lumen",
      "Obstruction of lymph nodes by metastases",
      "Congenital absence of the thoracic duct",
      "Lymphatic obliteration by fibrosis"],
     0, "Primary: abnormally dilated lymphatic channel → ↑ pressure → exudation into intestinal lumen. (Book p13)"),
    (S15, 13, "recall", "The most important cause of protein losing enteropathy, per the book, is:",
     ["Primary intestinal lymphangiectasia",
      "Coeliac disease",
      "Nephrotic syndrome",
      "Cirrhosis"],
     0, "1. Protein losing enteropathy — most important: primary intestinal lymphangiectasia. (Book p13)"),
    (S15, 13, "recall", "Protein losing enteropathy produces:",
     ["Hypoalbuminaemia with hypogammaglobulinaemia",
      "Hyperalbuminaemia with polyclonal gammopathy",
      "Isolated hypergammaglobulinaemia",
      "Isolated IgM elevation"],
     0, "Protein losing enteropathy: hypoalbuminaemia with hypogammaglobulinaemia. (Book p13)"),
    (S15, 13, "match",
     "Match the cause of edema to the printed mechanism — 1) Nephrotic syndrome 2) Liver disease 3) Protein losing enteropathy … A) ↓ albumin production B) Loss of albumin in urine C) Exudation into the intestinal lumen",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     0, "Nephrotic syndrome: loss of albumin in urine; liver disease: ↓ albumin production; protein losing enteropathy: exudation into the intestinal lumen. (Book p13)"),
    (S15, 13, "recall", "The specific investigation for intestinal lymphangiectasia is:",
     ["Fecal α-1 antitrypsin — elevated",
      "Fecal elastase",
      "D-xylose test",
      "Schilling test"],
     0, "Investigation: fecal α-1 antitrypsin: elevated (specific test). (Book p13)"),
    (S15, 13, "recall", "CT scan in intestinal lymphangiectasia shows:",
     ["Wall thickening of the small intestine",
      "Dilatation of the bile ducts",
      "Pancreatic calcification",
      "Mesenteric lymph node calcification"],
     0, "CT scan: wall thickening of small intestine. (Book p13)"),
    (S15, 13, "recall", "The endoscopic investigation listed for intestinal lymphangiectasia is:",
     ["Video capsule endoscopy",
      "Colonoscopy with ileal intubation only",
      "Endoscopic ultrasound",
      "Enteroscopy with submucosal dissection"],
     0, "Investigation: video capsule endoscopy. (Book p13)"),
    (S15, 13, "recall", "Management of intestinal lymphangiectasia is:",
     ["Medium chain triglyceride diet",
      "Gluten-free diet",
      "High long chain fat diet",
      "Total parenteral nutrition alone"],
     0, "Management: medium chain triglyceride diet. (Book p13)"),
    (S15, 13, "oddoneout", "All of the following are listed features of intestinal lymphangiectasia EXCEPT:",
     ["Hyperalbuminaemia", "Edema", "Ascites", "Diarrhea"],
     0, "Features: protein losing enteropathy with hypoalbuminaemia, edema, ascites, diarrhea. Hyperalbuminaemia is not listed. (Book p13)"),
    (S15, 13, "recall", "On endoscopy, intestinal lymphangiectasia appears as:",
     ["Diffuse white lesions with dilated lymphatics",
      "Deep serpiginous ulcers",
      "Cobblestone mucosa",
      "Pseudomembranous plaques"],
     0, "Endoscopy image: diffuse white lesions — lymphangiectasia on endoscopy with dilated lymphatics. (Book p13)"),
]


def build():
    questions = []
    for index, (sec, page, fmt, stem, opts, ans, exp) in enumerate(RAW, 1):
        questions.append({
            "id": f"MED-C{CHAPTER}-{index:02d}",
            "sec": sec,
            "page": page,
            "fmt": fmt,
            "q": stem,
            "opts": opts,
            "ans": ans,
            "exp": exp,
        })
    return questions


GUIDES = {
    S1: ("Basics of Absorption & Stages",
         "Three stages in order: Luminal → Mucosal → Post mucosal.\nLuminal is enzymes mediated; mucosal is the enterocyte brush border.\nPost mucosal is movement from the mucosal epithelial cell into blood."),
    S2: ("Anatomy of the Small Intestine",
         "Proximal 2/3 = maximum absorption (jejunum > duodenum).\nDistal 1/3 = bile acid, vitamin B12 and Mg2+ (ileum).\nFix the segment before learning each nutrient."),
    S3: ("Histology: Mucosa",
         "Villi are the specific feature and are surrounded by crypts of Lieberkühn.\nPaneth cells sit at the crypt base and make alpha defensins, lysozymes, phospholipase A2.\nRenewal every 48-72 hrs; interstitial cells of Cajal are pacemaker cells."),
    S4: ("Small Intestine Layers & Peyer's Patches",
         "Layers: mucosa, submucosa, muscularis propria, serosa.\nPeyer's patches are macroscopic lymphoid aggregates of the ileal submucosa.\nIn typhoid they hypertrophy."),
    S5: ("Fat Absorption: Luminal Phase",
         "Bile acids + pancreatic lipase act on triglyceride → lipolysis → fatty acids + glycerol.\nMicelles then pass into enterocytes by passive diffusion.\nChronic pancreatitis removes the lipase step."),
    S6: ("Bile Acid Physiology",
         "Body pool 4 g, maintained by enterohepatic circulation.\nSynthesis (7α-hydroxylase, rate limiting) → cholic and chenodeoxycholic acid → conjugation with glycine/taurine → bile salts.\nColonic bacterial deconjugation gives deoxycholic and lithocholic acid."),
    S7: ("Defects in Luminal & Mucosal Phase",
         "Luminal: chronic pancreatitis (lipase) and bile acid defect (secretion/synthesis/reabsorption).\nBile duct destruction in cirrhosis, PBC, PSC; ileal dysfunction in TB/Crohn's; early deconjugation in SIBO.\nMucosal: coeliac disease, Whipple disease, tropical sprue."),
    S8: ("Post-Mucosal Phase & Types of Fatty Acids",
         "LCFA + glycerol → esterification → chylomicrons → intestinal lymphatics.\nDisorders: abetalipoproteinaemia and intestinal lymphangiectasia.\nChain length >12 / 8-12 / <8; only long chain needs lipolysis and micelles; short chain is colonic and substantial in stool."),
    S9: ("Carbohydrate Absorption Mechanism",
         "Disaccharidases on the brush border: lactase, maltase, sucrase, trehalase.\nGut: SGLT1 (active) for glucose/galactose, GLUT5 for fructose.\nLiver: GLUT2 entry then galactokinase, fructokinase, glucokinase."),
    S10: ("Defects in Carbohydrate Absorption",
         "Congenital forms are autosomal recessive.\nSelective = lactase deficiency; global = small intestinal mucosal defect (coeliac, Whipple's, tropical sprue).\nPrimary (m/c) lactase deficiency is allele persistence; secondary follows infections and IBS."),
    S11: ("Protein Absorption & Selective Defects",
         "Trypsinogen → trypsin → activates chymotrypsin and elastase.\nSelective defects: enterokinase deficiency, Hartnup's disease (pellagra), cystinuria (COLA).\nCOLA = cystine, ornithine, lysine, arginine."),
    S12: ("Lactose Intolerance: Physiology to Pathogenesis",
         "Lactose (milk, cheese) → lactase (brush border) → glucose + galactose.\nCongenital autosomal recessive versus acquired ↓ activity (primary allele persistence, secondary infections/IBS).\nUnabsorbed carbohydrate is fermented to acid and H2, methane, CO2."),
    S13: ("Lactose Intolerance: Presentation & Investigations",
         "90 min post prandial distension, bloating, cramps; acidic diaper dermatitis in children.\nStool pH acidic; lactose hydrogen breath test positive at H2 > 20 ppm.\nLactose-glucose blood test is obsolete; treat with diet and calcium."),
    S14: ("Abetalipoproteinemia",
         "AKA neuroacanthocytosis; autosomal recessive; apoB48 → defective esterification → no chylomicrons.\nTriad: ataxia (vitamin E), retinitis pigmentosa, steatorrhea; smear shows acanthocytes.\nPost prandial endoscopic biopsy is 100% diagnostic with enterocyte vacuolation."),
    S15: ("Intestinal Lymphangiectasia",
         "Chylomicrons cross intestinal lymphatics into blood.\nPrimary = dilated channels; secondary = lymphoma or Crohn's with lymphatic obstruction.\nProtein losing enteropathy with fecal α-1 antitrypsin elevated; treat with medium chain triglyceride diet."),
}


def main():
    questions = build()
    ordered = []
    for sec, *_ in RAW:
        if sec not in ordered:
            ordered.append(sec)
    units = []
    for n, sec in enumerate(ordered, 1):
        title_text, guide = GUIDES[sec]
        units.append({
            "id": f"MED-U{CHAPTER}-{n}",
            "ch": CHAPTER,
            "n": n,
            "title": title_text,
            "sec": sec,
            "guide": guide,
            "qs": [q["id"] for q in questions if q["sec"] == sec],
        })
    chapter = {
        "chapter": CHAPTER,
        "title": TITLE,
        "pageRange": PAGES,
        "questions": questions,
        "units": units,
    }
    out = DATA / f"ch{CHAPTER:02d}.json"
    out.write_text(json.dumps(chapter, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out.name}: {len(questions)} questions / {len(units)} units")


if __name__ == "__main__":
    main()
