#!/usr/bin/env python3
"""Generate Chapter 5 Inflammatory Bowel Disease : Part 1 (Book p30-36).

Source: uploads/01.pdf PDF42-48 = Book p30-36, read sheet by sheet in printed order.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DATA.mkdir(exist_ok=True)

CHAPTER = 5
TITLE = "Inflammatory Bowel Disease : Part 1"
PAGES = "30-36"

V1 = "Entities of IBD & Microscopic Colitis"
V2 = "Diversion Colitis & Normal Histology of Colon"
V3 = "Colonic Mucosa & Definition of Diarrhea"
V4 = "Epidemiology of UC and Crohn's Disease"
V5 = "Genetic Syndromes Associated with IBD"
V6 = "IPEX Syndrome & Early Onset Childhood IBD"
V7 = "Pathogenesis of IBD"
V8 = "Ulcerative Colitis: Site & Macroscopy"
V9 = "Ulcerative Colitis: Microscopy"
V10 = "Crohn's Disease: Site & Macroscopy"
V11 = "Crohn's Disease: Microscopy"

RAW = [
    # ----------------------------------------------------------------- p30
    (V1, 30, "recall", "The entities listed under inflammatory bowel disease are:",
     ["Ulcerative colitis, Crohn's disease, microscopic colitis and diversion colitis",
      "Ulcerative colitis and Crohn's disease only",
      "Microscopic colitis and collagenous colitis only",
      "Infectious colitis and ischaemic colitis"],
     0, "Entities of inflammatory bowel disease: 1. ulcerative colitis (UC), 2. Crohn's disease (CD), 3. microscopic colitis, 4. diversion colitis. (Book p30)"),
    (V1, 30, "recall", "The book states that currently inflammatory bowel disease includes only:",
     ["UC and CD", "All four listed entities", "Microscopic colitis and diversion colitis", "UC and microscopic colitis"],
     0, "Currently, inflammatory bowel disease includes only UC and CD. (Book p30)"),
    (V1, 30, "recall", "Microscopic colitis is associated with long-term use of:",
     ["PPI and NSAIDS", "Antibiotics and steroids", "Opioids and anticholinergics", "Statins and metformin"],
     0, "Microscopic colitis: associated with long-term use of PPI and NSAIDS. (Book p30)"),
    (V1, 30, "recall", "Microscopic colitis presents with:",
     ["Chronic, non-bloody, voluminous, watery diarrhea similar to small bowel diarrhea",
      "Small volume bloody diarrhea with tenesmus",
      "Steatorrhea with weight loss",
      "Alternating constipation and obstructive episodes"],
     0, "Microscopic colitis: chronic, non-bloody, voluminous, watery diarrhea (similar to small bowel diarrhea). (Book p30)"),
    (V1, 30, "recall", "Clinical examination in microscopic colitis is:",
     ["Normal", "Shows a palpable mass", "Shows perianal fistulae", "Shows hepatosplenomegaly"],
     0, "Microscopic colitis: on clinical examination — normal. (Book p30)"),
    (V1, 30, "recall", "Endoscopy in microscopic colitis is:",
     ["Normal", "Shows continuous ulceration", "Shows pseudopolyps", "Shows cobblestoning"],
     0, "Microscopic colitis investigations: endoscopy — normal. (Book p30)"),
    (V1, 30, "match",
     "Match the microscopic colitis pattern to its printed feature — 1) Collagenous colitis 2) Lymphocytic colitis … A) Intra-epithelial lymphocytes B) Collagen band in mucosa",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Biopsy: collagenous colitis — collagen band in mucosa; lymphocytic colitis — intra-epithelial lymphocytes. (Book p30)"),
    (V1, 30, "match",
     "Match the microscopic colitis pattern to its printed association — 1) Collagenous colitis 2) Lymphocytic colitis … A) Celiac disease B) Sjogren's syndrome",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Collagenous colitis is associated with Sjogren's syndrome; lymphocytic colitis with celiac disease. (Book p30)"),
    (V1, 30, "scenario",
     "An elderly patient on long-term PPI has chronic watery voluminous non-bloody diarrhea with a normal colonoscopy. The book's diagnosis is:",
     ["Microscopic colitis", "Ulcerative colitis", "Crohn's disease", "Diversion colitis"],
     0, "Microscopic colitis: long-term PPI and NSAIDS, chronic non-bloody voluminous watery diarrhea with normal endoscopy. (Book p30)"),

    (V2, 30, "recall", "Diversion colitis is seen in:",
     ["Patients using colostomy bags after surgery for bowel malignancies",
      "Patients with ileostomy for ulcerative colitis only",
      "Patients on long-term PPI",
      "Patients with radiation enteritis"],
     0, "Diversion colitis: colitis seen in patients using colostomy bags (after surgery for bowel malignancies). (Book p30)"),
    (V2, 30, "match",
     "Order the layers of the normal colon as printed, innermost to outermost — 1) Mucosal epithelial cells 2) Lamina propria 3) Muscularis mucosa 4) Submucosa 5) Muscularis propria 6) Serosa … A) Serosa B) Mucosal epithelial cells C) Submucosa D) Lamina propria E) Muscularis propria F) Muscularis mucosa",
     ["1-B, 2-D, 3-F, 4-C, 5-E, 6-A", "1-A, 2-B, 3-C, 4-D, 5-E, 6-F", "1-F, 2-E, 3-D, 4-C, 5-B, 6-A", "1-B, 2-C, 3-D, 4-E, 5-F, 6-A"],
     0, "Normal histology of colon, innnermost to outermost: mucosal epithelial cells, lamina propria, muscularis mucosa, submucosa, muscularis propria, serosa. (Book p30)"),
    (V2, 30, "recall", "In the printed layer list, the layer immediately outside the muscularis mucosa is the:",
     ["Submucosa", "Muscularis propria", "Lamina propria", "Serosa"],
     0, "Layers: mucosal epithelial cells → lamina propria → muscularis mucosa → submucosa → muscularis propria → serosa. (Book p30)"),
    (V2, 30, "oddoneout", "Pick the ODD ONE OUT — one is not a printed layer of the normal colon:",
     ["Adventitia", "Muscularis mucosa", "Muscularis propria", "Submucosa"],
     0, "The printed layers are mucosal epithelial cells, lamina propria, muscularis mucosa, submucosa, muscularis propria and serosa. Adventitia is not listed. (Book p30)"),

    # ----------------------------------------------------------------- p31
    (V3, 31, "recall", "Compared with the small intestine, the colonic mucosa has:",
     ["No villi", "Long villi", "Villi only in the caecum", "Fused villi"],
     0, "Mucosa: villi are absent in the colon. (Book p31)"),
    (V3, 31, "recall", "The crypts of the colon contain microvilli whose function is:",
     ["Water absorption", "Mucus secretion", "Bile acid absorption", "Vitamin B12 absorption"],
     0, "Crypts: contain microvilli — water absorption. (Book p31)"),
    (V3, 31, "recall", "Goblet cells of the colon:",
     ["Secrete mucus", "Absorb water", "Produce defensins", "Secrete gastrin"],
     0, "Goblet cells: secrete mucus. (Book p31)"),
    (V3, 31, "numeric", "The note defines diarrhea as a stool volume above:",
     [">200 mL", ">100 mL", ">500 mL", ">1000 mL"],
     0, "Note: diarrhea → >200 mL of stool volume. (Book p31)"),

    (V4, 31, "recall", "Overall, in the epidemiology of IBD:",
     ["CD is more common than UC, and males outnumber females",
      "UC is more common than CD, and females outnumber males",
      "UC and CD are equally common",
      "CD is more common but females outnumber males"],
     0, "Epidemiology overall: CD > UC; males > females. (Book p31)"),
    (V4, 31, "match",
     "Match the epidemiological variable to the printed UC and CD values — 1) Female:male ratio 2) Smoking 3) Appendicectomy 4) OCP … A) UC protective / CD no association B) UC males > females / CD females > males (OCP use) C) UC no increased risk / CD increased risk D) UC protective / CD causative",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "Female:male ratio — UC males > females, CD females > males (OCP use); smoking — UC protective, CD causative; appendicectomy — UC protective, CD no association; OCP — UC no increased risk, CD increased risk. (Book p31)"),
    (V4, 31, "recall", "Smoking in IBD is:",
     ["Protective for UC and causative for CD",
      "Causative for UC and protective for CD",
      "Causative for both",
      "Protective for both"],
     0, "Smoking: UC — protective; CD — causative. (Book p31)"),
    (V4, 31, "recall", "Appendicectomy is:",
     ["Protective for UC with no association for CD",
      "Protective for both",
      "A risk factor for both",
      "Protective for CD only"],
     0, "Appendicectomy: UC — protective; CD — no association. (Book p31)"),
    (V4, 31, "recall", "Oral contraceptive pills carry:",
     ["Increased risk for CD but no increased risk for UC",
      "Increased risk for UC but not CD",
      "No increased risk for either",
      "Increased risk for both equally"],
     0, "OCP: UC — no increased risk; CD — increased risk. (Book p31)"),
    (V4, 31, "recall", "Familial inheritance (concordance) in IBD is:",
     ["Significant, and greater for CD than UC",
      "Not significant",
      "Significant and greater for UC than CD",
      "Significant but equal for both"],
     0, "Familial inheritance (concordance): significant; CD > UC. (Book p31)"),
    (V4, 31, "numeric", "Antibiotics in the first year of life increase the risk of IBD by:",
     ["3 times", "30 times", "1.5 times", "10 times"],
     0, "Antibiotics in 1st year of life → increases risk of IBD by 3 times. (Book p31)"),
    (V4, 31, "recall", "The age distribution of IBD is described by the book as having peaks at:",
     ["15-30 years and 70-90 years",
      "5-15 years and 40-50 years",
      "30-45 years only (single peak)",
      "0-5 years and 20-30 years"],
     0, "Age: peaks at 15-30 years and 70-90 years. (Book p31)"),
    (V4, 31, "recall", "The ethnicity gradient listed for IBD runs:",
     ["Jews > non-Jewish white > African American > Hispanic > Asian",
      "Asian > Hispanic > African American > non-Jewish white > Jews",
      "African American > non-Jewish white > Jews > Hispanic > Asian",
      "Non-Jewish white > Jews > Hispanic > Asian > African American"],
     0, "Ethnicity: Jews > non-Jewish white > African American > Hispanic > Asian. (Book p31)"),
    (V4, 31, "recall", "Behcet's disease and Crohn's disease share a common antibody, namely:",
     ["ASCA (anti-Saccharomyces cerevisiae antibody)",
      "p-ANCA",
      "Anti-goblet cell antibody",
      "Anti-OmpC"],
     0, "Note: Behcet's disease has GI manifestations like Crohn's disease and shares a common antibody — ASCA. (Book p31)"),
    (V4, 31, "recall", "Prolonged use of which drug causes features similar to ulcerative colitis?",
     ["α-methyl dopa", "Methyldopa withdrawal", "Isotretinoin", "Mycophenolate"],
     0, "Note: prolonged use of α-methyl dopa causes features similar to ulcerative colitis. (Book p31)"),
    (V4, 31, "scenario",
     "A patient develops a UC-like colitis after long-term therapy for hypertension. The drug implicated in the note is:",
     ["α-methyl dopa", "Amlodipine", "Hydrochlorothiazide", "Bisoprolol"],
     0, "Prolonged use of α-methyl dopa causes features similar to ulcerative colitis. (Book p31)"),
    (V4, 31, "recall", "Campylobacter jejuni is noted as a risk factor for IBD and also causes:",
     ["Large bowel diarrhea and Guillain Barre syndrome",
      "Small bowel diarrhea and hemolytic uremic syndrome",
      "Steatorrhea and osteomalacia",
      "Toxic megacolon and perforation"],
     0, "Campylobacter jejuni is a risk factor for IBD (also causes large bowel diarrhea, Guillain Barre syndrome). (Book p31)"),

    # ----------------------------------------------------------------- p32
    (V5, 32, "match",
     "Match the syndrome to its printed defect or inheritance — 1) Wiskott-Aldrich syndrome 2) Hermansky-Pudlak syndrome 3) Von Gierke's disease … A) Glucose-1-phosphatase deficiency B) WASP gene mutation (X-linked recessive) C) Autosomal recessive",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Wiskott-Aldrich — WASP gene mutation (X-linked recessive); Hermansky-Pudlak — autosomal recessive; von Gierke's disease (glycogen storage disorder type I) — glucose-1-phosphatase deficiency. (Book p32)"),
    (V5, 32, "recall", "The triad of Wiskott-Aldrich syndrome is:",
     ["Recurrent sino-pulmonary infections, recurrent eczema and recurrent thrombocytopenia with microplatelets",
      "Recurrent infections, albinism and pulmonary fibrosis",
      "Hypoglycemia, hepatomegaly and lactic acidosis",
      "Dermatitis, endocrinopathy and enteropathy"],
     0, "Wiskott-Aldrich syndrome: triad of 1. recurrent sino-pulmonary infections, 2. recurrent eczema, 3. recurrent thrombocytopenia (microplatelets). (Book p32)"),
    (V5, 32, "recall", "The platelet abnormality in Wiskott-Aldrich syndrome is:",
     ["Recurrent thrombocytopenia with microplatelets",
      "Platelet dysfunction with a normal count",
      "Thrombocytosis",
      " normal platelet function"],
     0, "Wiskott-Aldrich: recurrent thrombocytopenia (microplatelets). (Book p32)"),
    (V5, 32, "recall", "Hermansky-Pudlak syndrome is characterised by:",
     ["Platelet dysfunction with a normal platelet count",
      "Thrombocytopenia with microplatelets",
      "Thrombocytosis with bleeding",
      "Normal platelets and normal bleeding time"],
     0, "Hermansky-Pudlak syndrome: platelet dysfunction with normal platelet count. (Book p32)"),
    (V5, 32, "recall", "The interstitial lung disease of Hermansky-Pudlak syndrome is:",
     ["Pulmonary fibrosis", "Bronchiectasis", "Hypersensitivity pneumonitis", "Sarcoid-like granulomas"],
     0, "Hermansky-Pudlak: interstitial lung disease — pulmonary fibrosis. (Book p32)"),
    (V5, 32, "recall", "The third feature of Hermansky-Pudlak syndrome is:",
     ["Oculocutaneous albinism", "Doll facies", "Cerebral calcification", "Hyposplenism"],
     0, "Hermansky-Pudlak syndrome: oculocutaneous albinism. (Book p32)"),
    (V5, 32, "recall", "The features listed for von Gierke's disease are:",
     ["Hypoglycemia with or without seizures and Doll facies, hepatomegaly, lactic acidosis, hyperuricemia and hyperlipidemia",
      "Hypoglycemia, jaundice and renal tubular acidosis",
      "Hyperglycemia, ketosis and dehydration",
      "Hepatosplenomegaly with normal glucose"],
     0, "Von Gierke's disease features: hypoglycemia ± seizures, Doll facies; hepatomegaly; lactic acidosis; hyperuricemia; hyperlipidemia. (Book p32)"),
    (V5, 32, "fillup", "Von Gierke's disease is glycogen storage disorder type ____.",
     ["I", "II", "III", "V"],
     0, "Von Gierke's disease (glycogen storage disorder — type I). (Book p32)"),
    (V5, 32, "recall", "Syndromes presenting as IBD in childhood are grouped as:",
     ["UC-like non-granulomatous versus CD-like granulomatous",
      "Only granulomatous",
      "Only non-granulomatous",
      "Indistinguishable from adult onset disease"],
     0, "Present as IBD in childhood: UC (non-granulomatous) versus CD (granulomatous). (Book p32)"),
    (V5, 32, "recall", "The syndrome the book lists as the most common (m/c) presenting as IBD in childhood is:",
     ["Turner's syndrome", "Wiskott-Aldrich syndrome", "Hermansky-Pudlak syndrome", "Von Gierke's disease"],
     0, "Genetic syndromes associated with IBD: Turner's syndrome — m/c. (Book p32)"),
    (V5, 32, "oddoneout", "Pick the ODD ONE OUT — one is not a listed genetic syndrome associated with IBD:",
     ["Marfan syndrome", "Wiskott-Aldrich syndrome", "Hermansky-Pudlak syndrome", "Von Gierke's disease"],
     0, "Listed syndromes: Turner's syndrome (m/c), Wiskott-Aldrich, Hermansky-Pudlak and von Gierke's disease. Marfan syndrome is not listed. (Book p32)"),

    (V6, 32, "recall", "IPEX syndrome stands for:",
     ["Immune polyendocrinopathy X-linked syndrome",
      "Immune polyarthritis X-linked syndrome",
      "Idiopathic polyendocrinopathy enteropathy X-linked syndrome",
      "Immunodeficiency polyendocrinopathy X-linked syndrome"],
     0, "IPEX: immune polyendocrinopathy X-linked syndrome. (Book p32)"),
    (V6, 32, "fillup", "IPEX results from loss of ____ function causing reduced regulatory T-cell tolerance.",
     ["Foxp3", "AIRE", "WASP", "STAT3"],
     0, "Pathology: loss of Foxp3 function → reduced T-reg cell tolerance → IPEX syndrome. (Book p32)"),
    (V6, 32, "recall", "The triad of IPEX syndrome is:",
     ["Dermatitis, endocrinopathy (type I DM / thyroiditis) and UC-like enteropathy",
      "Eczema, thrombocytopenia and sino-pulmonary infections",
      "Albinism, pulmonary fibrosis and colitis",
      "Arthritis, uveitis and pyoderma gangrenosum"],
     0, "IPEX clinical features: triad of dermatitis, endocrinopathy (type I DM / thyroiditis), UC-like enteropathy. (Book p32)"),
    (V6, 33, "recall", "Management of IPEX syndrome is:",
     ["Supportive care and replacement therapy, and gene therapy",
      "Colectomy",
      "Gluten-free diet",
      "Anti-TNF therapy alone"],
     0, "IPEX management: supportive care and replacement therapy; gene therapy. (Book p33)"),
    (V6, 33, "recall", "The investigation for IPEX syndrome is:",
     ["Genetic testing", "Anti-TTG serology", "Colonoscopic biopsy", "Stool calprotectin"],
     0, "IPEX investigations: genetic testing. (Book p33)"),
    (V6, 33, "match",
     "Match the T-cell marker to its printed meaning — 1) CD3 2) CD25 3) CD4 … A) Helper T-cell B) Pan T-cell marker C) T-reg cell",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Markers of T-reg cell: CD3 — pan T-cell marker; CD25 — T-reg cell; CD4 — helper T-cell. (Book p33)"),
    (V6, 33, "recall", "Early onset childhood IBD is associated with a defect in:",
     ["IL-10 or the IL-10 receptor",
      "IL-17 or the IL-17 receptor",
      "IL-4 or IL-13",
      "Interferon gamma"],
     0, "Early onset childhood IBD: defect in IL-10 or IL-10 receptor function. (Book p33)"),
    (V6, 33, "recall", "Early onset childhood IBD presents as:",
     ["Severe refractory IBD in early life",
      "Mild self-limiting colitis",
      "Asymptomatic serological abnormality",
      "Isolated perianal disease"],
     0, "Early onset childhood IBD: severe refractory IBD in early life. (Book p33)"),
    (V6, 33, "recall", "The most potent anti-inflammatory cytokine in the body, per the note, is:",
     ["IL-10", "IL-4", "TGF-β", "IL-1 receptor antagonist"],
     0, "Note: most potent anti-inflammatory cytokine in the body — IL-10. (Book p33)"),

    (V7, 33, "fillup", "Exogenous and endogenous factors produce a dysregulated ____ immune response in a genetically susceptible individual.",
     ["mucosal", "systemic", "humoral", "vascular"],
     0, "Pathogenesis of IBD: exogenous and endogenous factors → dysregulated mucosal immune response in a genetically susceptible individual. (Book p33)"),
    (V7, 33, "recall", "In ulcerative colitis the overactive adaptive immune system is described as which lineage?",
     ["Th2", "Th1", "Th17 only", "T-reg deficiency"],
     0, "Ulcerative colitis: overactive adaptive immune system — Th2 lineage. (Book p33)"),
    (V7, 33, "recall", "The gene polymorphism linked to Crohn's disease is:",
     ["NOD2 (CARD15) on chromosome 16", "HLA DQ2", "WASP", "Foxp3"],
     0, "Crohn's disease: NOD2 (CARD15) gene polymorphism on chromosome 16 in genetically susceptible individuals. (Book p33)"),
    (V7, 33, "recall", "Defective innate immunity in Crohn's disease includes decreased clearance of:",
     ["Intracellular organisms — Mycobacterium paratuberculosis and M. avium complex",
      "Extracellular Gram negative bacilli",
      "Fungal spores",
      "Helminths"],
     0, "Defective innate immunity: decreased clearance of intracellular organisms (Mycobacterium paratuberculosis, M. avium complex). (Book p33)"),
    (V7, 33, "recall", "Another innate defect listed for Crohn's disease is:",
     ["Decreased defensin production from Paneth cells",
      "Increased defensin production from Paneth cells",
      "Loss of Paneth cells",
      "Paneth cell metaplasia in the rectum"],
     0, "Defective innate immunity: decreased defensin production from Paneth cells. (Book p33)"),
    (V7, 33, "match",
     "Match the Crohn's disease pathogenic step to its printed content — 1) Defective innate immunity 2) Defective autophagy 3) Overactive adaptive immunity 4) Altered microbiota … A) Decrease in gut bacteria like Faecalibacterium (gut protective) B) Decreased clearance of intracellular organisms C) Th1 lineage D) Autophagy defect",
     ["1-B, 2-D, 3-C, 4-A", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "Defective innate immunity: decreased clearance of intracellular organisms and decreased defensin from Paneth cells; defective autophagy; overactive adaptive immune system (Th1 lineage); decrease in protective gut bacteria such as Faecalibacterium. (Book p33)"),
    (V7, 33, "recall", "The protective gut bacterium noted as decreased in Crohn's disease is:",
     ["Faecalibacterium", "Bacteroides fragilis", "Escherichia coli", "Lactobacillus"],
     0, "Decrease in gut bacteria like Faecalibacterium (gut protective). (Book p33)"),
    (V7, 33, "truefalse",
     "TRUE or FALSE — the book attributes the adaptive immune overactivity of Crohn's disease to the Th1 lineage.",
     ["True — Th1 lineage in Crohn's disease",
      "False — Crohn's disease is Th2 mediated",
      "False — the lineage is not identified",
      "True — but Th2 is also overactive"],
     0, "Overactive adaptive immune system (Th lineage: Crohn's disease) — Th1. (Book p33)"),

    # ----------------------------------------------------------------- p34
    (V8, 34, "numeric", "The rectum alone is the site of involvement in ulcerative colitis in what proportion?",
     ["50%", "5%", "90%", "15%"],
     0, "Site of involvement — ulcerative colitis: rectum alone 50%. (Book p34)"),
    (V8, 34, "recall", "The macroscopy of ulcerative colitis is described as:",
     ["Hemorrhagic, edematous, ulcerated mucosa with a granular surface",
      "Normal mucosa with patchy skip lesions",
      "Cobblestone mucosa with creeping fat",
      "Transmural fissuring with strictures"],
     0, "Macroscopy: hemorrhagic, edematous, ulcerated mucosa with granular surface. (Book p34)"),
    (V8, 34, "fillup", "Pseudopolyps in ulcerative colitis are inflammatory polyps due to epithelial ____.",
     ["regeneration", "metaplasia", "dysplasia", "necrosis"],
     0, "Pseudopolyps: inflammatory polyp d/t epithelial regeneration. (Book p34)"),
    (V8, 34, "recall", "The lead pipe appearance of the colon is:",
     ["Atrophic and featureless, seen in chronic long-standing UC (rare)",
      "The typical finding of acute severe UC",
      "Caused by transmural fibrosis",
      "Pathognomonic of Crohn's colitis"],
     0, "Chronic long-standing UC (rare): lead pipe appearance (atrophic, featureless colon). (Book p34)"),
    (V8, 34, "match",
     "Match the lead pipe features as printed — 1) Feature a 2) Feature b … A) Shortening and narrowing of colon B) Loss of haustrations",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Lead pipe appearance: a. loss of haustrations; b. shortening and narrowing of colon. (Book p34)"),
    (V8, 34, "numeric", "Toxic megacolon in fulminant colitis is defined by a colon diameter above:",
     [">6 cm", ">3 cm", ">10 cm", ">15 cm"],
     0, "Fulminant colitis (very rare): toxic megacolon (colon diameter >6 cm). (Book p34)"),
    (V8, 34, "recall", "Fulminant colitis with toxic megacolon is described as:",
     ["Very rare", "The commonest presentation", "Seen in 50% of patients", "Exclusive to Crohn's disease"],
     0, "Fulminant colitis (very rare): toxic megacolon (colon diameter >6 cm). (Book p34)"),
    (V8, 34, "recall", "Haustrations in the uninvolved colon in ulcerative colitis are:",
     ["Present", "Absent", "Replaced by pseudopolyps", "Thickened"],
     0, "Image label: haustrations present (uninvolved colon). (Book p34)"),
    (V8, 34, "scenario",
     "A barium study in long-standing UC shows an atrophic, featureless, shortened colon without haustrations. The book calls this:",
     ["Lead pipe appearance", "Cobblestone appearance", "String sign", "Garden hose appearance"],
     0, "Lead pipe appearance (atrophic, featureless colon) with loss of haustrations and shortening, seen on barium study. (Book p34)"),

    # ----------------------------------------------------------------- p35
    (V9, 35, "recall", "The microscopic description of ulcerative colitis begins with:",
     ["Cryptitis with loss of crypt architecture",
      "Non-caseating granulomas",
      "Transmural lymphoid aggregates",
      "Pyloric metaplasia"],
     0, "Microscopy: cryptitis with loss of crypt architecture. (Book p35)"),
    (V9, 35, "recall", "Paneth cell metaplasia in ulcerative colitis is seen:",
     ["Distal to the hepatic flexure", "Only in the rectum", "Only in the terminal ileum", "Throughout the colon"],
     0, "Paneth cell metaplasia (seen distal to hepatic flexure). (Book p35)"),
    (V9, 35, "recall", "The earliest microscopic finding in ulcerative colitis is:",
     ["Basal plasma cells and lymphoid aggregates",
      "Crypt abscesses",
      "Non-caseating granulomas",
      "Fibrosis"],
     0, "Basal plasma cell and lymphoid aggregates: earliest finding. (Book p35)"),
    (V9, 35, "recall", "Basal plasma cells are useful because they:",
     ["Can help in diagnosing relapse in patients in remission",
      "Predict the need for colectomy",
      "Confirm Crohn's disease",
      "Exclude dysplasia"],
     0, "Basal plasma cell and lymphoid aggregates: earliest finding; can help in diagnosing relapse in remission patients. (Book p35)"),
    (V9, 35, "oddoneout", "All of the following are listed as factors AGAINST the diagnosis of ulcerative colitis EXCEPT:",
     ["Continuous mucosal involvement", "Transmural involvement", "Skip lesions", "Fistulas"],
     0, "Factors against UC: transmural involvement, thickening, fistulas, fibrosis, skip lesions, strictures, deep ulcers, fissures, abscess. Continuous mucosal involvement is typical of UC. (Book p35)"),
    (V9, 35, "match",
     "Match the finding to the disease it argues against or for — 1) Skip lesions 2) Cryptitis with loss of crypt architecture 3) Non-caseating granuloma … A) Ulcerative colitis B) Against ulcerative colitis C) Crohn's disease",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     0, "Skip lesions argue against UC; cryptitis with loss of crypt architecture supports UC; non-caseating granulomas support Crohn's disease. (Book p35)"),

    (V10, 35, "recall", "Crohn's disease can occur:",
     ["Anywhere from the oral cavity to the anal canal, including perianal disease",
      "Only in the terminal ileum",
      "Only in the colon",
      "Only in the jejunum"],
     0, "Site of involvement: can occur anywhere from oral cavity to anal canal (e.g. perianal involvement). (Book p35)"),
    (V10, 35, "numeric", "Ileocolitis accounts for what proportion of Crohn's disease?",
     ["40-50%", "15-20%", "30-40%", "70-80%"],
     0, "Ileocolitis: 40-50%. (Book p35)"),
    (V10, 35, "numeric", "Ileitis alone accounts for what proportion of Crohn's disease?",
     ["30-40%", "15-20%", "40-50%", "5-10%"],
     0, "Ileitis: 30-40%. (Book p35)"),
    (V10, 35, "numeric", "Colitis alone accounts for what proportion of Crohn's disease?",
     ["15-20%", "30-40%", "40-50%", "60-70%"],
     0, "Colitis: 15-20%. (Book p35)"),
    (V10, 35, "match",
     "Match the Crohn's distribution to its printed frequency — 1) Ileocolitis 2) Ileitis 3) Colitis … A) 15-20% B) 30-40% C) 40-50%",
     ["1-C, 2-B, 3-A", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-A, 3-B"],
     0, "Ileocolitis 40-50%; ileitis 30-40%; colitis 15-20%. (Book p35)"),
    (V10, 35, "recall", "The earliest macroscopic finding in Crohn's disease is:",
     ["Aphthous ulcers — small, translucent ulcers",
      "Linear serpiginous ulcers",
      "Cobblestone appearance",
      "Strictures"],
     0, "Earliest finding: aphthous ulcers → small, translucent ulcers. (Book p35)"),
    (V10, 35, "recall", "The most visible macroscopic finding in Crohn's disease is:",
     ["Linear, serpiginous ulcers", "Aphthous ulcers", "Pseudopolyps", "Lead pipe colon"],
     0, "Most visible finding: linear, serpiginous ulcers. (Book p35)"),
    (V10, 35, "recall", "The cobblestone appearance results from:",
     ["Ulcers fusing longitudinally and transversely with areas of uninvolved mucosa between",
      "Oedema of the submucosa alone",
      "Confluent pseudopolyps",
      "Fibrotic strictures"],
     0, "Cobblestone appearance: the ulcers fuse longitudinally and transversely with areas of uninvolved mucosa in between. (Book p35)"),
    (V10, 35, "recall", "The macroscopic description of Crohn's lesions is:",
     ["Deep, transmural, asymmetric skip lesions",
      "Superficial, symmetrical, continuous lesions",
      "Mucosal granularities only",
      "Diffuse pseudopolyposis"],
     0, "Macroscopy: deep, transmural, asymmetric skip lesions. (Book p35)"),
    (V10, 35, "recall", "Thickening of the wall and strictures in Crohn's disease reflect:",
     ["Transmural fibrosis and stenosis, typically in the terminal ileum",
      "Mucosal oedema only",
      "Muscularis mucosa hyperplasia",
      "Amyloid deposition"],
     0, "Thickening of the wall and strictures: transmural fibrosis and stenosis seen in terminal ileum. (Book p35)"),
    (V10, 35, "fillup", "Creeping fat is thickened ____ encasing the bowel wall.",
     ["mesentery", "serosa", "submucosa", "omentum"],
     0, "Creeping fat: thickened mesentery encasing the bowel wall. (Book p35)"),
    (V10, 35, "recall", "The garden hose appearance of the esophagus is noted in:",
     ["Well developed progressive systemic sclerosis",
      "Crohn's disease of the esophagus",
      "Ulcerative colitis",
      "Achalasia cardia"],
     0, "Note: garden hose appearance in esophagus → well developed progressive systemic sclerosis. (Book p35)"),
    (V10, 35, "scenario",
     "At laparotomy for ileal Crohn's disease the surgeon finds the mesentery thickened and encasing the bowel wall. The book terms this:",
     ["Creeping fat", "Cobblestoning", "Lead pipe colon", "Fat halo sign"],
     0, "Creeping fat: thickened mesentery encasing the bowel wall. (Book p35)"),

    # ----------------------------------------------------------------- p36
    (V11, 36, "recall", "Microscopically, Crohn's disease involves tissue up to the:",
     ["Muscularis propria", "Mucosa only", "Submucosa only", "Serosa only"],
     0, "Microscopy: involvement up to muscularis propria. (Book p36)"),
    (V11, 36, "recall", "Non-caseating granulomas in Crohn's disease may be found:",
     ["At any level and can be extraintestinal",
      "Only in the mucosa",
      "Only in lymph nodes",
      "Only in the rectum"],
     0, "Non-caseating granulomas: at any level, can be extraintestinal. (Book p36)"),
    (V11, 36, "recall", "The lymph node finding in Crohn's disease is:",
     ["Mesenteric lymphadenopathy", "Caseating granulomas", "Caseous necrosis", "Abscess formation"],
     0, "Microscopy: mesenteric lymphadenopathy. (Book p36)"),
    (V11, 36, "recall", "Crypt architecture in Crohn's disease is:",
     ["Normal", "Lost", "Branching and distorted", "Replaced by fibrosis"],
     0, "Changes in crypts: cryptitis, crypt abscesses; crypt architecture — normal. (Book p36)"),
    (V11, 36, "match",
     "Match the Crohn's microscopy item to its printed descriptor — 1) Crypt changes 2) Metaplasia 3) Aggregates 4) Deep involvement … A) Pyloric metaplasia B) Cryptitis and crypt abscesses with normal architecture C) Involvement up to muscularis propria D) Lymphoid aggregates",
     ["1-B, 2-A, 3-D, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-D, 3-A, 4-C"],
     0, "Cryptitis and crypt abscesses with normal crypt architecture; pyloric metaplasia; lymphoid aggregates; involvement up to muscularis propria. (Book p36)"),
    (V11, 36, "oddoneout", "All of the following are listed causes of non-caseating granuloma EXCEPT:",
     ["Rheumatoid arthritis", "Sarcoidosis", "Tuberculosis", "Berylliosis"],
     0, "Causes of non-caseating granuloma: sarcoidosis, tuberculosis, cat scratch disease, berylliosis, hypersensitivity pneumonitis, Crohn's disease. Rheumatoid arthritis is not listed. (Book p36)"),
    (V11, 36, "recall", "Which of these is listed among the causes of non-caseating granuloma?",
     ["Cat scratch disease", "Rheumatoid arthritis", "Sjogren's syndrome", "Whipple's disease"],
     0, "Causes of non-caseating granuloma: sarcoidosis, tuberculosis, cat scratch disease, berylliosis, hypersensitivity pneumonitis, Crohn's disease. (Book p36)"),
    (V11, 36, "scenario",
     "A resection specimen shows transmural inflammation with non-caseating granulomas and lymphoid aggregates, but crypt architecture is preserved. The book's diagnosis is:",
     ["Crohn's disease", "Ulcerative colitis", "Intestinal tuberculosis", "Microscopic colitis"],
     0, "Crohn's microscopy: involvement up to muscularis propria, non-caseating granulomas, lymphoid aggregates, cryptitis and crypt abscesses with normal crypt architecture. (Book p36)"),
]


GUIDES = {
    V1: ("Entities of IBD & Microscopic Colitis",
         "Four entities are listed, but IBD currently means UC and CD only.\nMicroscopic colitis follows long-term PPI and NSAID use: chronic non-bloody voluminous watery diarrhea with a normal examination and normal endoscopy.\nBiopsy: collagenous colitis (collagen band, Sjogren's) versus lymphocytic colitis (intra-epithelial lymphocytes, celiac disease)."),
    V2: ("Diversion Colitis & Normal Histology of Colon",
         "Diversion colitis occurs in patients using colostomy bags after surgery for bowel malignancies.\nNormal colonic layers, innermost to outermost: mucosal epithelial cells, lamina propria, muscularis mucosa, submucosa, muscularis propria, serosa.\nLearn the order — it anchors every depth-of-invasion comparison that follows."),
    V3: ("Colonic Mucosa & Definition of Diarrhea",
         "Colonic mucosa has no villi.\nCrypts contain microvilli for water absorption; goblet cells secrete mucus.\nDiarrhea is defined as a stool volume above 200 mL."),
    V4: ("Epidemiology of UC and Crohn's Disease",
         "Overall CD > UC and males > females; peaks at 15-30 and 70-90 years.\nEthnicity: Jews > non-Jewish white > African American > Hispanic > Asian.\nSmoking protects against UC but causes CD; appendicectomy protects against UC; OCP raises CD risk; concordance is significant and greater in CD; antibiotics in the first year triple the risk."),
    V5: ("Genetic Syndromes Associated with IBD",
         "Childhood IBD is grouped as UC-like non-granulomatous versus CD-like granulomatous; Turner's syndrome is listed as most common.\nWiskott-Aldrich: WASP mutation, X-linked recessive, eczema plus sino-pulmonary infection plus microplatelet thrombocytopenia.\nHermansky-Pudlak: autosomal recessive with platelet dysfunction, pulmonary fibrosis and oculocutaneous albinism; von Gierke type I with glucose-1-phosphatase deficiency."),
    V6: ("IPEX Syndrome & Early Onset Childhood IBD",
         "Loss of Foxp3 function reduces regulatory T-cell tolerance and causes IPEX.\nTriad: dermatitis, endocrinopathy (type I DM / thyroiditis) and UC-like enteropathy.\nSupportive care, gene therapy and genetic testing; T-reg marker is CD25; early onset IBD reflects IL-10 pathway defects."),
    V7: ("Pathogenesis of IBD",
         "Exogenous and endogenous factors drive a dysregulated mucosal immune response in a genetically susceptible host.\nUC: unclear pathogenesis with Th2 overactivity.\nCrohn's: NOD2/CARD15 on chromosome 16, defective innate immunity (intracellular organisms, Paneth cell defensins), defective autophagy, Th1 overactivity and loss of protective Faecalibacterium."),
    V8: ("Ulcerative Colitis: Site & Macroscopy",
         "Rectum alone is involved in 50%.\nHemorrhagic, edematous, ulcerated granular mucosa with pseudopolyps from epithelial regeneration.\nChronic disease rarely gives a lead pipe atrophic featureless colon; fulminant colitis rarely gives toxic megacolon with a diameter above 6 cm."),
    V9: ("Ulcerative Colitis: Microscopy",
         "Cryptitis with loss of crypt architecture.\nPaneth cell metaplasia distal to the hepatic flexure.\nBasal plasma cells and lymphoid aggregates are the earliest finding and flag relapse; transmural disease, skip lesions, fistulas, strictures and fissures all argue against UC."),
    V10: ("Crohn's Disease: Site & Macroscopy",
         "Anywhere from mouth to anus; ileocolitis 40-50%, ileitis 30-40%, colitis 15-20%.\nDeep transmural asymmetric skip lesions; aphthous ulcers are earliest, linear serpiginous ulcers most visible.\nCobblestoning, perianal fissures and fistulas, terminal ileal fibrosis and stenosis, and creeping fat."),
    V11: ("Crohn's Disease: Microscopy",
         "Involvement up to the muscularis propria with non-caseating granulomas at any level, even extraintestinal.\nMesenteric lymphadenopathy; cryptitis and crypt abscesses with normal crypt architecture.\nPyloric metaplasia, lymphoid aggregates and fibrosis; granuloma differential includes sarcoidosis, tuberculosis, cat scratch disease, berylliosis and hypersensitivity pneumonitis."),
}


def main():
    questions = []
    for index, (sec, page, fmt, stem, opts, ans, exp) in enumerate(RAW, 1):
        questions.append({
            "id": f"MED-C{CHAPTER}-{index:02d}",
            "sec": sec,
            "page": page,
            "fmt": fmt,
            "q": stem,
            "opts": opts,
            "ans": ans,
            "exp": exp,
        })
    ordered = []
    for sec, *_ in RAW:
        if sec not in ordered:
            ordered.append(sec)
    units = []
    for n, sec in enumerate(ordered, 1):
        title_text, guide = GUIDES[sec]
        units.append({
            "id": f"MED-U{CHAPTER}-{n}",
            "ch": CHAPTER,
            "n": n,
            "title": title_text,
            "sec": sec,
            "guide": guide,
            "qs": [q["id"] for q in questions if q["sec"] == sec],
        })
    out = DATA / f"ch{CHAPTER:02d}.json"
    out.write_text(json.dumps({
        "chapter": CHAPTER, "title": TITLE, "pageRange": PAGES,
        "questions": questions, "units": units,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out.name}: {len(questions)} questions / {len(units)} units")


if __name__ == "__main__":
    main()
