#!/usr/bin/env python3
"""Generate Chapter 6 Inflammatory Bowel Disease : Part 2 (Book p37-45).

Source: uploads/01.pdf PDF49-57 = Book p37-45, read sheet by sheet in printed order.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DATA.mkdir(exist_ok=True)

CHAPTER = 6
TITLE = "Inflammatory Bowel Disease : Part 2"
PAGES = "37-45"

X1 = "Ulcerative Colitis: Clinical Features"
X2 = "Fecal Calprotectin & Endoscopy in UC"
X3 = "Radiology: Barium Enema in UC"
X4 = "Crohn's Disease: Clinical Features"
X5 = "Endoscopy & Cross Sectional Imaging in Crohn's"
X6 = "Intestinal Tuberculosis versus Crohn's Disease"
X7 = "Extraintestinal Manifestations of IBD"
X8 = "Others, Other Investigations & Serology"
X9 = "Truelove And Witt's Classification"
X10 = "Medical Management of Ulcerative Colitis"
X11 = "Sulfasalazine & Surgery in Ulcerative Colitis"
X12 = "Crohn's Disease: Grading & Medical Management"
X13 = "Crohn's Disease: Management by Severity"
X14 = "Malignancy in IBD"

RAW = [
    # ----------------------------------------------------------------- p37
    (X1, 37, "recall", "The clinical features of ulcerative colitis are based on:",
     ["The level of involvement", "The age of the patient", "The serological profile", "The histological grade"],
     0, "Clinical features of ulcerative colitis are described based on the level of involvement. (Book p37)"),
    (X1, 37, "match",
     "Match the extent of ulcerative colitis to its printed presentation — 1) Proctitis 2) Proctosigmoiditis 3) Proctocolitis … A) Streaks of blood onto formed stool B) Painless bleeding per rectum C) Large bowel diarrhea with small frequent stools containing blood, pus and mucus",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     0, "Proctitis gives painless bleeding per rectum; proctosigmoiditis gives streaks of blood onto formed stool; proctocolitis gives large bowel diarrhea with small, frequent stools containing blood, pus and mucus. (Book p37)"),
    (X1, 37, "recall", "The differential diagnosis listed for painless bleeding per rectum in ulcerative colitis is:",
     ["Hemorrhoids and malignancies", "Anal fissures only", "Diverticulosis only", "Infectious colitis only"],
     0, "Painless bleeding per rectum — differential diagnosis: hemorrhoids and malignancies. (Book p37)"),
    (X1, 37, "recall", "Physical examination in ulcerative colitis is:",
     ["Normal", "Shows a right iliac fossa mass", "Shows hepatosplenomegaly", "Shows generalised tenderness"],
     0, "Clinical features: normal physical examination. (Book p37)"),
    (X1, 37, "recall", "Slow proximal transit in ulcerative colitis produces:",
     ["Constipation", "Steatorrhea", "Vomiting", "Tenesmus"],
     0, "Slow proximal transit produces constipation. (Book p37)"),
    (X1, 37, "recall", "The symptom that accompanies large bowel diarrhea in ulcerative colitis is:",
     ["Tenesmus", "Nocturnal vomiting", "Jaundice", "Dysphagia"],
     0, "Large bowel diarrhea: small, frequent stools with blood, pus and mucus, plus tenesmus. (Book p37)"),
    (X1, 37, "recall", "Systemic symptoms in ulcerative colitis are:",
     ["Very rare", "Universal", "Present in half the patients", "The presenting feature"],
     0, "Systemic symptoms are very rare in ulcerative colitis. (Book p37)"),
    (X1, 37, "fillup", "Systemic symptoms are very rare because the lineage involved is ____, acting through IL-4, IL-5 and IL-13.",
     ["Th2", "Th1", "Th17", "T-reg"],
     0, "Systemic symptoms: very rare (Th2 lineage involving IL-4, IL-5 and IL-13). (Book p37)"),
    (X1, 37, "numeric", "The book states that what proportion of ulcerative colitis patients have a relapsing course?",
     ["90%", "9%", "19%", "50%"],
     0, "90% of ulcerative colitis patients have a relapsing course. (Book p37)"),

    (X2, 37, "recall", "Fecal calprotectin is described in the note as:",
     ["The most sensitive biomarker", "A specific but insensitive biomarker", "A liver function marker", "A marker of bile acid malabsorption"],
     0, "Note: fecal calprotectin is the most sensitive biomarker. (Book p37)"),
    (X2, 37, "recall", "Fecal calprotectin is used to:",
     ["Assess disease severity, response to treatment and diagnose relapse",
      "Confirm the need for colectomy",
      "Distinguish ulcerative colitis from Crohn's disease",
      "Screen for dysplasia"],
     0, "Fecal calprotectin is used to assess disease severity, response to treatment and to diagnose relapse. (Book p37)"),
    (X2, 37, "recall", "The extent of involvement on endoscopy in ulcerative colitis is described as:",
     ["Symmetrical, superficial and continuous", "Asymmetrical and segmental", "Transmural and patchy", "Limited to the right colon"],
     0, "Endoscopy findings: symmetrical, superficial and continuous involvement. (Book p37)"),
    (X2, 37, "match",
     "Match the ulcerative colitis endoscopic item to the printed descriptor — 1) Earliest finding 2) Vascularity 3) Mucosal detail 4) Late finding … A) Decreased vascularity B) Lead pipe or pipestem colon C) Erythematous, red, velvety mucosa D) Mucosal ulcerations with fine granulations and friability",
     ["1-C, 2-A, 3-D, 4-B", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-D, 3-A, 4-C"],
     0, "Erythematous, red, velvety mucosa is the earliest finding; vascularity is decreased; the mucosa shows ulcerations with fine granulations and friability; late disease gives a lead pipe or pipestem colon. (Book p37)"),
    (X2, 37, "recall", "Inflammatory pseudopolyps are listed among the:",
     ["Endoscopy findings in ulcerative colitis", "Barium enema findings only", "Serological markers", "Surgical indications"],
     0, "Endoscopy findings in ulcerative colitis include inflammatory pseudopolyps. (Book p37)"),
    (X2, 37, "recall", "The lead pipe or pipestem colon is described as:",
     ["Very rare on endoscopy", "The usual endoscopic appearance", "Diagnostic of Crohn's colitis", "Seen in every patient"],
     0, "Lead pipe or pipestem colon is very rare on endoscopy. (Book p37)"),
    (X2, 37, "scenario",
     "A patient with long-standing colitis is scoped and shows continuous symmetrical disease from the rectum upwards with decreased vascularity, friable granular mucosa and pseudopolyps. The book's findings are those of:",
     ["Ulcerative colitis", "Crohn's colitis", "Intestinal tuberculosis", "Microscopic colitis"],
     0, "Ulcerative colitis endoscopy: symmetrical, superficial, continuous involvement with decreased vascularity, fine granulations, friability and inflammatory pseudopolyps. (Book p37)"),

    # ----------------------------------------------------------------- p38
    (X3, 38, "recall", "The earliest change on barium enema in ulcerative colitis is:",
     ["Fine mucosal granularities", "Deep collar stud ulcers", "Lead pipe colon", "Toxic megacolon"],
     0, "Barium enema: earliest change is fine mucosal granularities. (Book p38)"),
    (X3, 38, "recall", "Serrations on barium enema in ulcerative colitis produce:",
     ["A hazy margin", "A target appearance", "A comb sign", "A string sign"],
     0, "Barium enema: serrations producing a hazy margin. (Book p38)"),
    (X3, 38, "recall", "Deep ulcers extending to the submucosa correspond to the named lesion:",
     ["Collar stud ulcers", "Aphthous ulcers", "Rose thorn ulcers", "Longitudinal ulcers"],
     0, "Deep ulcers extending to the submucosa produce collar stud ulcers. (Book p38)"),
    (X3, 38, "recall", "Backwash ileitis is inflammation of the:",
     ["Terminal ileum", "Duodenum", "Ascending colon", "Rectum"],
     0, "Backwash ileitis is inflammation of the terminal ileum. (Book p38)"),
    (X3, 38, "recall", "Which structure is lost on barium enema in ulcerative colitis?",
     ["Rectal valves", "Haustra of the caecum", "Ileocaecal valve", "Appendiceal orifice"],
     0, "Barium enema findings include loss of rectal valves. (Book p38)"),
    (X3, 38, "match",
     "Match the barium enema appearance to its printed stage — 1) Earliest change 2) Deep ulcers 3) Chronic long-standing disease 4) Fulminant disease … A) Lead pipe appearance B) Toxic megacolon C) Collar stud ulcers D) Fine mucosal granularities",
     ["1-D, 2-C, 3-A, 4-B", "1-A, 2-B, 3-C, 4-D", "1-D, 2-A, 3-B, 4-C", "1-C, 2-D, 3-B, 4-A"],
     0, "Fine mucosal granularities are the earliest change; collar stud ulcers reflect deep ulcers; lead pipe appearance reflects chronic long-standing disease; toxic megacolon complicates fulminant disease. (Book p38)"),
    (X3, 38, "oddoneout", "Pick the ODD ONE OUT — one is not a listed barium enema finding in ulcerative colitis:",
     ["String sign", "Fine mucosal granularities", "Collar stud ulcers", "Backwash ileitis"],
     0, "Barium enema findings in ulcerative colitis: fine mucosal granularities, serrations, collar stud ulcers, mild narrowing of lumen, loss of rectal valves, backwash ileitis. The string sign belongs to Crohn's disease. (Book p38)"),

    (X4, 38, "recall", "The commonest site pattern of Crohn's disease is:",
     ["Ileocolitis", "Isolated colitis", "Jejunoileitis", "Isolated gastric disease"],
     0, "Crohn's disease clinical features: ileocolitis is the most common pattern. (Book p38)"),
    (X4, 38, "recall", "Episodic right lower quadrant pain in ileocolitis is:",
     ["Relieved with diarrhea", "Relieved by fasting only", "Worse after defecation", "Unrelated to bowel habit"],
     0, "Ileocolitis: episodic right lower quadrant pain relieved with diarrhea (large bowel diarrhea due to colitis). (Book p38)"),
    (X4, 38, "fillup", "Fever, weight loss and systemic symptoms in Crohn's disease reflect a ____ profile acting through IL-2 and interferon gamma.",
     ["Th1", "Th2", "Th17", "T-reg"],
     0, "Fever, weight loss and systemic symptoms are due to the Th1 profile (IL-2, interferon gamma). (Book p38)"),
    (X4, 38, "recall", "Jejunoileitis in Crohn's disease produces:",
     ["Malabsorption", "Constipation", "Jaundice", "Haematuria"],
     0, "Jejunoileitis produces malabsorption. (Book p38)"),
    (X4, 38, "recall", "A palpable inflammatory mass in Crohn's disease is due to:",
     ["Thickening of the bowel wall", "Mesenteric lymph nodes only", "An abscess cavity", "Creeping fat alone"],
     0, "Palpable inflammatory mass: due to thickening of the bowel wall. (Book p38)"),
    (X4, 38, "recall", "The fistula frequency listed for Crohn's disease is:",
     ["Enterovesical more than perianal", "Perianal more than enterovesical", "Equal for both", "Enterocutaneous only"],
     0, "Fistulas: enterovesical more than perianal. (Book p38)"),
    (X4, 38, "fillup", "Fissures in Crohn's disease progress to ____ strictures.",
     ["fibrosed", "inflammatory", "malignant", "congenital"],
     0, "Fissures progress to fibrosed strictures. (Book p38)"),
    (X4, 38, "match",
     "Match the Crohn's disease feature to its printed mechanism — 1) Palpable inflammatory mass 2) Malabsorption 3) Fistulas 4) Strictures … A) Enterovesical more than perianal B) Thickening of the bowel wall C) Fissures leading to fibrosis D) Jejunoileitis",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "The palpable inflammatory mass comes from bowel wall thickening; malabsorption from jejunoileitis; fistulas are enterovesical more than perianal; strictures follow fibrosis of fissures. (Book p38)"),
    (X4, 38, "scenario",
     "A young man has episodic right lower quadrant pain relieved by diarrhea, low grade fever, weight loss, bowel obstruction and a palpable right lower quadrant mass. The book's picture is:",
     ["Crohn's disease with ileocolitis", "Ulcerative proctitis", "Intestinal tuberculosis", "Irritable bowel syndrome"],
     0, "Crohn's ileocolitis: episodic right lower quadrant pain relieved with diarrhea, fever, weight loss, systemic symptoms, obstruction, palpable inflammatory mass. (Book p38)"),

    # ----------------------------------------------------------------- p39
    (X5, 39, "recall", "The target sign on barium enema is:",
     ["Mucosal ulcers with a surrounding translucent mound of edema",
      "A narrowed fibrosed segment",
      "A hypervascular mesentery",
      "A fatty middle layer in the bowel wall"],
     0, "Barium enema: target sign — mucosal ulcers with a surrounding translucent mound of edema. (Book p39)"),
    (X5, 39, "recall", "The target sign is described as the:",
     ["Earliest radiological and endoscopic finding", "Most specific sign of fistula", "Sign of toxic megacolon", "Late fibrotic change"],
     0, "The target sign is the earliest radiological and endoscopic finding. (Book p39)"),
    (X5, 39, "recall", "Rose thorn ulcers, fissures and the string sign are grouped as reflecting:",
     ["Transmural ulcers", "Mucosal ulcers only", "Ischaemic ulcers", "Infectious ulcers"],
     0, "Rose thorn ulcers, fissures and the string sign reflect transmural ulcers. (Book p39)"),
    (X5, 39, "recall", "The string sign represents:",
     ["Fibrosed bowel", "Active mucosal inflammation", "A fistulous track", "Mesenteric oedema"],
     0, "String sign: fibrosed bowel. (Book p39)"),
    (X5, 39, "recall", "The role of CT scan in inflammatory bowel disease is:",
     ["Limited, with MR enterography preferred instead",
      "The investigation of choice",
      "Used only for dysplasia surveillance",
      "Used only in ulcerative colitis"],
     0, "CT scan has a limited role in the diagnosis of IBD; MR enterography is preferred instead. (Book p39)"),
    (X5, 39, "match",
     "Match the CT sign to its printed meaning — 1) Target appearance 2) Comb sign 3) Fat halo sign … A) Hypervascular mesentery B) Inner and outer soft tissue attenuation with a fatty middle layer C) Colonic wall thickening",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     0, "Target appearance reflects colonic wall thickening; the comb sign reflects a hypervascular mesentery; the fat halo sign shows inner and outer soft tissue attenuation with a fatty middle layer. (Book p39)"),
    (X5, 39, "recall", "The comb sign in Crohn's disease indicates:",
     ["Hypervascular mesentery", "Fibrosed stricture", "Transmural ulceration", "Bowel wall fat deposition"],
     0, "Comb sign in Crohn's disease: hypervascular mesentery. (Book p39)"),
    (X5, 39, "recall", "In the fat halo sign the middle layer shows:",
     ["Fatty attenuation", "Soft tissue attenuation", "Calcification", "Air"],
     0, "Fat halo sign: inner and outer layers show soft tissue attenuation, the middle layer fatty attenuation. (Book p39)"),
    (X5, 39, "oddoneout", "Pick the ODD ONE OUT — one is not a listed CT scan finding in inflammatory bowel disease:",
     ["Sinus tract", "Target appearance", "Comb sign", "Fat halo sign"],
     0, "CT scan findings listed: target appearance from colonic wall thickening, comb sign and fat halo sign. Sinus tract appears among the barium enema images. (Book p39)"),

    # ----------------------------------------------------------------- p40
    (X6, 40, "match",
     "Match the feature to the Crohn's disease finding — 1) Ileocaecal valve 2) Colon 3) Ulcers … A) Four or more segments, especially terminal ileum and ileocaecal valve B) Longitudinal C) Commonly involved",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     0, "Crohn's disease: ileocaecal valve commonly involved; four or more segments especially terminal ileum and ileocaecal valve; longitudinal ulcers. (Book p40)"),
    (X6, 40, "match",
     "Match the feature to the intestinal tuberculosis finding — 1) Ileocaecal valve 2) Colon 3) Ulcers … A) Fewer than four segments, especially ileocaecal valve and ascending colon B) Transverse C) Usually strictured and patulous",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     0, "Intestinal tuberculosis: ileocaecal valve usually strictured and patulous; fewer than four segments especially ileocaecal valve and ascending colon; transverse ulcers. (Book p40)"),
    (X6, 40, "recall", "Cobblestone appearance, aphthous lesions and perianal lesions are:",
     ["Frequent in Crohn's disease and rare in intestinal tuberculosis",
      "Frequent in intestinal tuberculosis and rare in Crohn's disease",
      "Equally frequent in both",
      "Absent in both"],
     0, "Cobblestone appearance, aphthous lesions and perianal lesions are frequent in Crohn's disease and rare in intestinal tuberculosis. (Book p40)"),
    (X6, 40, "truefalse",
     "TRUE or FALSE — in the book's comparison, transverse ulcers with a usually strictured and patulous ileocaecal valve favour intestinal tuberculosis over Crohn's disease.",
     ["True — transverse ulcers and a strictured patulous valve favour tuberculosis",
      "False — those findings favour Crohn's disease",
      "False — the valve is never involved in tuberculosis",
      "True — but only when more than four segments are involved"],
     0, "Intestinal tuberculosis: transverse ulcers, usually strictured and patulous ileocaecal valve, fewer than four segments, perianal lesions rare. (Book p40)"),
    (X6, 40, "scenario",
     "A patient with ileocaecal disease has transverse ulcers, a patulous but usually strictured ileocaecal valve and involvement of fewer than four segments. The book favours:",
     ["Intestinal tuberculosis", "Crohn's disease", "Ulcerative colitis", "Behcet's disease"],
     0, "Intestinal tuberculosis: transverse ulcers, usually strictured and patulous ileocaecal valve, fewer than four segments especially ileocaecal valve and ascending colon, perianal lesions rare. (Book p40)"),

    (X7, 40, "recall", "Most extraintestinal manifestations of inflammatory bowel disease are most common in:",
     ["Crohn's disease", "Ulcerative colitis", "Microscopic colitis", "Diversion colitis"],
     0, "Most extraintestinal manifestations are most common in Crohn's disease. (Book p40)"),
    (X7, 40, "oddoneout", "Pick the ODD ONE OUT — one is not listed as most common in ulcerative colitis:",
     ["Erythema nodosum", "Uveitis", "Primary sclerosing cholangitis", "Pyoderma gangrenosum"],
     0, "Listed as most common in ulcerative colitis: uveitis, primary sclerosing cholangitis and pyoderma gangrenosum. Erythema nodosum is not in that list. (Book p40)"),
    (X7, 40, "match",
     "Match the eye manifestation to its printed descriptor — 1) Episcleritis 2) Uveitis … A) More dangerous, can lead to loss of vision, unrelated to bowel activity B) Extension of conjunctivitis, parallels bowel activity",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Episcleritis is an extension of conjunctivitis and parallels bowel activity; uveitis is more dangerous, can lead to loss of vision and is unrelated to bowel activity. (Book p40)"),
    (X7, 40, "recall", "Erythema nodosum is described by the book as:",
     ["Painful, pretibial papules", "Painless, truncal nodules", "Pruritic vesicles on the extensor surface", "Painless palmar macules"],
     0, "Erythema nodosum: painful, pretibial papules. (Book p40)"),
    (X7, 40, "match",
     "Match the arthritis pattern to its printed descriptor — 1) Peripheral arthritis type I 2) Peripheral arthritis type II … A) Ankylosing spondylitis like axial arthritis, unrelated to bowel activity B) Large joint migratory asymmetrical pauciarticular arthritis, parallels bowel activity",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Peripheral arthritis type I is large joint migratory asymmetrical pauciarticular arthritis that parallels bowel activity; type II is ankylosing spondylitis like axial arthritis unrelated to bowel activity. (Book p40)"),
    (X7, 40, "recall", "Peripheral arthritis type I in inflammatory bowel disease:",
     ["Parallels bowel activity", "Is unrelated to bowel activity", "Only occurs after colectomy", "Is erosive and deforming"],
     0, "Peripheral arthritis type I parallels bowel activity. (Book p40)"),
    (X7, 40, "recall", "Which of the following skin lesions is listed among the manifestations of inflammatory bowel disease?",
     ["Pyoderma vegetans", "Erythema multiforme", "Psoriasis", "Dermatitis herpetiformis"],
     0, "Skin lesions listed: erythema nodosum, pyoderma gangrenosum, pyoderma vegetans, aphthous ulcers and Sweet syndrome. (Book p40)"),
    (X7, 40, "scenario",
     "A patient with quiescent colitis develops large joint migratory asymmetrical pauciarticular arthritis that flares whenever the bowel symptoms flare. The book's type is:",
     ["Peripheral arthritis type I", "Peripheral arthritis type II", "Ankylosing spondylitis", "Septic arthritis"],
     0, "Peripheral arthritis type I: large joint migratory asymmetrical pauciarticular arthritis that parallels bowel activity. (Book p40)"),

    # ----------------------------------------------------------------- p41
    (X8, 41, "recall", "Primary sclerosing cholangitis in inflammatory bowel disease is:",
     ["Most common in ulcerative colitis", "Most common in Crohn's disease", "Equally common in both", "Not associated with IBD"],
     0, "Primary sclerosing cholangitis is most common in ulcerative colitis. (Book p41)"),
    (X8, 41, "recall", "Primary sclerosing cholangitis is described as fibrosing destruction of:",
     ["Intra and extrahepatic bile ducts", "Only the intrahepatic ducts", "Only the extrahepatic ducts", "The portal vein"],
     0, "Primary sclerosing cholangitis: fibrosing destruction of intra and extrahepatic bile ducts. (Book p41)"),
    (X8, 41, "numeric", "What proportion of patients with primary sclerosing cholangitis are ulcerative colitis positive?",
     ["Two thirds", "One third", "5%", "90%"],
     0, "Two thirds of patients with primary sclerosing cholangitis are ulcerative colitis positive. (Book p41)"),
    (X8, 41, "numeric", "What proportion of patients with ulcerative colitis are primary sclerosing cholangitis positive?",
     ["5%", "Two thirds", "50%", "95%"],
     0, "5% of patients with ulcerative colitis are primary sclerosing cholangitis positive. (Book p41)"),
    (X8, 41, "recall", "The stones listed under OTHERS in inflammatory bowel disease are:",
     ["Cholelithiasis and oxalate nephrolithiasis", "Struvite renal stones only", "Pigment gallstones only", "Salivary calculi"],
     0, "Stones: cholelithiasis and nephrolithiasis of the oxalate type. (Book p41)"),
    (X8, 41, "match",
     "Match the OTHERS item to its printed content — 1) Musculoskeletal 2) Liver 3) Vascular … A) Steatosis B) Increased risk of thromboembolism C) Osteopenia and osteoporosis",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     0, "Musculoskeletal: osteopenia and osteoporosis; liver: steatosis; vascular: increased risk of thromboembolism. (Book p41)"),
    (X8, 41, "numeric", "Osteopenia and osteoporosis are reported in what proportion of patients as most common?",
     ["More than 40%", "More than 4%", "More than 90%", "Less than 1%"],
     0, "Musculoskeletal: osteopenia and osteoporosis, most common in more than 40% of patients. (Book p41)"),
    (X8, 41, "recall", "Osteopenia and osteoporosis in inflammatory bowel disease are attributed to:",
     ["Long term drug use", "Vitamin A excess", "Parathyroid adenoma", "Renal phosphate wasting"],
     0, "Osteopenia and osteoporosis occur due to long term drug use. (Book p41)"),
    (X8, 41, "recall", "Fecal calprotectin and lactoferrin help to differentiate:",
     ["IBD relapse from infectious large bowel diarrhea",
      "Ulcerative colitis from Crohn's disease",
      "Irritable bowel syndrome from microscopic colitis",
      "Dysplasia from carcinoma"],
     0, "Fecal calprotectin and lactoferrin help differentiate IBD relapse from infectious large bowel diarrhea. (Book p41)"),
    (X8, 41, "recall", "Levels of fecal calprotectin and lactoferrin are:",
     ["Increased in IBD relapse", "Decreased in IBD relapse", "Unchanged in IBD relapse", "Only raised in infection"],
     0, "Levels of fecal calprotectin and lactoferrin are increased in IBD relapse. (Book p41)"),
    (X8, 41, "recall", "Relapse is identified by:",
     ["Fecal calprotectin and lactoferrin, and correlation with extraintestinal manifestations",
      "Serology alone", "Barium enema alone", "Liver function tests alone"],
     0, "Relapse is identified by fecal calprotectin and lactoferrin, and by correlation with extraintestinal manifestations. (Book p41)"),
    (X8, 41, "match",
     "Match the serological marker to its printed meaning — 1) ASCA 2) Omp-C 3) APB 4) Anti-Ia … A) Anti-pancreatic antibody B) Elevated levels mean bad prognosis and need for surgery C) Anti-Saccharomyces cerevisiae antibody D) Outer membrane porin C antibody",
     ["1-C, 2-D, 3-A, 4-B", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-C, 2-A, 3-D, 4-B"],
     0, "ASCA is anti-Saccharomyces cerevisiae antibody; Omp-C is outer membrane porin C antibody; APB is anti-pancreatic antibody; anti-Ia elevated means bad prognosis and need for surgery. (Book p41)"),
    (X8, 41, "recall", "Elevated anti-Ia in Crohn's disease indicates:",
     ["Bad prognosis and need for surgery", "Imminent response to steroids", "Coexistent celiac disease", "Resolution of inflammation"],
     0, "Anti-Ia elevated means bad prognosis and need for surgery. (Book p41)"),
    (X8, 41, "recall", "Atypical p-ANCA in ulcerative colitis:",
     ["Correlates with disease activity", "Predicts the need for colectomy", "Is diagnostic on its own", "Is unrelated to the disease"],
     0, "Ulcerative colitis serology: atypical p-ANCA correlates with disease activity. (Book p41)"),
    (X8, 41, "recall", "ASCA is common to Crohn's disease and:",
     ["Behcet's disease", "Ulcerative colitis", "Celiac disease", "Whipple's disease"],
     0, "Note: ASCA is common to Crohn's disease and Behcet's disease. (Book p41)"),
    (X8, 41, "oddoneout", "Pick the ODD ONE OUT — one is not listed under Crohn's disease serology:",
     ["Anti-goblet cell antibody", "ASCA", "Omp-C", "Anti-flagellin"],
     0, "Crohn's disease serology: ASCA, Omp-C, APB, anti-Ia and anti-flagellin. Anti-goblet cell antibody is listed under ulcerative colitis. (Book p41)"),

    # ----------------------------------------------------------------- p42
    (X9, 42, "match",
     "Match the Truelove and Witt's grade to its printed stool criterion — 1) Mild 2) Moderate 3) Severe … A) Fewer than four stools per day B) More than ten stools per day with blood C) Between mild and severe",
     ["1-A, 2-C, 3-B", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     0, "Mild: fewer than four stools per day; moderate: between mild and severe; severe: more than ten stools per day with blood. (Book p42)"),
    (X9, 42, "numeric", "The stool frequency that defines mild ulcerative colitis is:",
     ["Fewer than four stools per day", "Fewer than ten stools per day", "More than ten stools per day", "Exactly four stools per day"],
     0, "Mild ulcerative colitis: fewer than four stools per day. (Book p42)"),
    (X9, 42, "numeric", "The stool frequency that defines severe ulcerative colitis is:",
     ["More than ten stools per day with blood", "More than four stools per day", "Fewer than four stools per day", "More than twenty stools per day"],
     0, "Severe ulcerative colitis: more than ten stools per day with blood. (Book p42)"),
    (X9, 42, "numeric", "The fever threshold for severe ulcerative colitis is:",
     ["Above 37.5 °C", "Above 38.5 °C", "Above 39.5 °C", "Any documented fever"],
     0, "Severe ulcerative colitis: fever above 37.5 °C. (Book p42)"),
    (X9, 42, "numeric", "The heart rate threshold listed for severe ulcerative colitis is:",
     ["Above 90 per minute", "Above 100 per minute", "Above 120 per minute", "Above 60 per minute"],
     0, "Severe ulcerative colitis: heart rate above 90 per minute. (Book p42)"),
    (X9, 42, "numeric", "The anemia threshold for severe ulcerative colitis is a hemoglobin below:",
     ["75% of normal", "50% of normal", "90% of normal", "10 g/dL in every case"],
     0, "Severe ulcerative colitis: anemia with hemoglobin below 75% of normal. (Book p42)"),
    (X9, 42, "numeric", "The ESR threshold that separates severe from mild ulcerative colitis is:",
     ["30 mm per hour", "10 mm per hour", "50 mm per hour", "100 mm per hour"],
     0, "Mild ulcerative colitis has ESR below 30 mm per hour; severe disease has ESR above 30 mm per hour. (Book p42)"),
    (X9, 42, "recall", "Mild ulcerative colitis is characterised by:",
     ["No fever, no tachycardia and mild anemia",
      "High fever and tachycardia",
      "More than ten bloody stools per day",
      "Peritoneal signs"],
     0, "Mild ulcerative colitis: fewer than four stools per day, no fever, no tachycardia, mild anemia, ESR below 30 mm per hour. (Book p42)"),
    (X9, 42, "oddoneout", "Pick the ODD ONE OUT — one is not a Truelove and Witt's severe criterion:",
     ["ESR below 30 mm per hour", "More than ten stools per day with blood", "Fever above 37.5 °C", "Heart rate above 90 per minute"],
     0, "Severe criteria: more than ten stools per day with blood, fever above 37.5 °C, heart rate above 90 per minute, hemoglobin below 75% of normal, ESR above 30 mm per hour. (Book p42)"),

    (X10, 42, "recall", "The mainstay of treatment in ulcerative colitis is:",
     ["5-aminosalicylic acid", "Corticosteroids", "Colectomy", "Total parenteral nutrition"],
     0, "5-ASA (aminosalicylic acid) is the mainstay of treatment. (Book p42)"),
    (X10, 42, "fillup", "Plain 5-ASA is absorbed at the small intestine and therefore does not reach the ____.",
     ["rectum", "duodenum", "stomach", "liver"],
     0, "Disadvantage of plain 5-ASA: absorbed at the small intestine, so it does not reach the rectum, the site of active disease. (Book p42)"),
    (X10, 42, "recall", "Delayed or controlled release 5-ASA, that is mesalamine, is the drug of choice for:",
     ["Mild ulcerative colitis", "Severe fulminant colitis", "Toxic megacolon", "Maintenance after colectomy"],
     0, "Mesalamine is a delayed or controlled release 5-ASA and is the drug of choice for mild ulcerative colitis. (Book p42)"),
    (X10, 42, "match",
     "Match the ulcerative colitis severity to its printed induction therapy — 1) Mild 2) Moderate 3) Severe … A) Oral mesalamine and oral steroids B) Intravenous steroid C) Topical 5-ASA or oral mesalamine",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     0, "Induction: mild disease gets topical 5-ASA or oral mesalamine; moderate disease gets oral mesalamine and oral steroids; severe disease gets intravenous steroid. (Book p42)"),
    (X10, 42, "recall", "Maintenance therapy in mild ulcerative colitis is:",
     ["Topical 5-ASA", "Oral prednisolone", "Intravenous cyclosporine", "No treatment"],
     0, "Maintenance: mild ulcerative colitis is maintained on topical 5-ASA. (Book p42)"),
    (X10, 42, "recall", "Steroid resistant or refractory moderate ulcerative colitis is treated with:",
     ["Azathioprine or 6-mercaptopurine", "Increasing doses of oral steroids", "Colectomy", "Topical 5-ASA alone"],
     0, "Steroid resistant or refractory moderate ulcerative colitis: azathioprine or 6-mercaptopurine. (Book p42)"),
    (X10, 42, "recall", "Severe ulcerative colitis is induced with:",
     ["Intravenous steroid, intravenous anti-TNF-alpha or intravenous cyclosporine",
      "Topical 5-ASA alone",
      "Oral budesonide alone",
      "Mesalamine enemas alone"],
     0, "Severe ulcerative colitis induction: intravenous steroid, intravenous anti-TNF-alpha or intravenous cyclosporine. (Book p42)"),
    (X10, 42, "recall", "Maintenance in severe ulcerative colitis is with:",
     ["Azathioprine or 6-mercaptopurine, low dose anti-TNF-alpha or oral cyclosporine",
      "Topical 5-ASA alone",
      "Long term high dose prednisolone",
      "No maintenance required"],
     0, "Severe ulcerative colitis maintenance: azathioprine or 6-mercaptopurine, low dose anti-TNF-alpha or oral cyclosporine. (Book p42)"),
    (X10, 42, "scenario",
     "A patient with severe ulcerative colitis settles after intravenous steroid and now needs maintenance. According to the book you would choose:",
     ["Azathioprine or 6-mercaptopurine", "Topical 5-ASA alone", "Oral budesonide 9 mg per day", "No maintenance"],
     0, "Severe ulcerative colitis maintenance: azathioprine or 6-mercaptopurine, low dose anti-TNF-alpha or oral cyclosporine. (Book p42)"),

    # ----------------------------------------------------------------- p43
    (X11, 43, "fillup", "Sulfasalazine is 5-ASA linked to a carrier molecule called ____.",
     ["sulfapyridine", "mesalamine", "olsalazine", "balsalazide"],
     0, "Sulfasalazine: 5-ASA plus sulfapyridine as the carrier. (Book p43)"),
    (X11, 43, "recall", "Sulfasalazine is absorbed at the:",
     ["Rectum", "Stomach", "Duodenum", "Oesophagus"],
     0, "Sulfasalazine: 5-ASA plus sulfapyridine carrier, absorbed at the rectum. (Book p43)"),
    (X11, 43, "recall", "The note 'G6PD deficiency, no longer used' appears against:",
     ["Sulfasalazine", "Mesalamine", "Azathioprine", "Budesonide"],
     0, "Sulfasalazine note: G6PD deficiency means it is no longer used. (Book p43)"),
    (X11, 43, "recall", "The side effects listed for azathioprine are:",
     ["Hepatotoxicity, bone marrow suppression and pancreatitis",
      "Nephrotoxicity and ototoxicity",
      "Pulmonary fibrosis and alopecia",
      "Cardiomyopathy and cataract"],
     0, "Side effects of azathioprine: hepatotoxicity, bone marrow suppression and pancreatitis. (Book p43)"),
    (X11, 43, "recall", "The surgical procedure listed for ulcerative colitis is:",
     ["Proctocolectomy with ileoanal anastomosis",
      "Segmental colectomy",
      "Stricturoplasty",
      "Loop ileostomy alone"],
     0, "Surgical management of ulcerative colitis: proctocolectomy with ileoanal anastomosis. (Book p43)"),
    (X11, 43, "recall", "Which of the following is a listed indication for surgery in ulcerative colitis?",
     ["Medically refractory disease", "Perianal fistula", "Asymptomatic proctitis", "Mild arthralgia"],
     0, "Indications for surgery in ulcerative colitis: colonic dysplasia or carcinoma, uncontrollable colonic hemorrhage, colonic perforation, toxic megacolon and medically refractory disease. (Book p43)"),
    (X11, 43, "match",
     "Match the surgical indication to its printed wording — 1) Bleeding 2) Perforation 3) Neoplasia … A) Colonic perforation B) Uncontrollable colonic hemorrhage C) Colonic dysplasia or carcinoma",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     0, "Surgical indications: uncontrollable colonic hemorrhage, colonic perforation and colonic dysplasia or carcinoma, plus toxic megacolon and medically refractory disease. (Book p43)"),
    (X11, 43, "oddoneout", "Pick the ODD ONE OUT — one is not a listed indication for surgery in ulcerative colitis:",
     ["Perianal fistula", "Toxic megacolon", "Colonic perforation", "Colonic dysplasia or carcinoma"],
     0, "Indications for surgery in ulcerative colitis: toxic megacolon, colonic perforation, uncontrollable colonic hemorrhage, colonic dysplasia or carcinoma and medically refractory disease. Perianal fistula is not listed. (Book p43)"),

    (X12, 43, "match",
     "Match the Crohn's disease severity grade to its printed descriptor — 1) Mild-moderate 2) Moderate-severe 3) Severe-fulminant … A) Between mild and severe B) No dehydration, no obstruction, no weight loss and no systemic features C) Despite steroid intake the patient has fever, cachexia, obstruction and peritoneal signs",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     0, "Mild-moderate: no dehydration, no obstruction, no weight loss, no systemic features. Moderate-severe: between mild and severe. Severe-fulminant: despite steroid intake the patient has fever, cachexia, obstruction and peritoneal signs. (Book p43)"),
    (X12, 43, "recall", "Severe-fulminant Crohn's disease is defined by the book as:",
     ["Persistence of fever, cachexia, obstruction and peritoneal signs despite steroid intake",
      "Any obstruction at presentation",
      "Weight loss alone",
      "Response to oral budesonide"],
     0, "Severe-fulminant: despite steroid intake the patient has fever, cachexia, obstruction and peritoneal signs. (Book p43)"),
    (X12, 43, "recall", "The objectives of medical management in Crohn's disease are:",
     ["Endoscopic mucosal healing and prevention of complications such as strictures and fistulae",
      "Complete eradication of the disease",
      "Weight gain alone",
      "Normalisation of serology"],
     0, "Objectives: endoscopic mucosal healing and prevention of complications such as strictures and fistulae. (Book p43)"),
    (X12, 43, "recall", "Corticosteroids in Crohn's disease carry a high risk of:",
     ["Dependency and resistance", "Hepatotoxicity", "Bone marrow suppression", "Pancreatitis"],
     0, "Corticosteroids carry a high risk of dependency and resistance. (Book p43)"),
    (X12, 43, "recall", "The anti-TNF agents listed for Crohn's disease are:",
     ["Infliximab, adalimumab and certolizumab pegol",
      "Natalizumab, vedolizumab and ustekinumab",
      "Rituximab and tocilizumab",
      "Secukinumab and ixekizumab"],
     0, "Biologics: anti-TNF agents are infliximab, adalimumab and certolizumab pegol. (Book p43)"),
    (X12, 43, "recall", "Biologics play an important role in:",
     ["Continuously active disease and prolonged symptomatic remission",
      "Asymptomatic disease",
      "Acute infective diarrhea",
      "Perianal skin tags alone"],
     0, "Biologics play an important role in the treatment of continuously active disease and prolonged symptomatic remission. (Book p43)"),
    (X12, 43, "recall", "Which drug class is listed among the drugs used in Crohn's disease?",
     ["Immunomodulators", "Statins", "Proton pump inhibitors", "Bisphosphonates"],
     0, "Drugs listed for Crohn's disease: antibiotics, corticosteroids, 5-ASA, immunomodulators and biologics. (Book p43)"),

    # ----------------------------------------------------------------- p44
    (X13, 44, "fillup", "Mild-moderate Crohn's disease is induced with oral ____ at 9 mg per day.",
     ["budesonide", "prednisolone", "mesalamine", "methotrexate"],
     0, "Mild-moderate Crohn's disease induction: oral budesonide 9 mg per day. (Book p44)"),
    (X13, 44, "numeric", "The dose of oral budesonide used for induction in mild-moderate Crohn's disease is:",
     ["9 mg per day", "90 mg per day", "3 mg per day", "40 mg per day"],
     0, "Oral budesonide 9 mg per day for mild-moderate Crohn's disease. (Book p44)"),
    (X13, 44, "recall", "Maintenance therapy in mild-moderate Crohn's disease is:",
     ["Not required", "Azathioprine", "Periodic anti-TNF-alpha", "Oral 5-ASA"],
     0, "Mild-moderate Crohn's disease: maintenance is not required. (Book p44)"),
    (X13, 44, "match",
     "Match the Crohn's severity to the printed induction steroid — 1) Mild-moderate 2) Moderate-severe 3) Severe-fulminant … A) Intravenous steroids B) Oral budesonide C) Oral steroids",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Induction: mild-moderate gets oral budesonide, moderate-severe gets oral steroids, severe-fulminant gets intravenous steroids. (Book p44)"),
    (X13, 44, "recall", "Maintenance in severe-fulminant Crohn's disease is:",
     ["Periodic anti-TNF-alpha", "Not required", "Oral budesonide", "Topical 5-ASA"],
     0, "Severe-fulminant Crohn's disease maintenance: periodic anti-TNF-alpha. (Book p44)"),
    (X13, 44, "recall", "Maintenance in moderate-severe Crohn's disease is with:",
     ["Azathioprine or 6-mercaptopurine", "Oral budesonide", "Topical 5-ASA", "No treatment"],
     0, "Moderate-severe Crohn's disease maintenance: azathioprine or 6-mercaptopurine. (Book p44)"),
    (X13, 44, "recall", "Fistulizing Crohn's disease is managed with:",
     ["Anti-TNF-alpha with or without immunomodulators, followed by surgery",
      "Oral budesonide alone",
      "Antibiotics alone",
      "No intervention"],
     0, "Fistulizing disease: anti-TNF-alpha with or without immunomodulators followed by surgery. (Book p44)"),
    (X13, 44, "recall", "The drug listed in moderate-severe Crohn's disease alongside azathioprine and anti-TNF-alpha is:",
     ["Methotrexate", "Cyclosporine", "Tacrolimus", "Cyclophosphamide"],
     0, "Moderate-severe Crohn's disease drugs: oral steroids, azathioprine or 6-mercaptopurine, methotrexate, anti-TNF-alpha and periodic anti-TNF-alpha. (Book p44)"),
    (X13, 44, "recall", "The note on maintenance therapy in Crohn's disease advises avoiding:",
     ["Smoking and NSAIDs", "Exercise and fibre", "Dairy and gluten", "Vaccinations"],
     0, "Note: avoid smoking and NSAIDs. (Book p44)"),
    (X13, 44, "recall", "The drugs to be avoided in maintenance therapy of Crohn's disease are:",
     ["Oral 5-ASA, corticosteroids and budesonide",
      "Azathioprine and 6-mercaptopurine",
      "Anti-TNF agents and methotrexate",
      "Antibiotics and biologics"],
     0, "Drugs to be avoided in maintenance therapy: oral 5-ASA, corticosteroids and budesonide. (Book p44)"),
    (X13, 44, "match",
     "Match the newer drug to its printed target — 1) Natalizumab 2) Ustekinumab 3) Vedolizumab … A) Anti-IL-12 and IL-23 B) Anti-alpha-4 integrin C) Anti-integrin",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-B, 3-A", "1-B, 2-C, 3-A"],
     0, "Newer drugs: natalizumab is anti-alpha-4 integrin, ustekinumab is anti-IL-12 and IL-23, vedolizumab is anti-integrin. (Book p44)"),
    (X13, 44, "recall", "Natalizumab is:",
     ["An anti-alpha-4 integrin antibody", "An anti-IL-12 and IL-23 antibody", "An anti-TNF agent", "An anti-integrin antibody"],
     0, "Newer drugs: natalizumab is anti-alpha-4 integrin. (Book p44)"),
    (X13, 44, "scenario",
     "A patient with moderate-severe ileocolonic Crohn's disease is in remission after oral steroids. The book's maintenance choice is:",
     ["Azathioprine or 6-mercaptopurine", "Oral budesonide", "Topical 5-ASA", "No maintenance"],
     0, "Moderate-severe Crohn's disease maintenance: azathioprine or 6-mercaptopurine. (Book p44)"),

    # ----------------------------------------------------------------- p45
    (X14, 45, "recall", "The risk of malignancy in inflammatory bowel disease is:",
     ["Present in both ulcerative colitis and Crohn's disease",
      "Confined to ulcerative colitis",
      "Confined to Crohn's disease",
      "Negligible in both"],
     0, "Risk of malignancy is present in both ulcerative colitis and Crohn's disease. (Book p45)"),
    (X14, 45, "oddoneout", "Pick the ODD ONE OUT — one is not listed as an increased malignancy risk in inflammatory bowel disease:",
     ["Gastric carcinoma", "Non-Hodgkin's lymphoma", "Leukemia", "Myelodysplastic syndrome"],
     0, "Increased risk: non-Hodgkin's lymphoma, leukemia, myelodysplastic syndrome and cholangiocarcinoma. Gastric carcinoma is not listed. (Book p45)"),
    (X14, 45, "recall", "Cholangiocarcinoma in inflammatory bowel disease is attributed to the association with:",
     ["Primary sclerosing cholangitis", "Chronic hepatitis B", "Alcoholic liver disease", "Gallstones"],
     0, "Cholangiocarcinoma occurs due to the association with primary sclerosing cholangitis. (Book p45)"),
    (X14, 45, "match",
     "Match the sporadic colorectal carcinoma feature to the IBD related carcinoma feature — 1) Age of onset 2) Genetic sequence 3) Site of lesion … A) Adenoma to carcinoma sequence B) Any segment of diseased colon C) Ten to fifteen years younger",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     0, "Sporadic carcinoma presents after 50 years; IBD related carcinoma presents ten to fifteen years younger, follows an inflammation-dysplasia-carcinoma sequence in sporadic terms, and arises in any segment of diseased colon. (Book p45)"),
    (X14, 45, "numeric", "The age of onset quoted for sporadic colorectal carcinoma is:",
     ["Above 50 years", "Above 30 years", "Above 70 years", "Below 20 years"],
     0, "Sporadic colorectal carcinoma: age of onset above 50 years. (Book p45)"),
    (X14, 45, "numeric", "IBD related colorectal carcinoma presents how much earlier than sporadic carcinoma?",
     ["Ten to fifteen years younger", "One to two years younger", "Thirty years younger", "At the same age"],
     0, "IBD related carcinoma: ten to fifteen years younger. (Book p45)"),
    (X14, 45, "numeric", "The five year survival rate quoted in the comparison table is:",
     ["50% for both", "90% for sporadic and 50% for IBD related", "50% for sporadic and 90% for IBD related", "Unknown for both"],
     0, "Five year survival rate: 50% for both sporadic and IBD related carcinoma. (Book p45)"),
    (X14, 45, "recall", "The pathological feature of IBD related carcinoma is:",
     ["Signet ring cell carcinoma", "Adenocarcinoma", "Squamous cell carcinoma", "Carcinoid tumour"],
     0, "IBD related carcinoma is a signet ring cell carcinoma; sporadic carcinoma is an adenocarcinoma. (Book p45)"),
    (X14, 45, "recall", "Sporadic colorectal carcinoma is:",
     ["Common on the left side", "Equally distributed", "Confined to the rectum", "Confined to the caecum"],
     0, "Sporadic colorectal carcinoma is common on the left side. (Book p45)"),
    (X14, 45, "recall", "Mutation timing in sporadic colorectal carcinoma is:",
     ["APC mutation early and p53 mutation late", "p53 mutation early and APC mutation late", "Both mutations early", "Both mutations late"],
     0, "Sporadic colorectal carcinoma: APC mutation early, p53 mutation late. (Book p45)"),
    (X14, 45, "recall", "Mutation timing in IBD related carcinoma is:",
     ["p53 mutation early and APC mutation late", "APC mutation early and p53 mutation late", "Both mutations early", "Both mutations late"],
     0, "IBD related carcinoma: p53 mutation early, APC mutation late. (Book p45)"),
    (X14, 45, "scenario",
     "A patient with long-standing colitis develops a signet ring cell carcinoma in a segment of diseased colon at 38 years of age. Compared with sporadic carcinoma the book would describe this as:",
     ["Ten to fifteen years younger, arising in any segment of diseased colon",
      "Typical sporadic left sided adenocarcinoma",
      "Unrelated to the colitis",
      "Due to APC mutation occurring early"],
     0, "IBD related carcinoma: ten to fifteen years younger, signet ring cell type, any segment of diseased colon, inflammation-dysplasia-carcinoma sequence with p53 early and APC late. (Book p45)"),
]


GUIDES = {
    X1: ("Ulcerative Colitis: Clinical Features",
         "Features are described by the level of involvement: proctitis, proctosigmoiditis and proctocolitis.\nProctitis gives painless bleeding per rectum (differential: hemorrhoids and malignancies); proctosigmoiditis gives streaks of blood onto formed stool; proctocolitis gives large bowel diarrhea with small frequent stools containing blood, pus and mucus, plus tenesmus.\nPhysical examination is normal, slow proximal transit causes constipation, systemic symptoms are very rare because the lineage is Th2, and 90% have a relapsing course."),
    X2: ("Fecal Calprotectin & Endoscopy in UC",
         "Fecal calprotectin is the most sensitive biomarker and is used to assess severity, treatment response and relapse.\nEndoscopy shows symmetrical, superficial, continuous involvement.\nErythematous red velvety mucosa is earliest; vascularity is decreased; the mucosa shows ulcerations with fine granulations and friability; inflammatory pseudopolyps and, very rarely, a lead pipe colon."),
    X3: ("Radiology: Barium Enema in UC",
         "Barium enema is the radiological heading for ulcerative colitis.\nFine mucosal granularities are the earliest change, followed by serrations giving a hazy margin, mild luminal narrowing and loss of rectal valves.\nDeep ulcers reaching the submucosa give collar stud ulcers; backwash ileitis inflames the terminal ileum; chronic disease gives a lead pipe and fulminant disease toxic megacolon."),
    X4: ("Crohn's Disease: Clinical Features",
         "Ileocolitis is the commonest pattern: episodic right lower quadrant pain relieved by diarrhea.\nFever, weight loss and systemic symptoms reflect the Th1 profile with IL-2 and interferon gamma.\nJejunoileitis causes malabsorption; a palpable inflammatory mass comes from bowel wall thickening; obstruction, enterovesical more than perianal fistulas, and fissures progressing to fibrosed strictures complete the list."),
    X5: ("Endoscopy & Cross Sectional Imaging in Crohn's",
         "The target sign, mucosal ulcers with a translucent mound of edema, is the earliest radiological and endoscopic finding.\nRose thorn ulcers, fissures and the string sign reflect transmural disease; the string sign itself is fibrosed bowel.\nCT has a limited role because MR enterography is preferred: target appearance from wall thickening, comb sign from a hypervascular mesentery, and fat halo sign with soft tissue inner and outer layers around a fatty middle layer."),
    X6: ("Intestinal Tuberculosis versus Crohn's Disease",
         "Crohn's: ileocaecal valve commonly involved, four or more segments especially terminal ileum and ileocaecal valve, longitudinal ulcers, and frequent cobblestoning, aphthous and perianal lesions.\nTuberculosis: ileocaecal valve usually strictured and patulous, fewer than four segments especially ileocaecal valve and ascending colon, transverse ulcers, and rare cobblestoning, aphthous and perianal lesions.\nTransverse ulcers plus a patulous strictured valve with fewer than four segments is the tuberculosis pattern."),
    X7: ("Extraintestinal Manifestations of IBD",
         "Most extraintestinal manifestations are most common in Crohn's disease; uveitis, primary sclerosing cholangitis and pyoderma gangrenosum are most common in ulcerative colitis.\nEye: episcleritis extends from conjunctivitis and parallels bowel activity; uveitis is more dangerous, can cause vision loss and is unrelated to bowel activity.\nSkin: painful pretibial papules of erythema nodosum, pyoderma gangrenosum, pyoderma vegetans, aphthous ulcers and Sweet syndrome. Joints: type I pauciarticular arthritis parallels the bowel; type II axial arthritis does not."),
    X8: ("Others, Other Investigations & Serology",
         "Primary sclerosing cholangitis is most common in ulcerative colitis and fibroses intra and extrahepatic ducts; two thirds of PSC patients have UC and 5% of UC patients have PSC.\nOthers: gallstones and oxalate renal stones, osteopenia and osteoporosis in over 40% from long term drug use, hepatic steatosis and raised thromboembolic risk.\nFecal calprotectin and lactoferrin separate relapse from infectious diarrhea and rise during relapse. Serology: p-ANCA and anti-goblet cell antibody for UC; ASCA, Omp-C, anti-pancreatic antibody, anti-Ia and anti-flagellin for Crohn's."),
    X9: ("Truelove And Witt's Classification",
         "Mild: fewer than four stools per day, no fever, no tachycardia, mild anemia, ESR below 30 mm per hour.\nModerate sits between mild and severe.\nSevere: more than ten stools per day with blood, fever above 37.5 °C, heart rate above 90, hemoglobin below 75% of normal and ESR above 30 mm per hour."),
    X10: ("Medical Management of Ulcerative Colitis",
         "5-ASA is the mainstay, but plain 5-ASA is absorbed in the small intestine and never reaches the rectum; delayed release mesalamine is the drug of choice for mild disease.\nInduction: topical 5-ASA or oral mesalamine for mild, add oral steroids for moderate, intravenous steroid for severe.\nSteroid refractory moderate disease moves to azathioprine or 6-mercaptopurine; severe disease adds intravenous anti-TNF or cyclosporine, and maintenance uses azathioprine or 6-mercaptopurine with low dose anti-TNF or oral cyclosporine."),
    X11: ("Sulfasalazine & Surgery in Ulcerative Colitis",
         "Sulfasalazine is 5-ASA carried by sulfapyridine, absorbed at the rectum, and abandoned in G6PD deficiency.\nAzathioprine side effects are hepatotoxicity, bone marrow suppression and pancreatitis.\nSurgery is proctocolectomy with ileoanal anastomosis for toxic megacolon, perforation, uncontrollable hemorrhage, dysplasia or carcinoma, and medically refractory disease."),
    X12: ("Crohn's Disease: Grading & Medical Management",
         "Grading: mild-moderate has no dehydration, obstruction, weight loss or systemic features; moderate-severe lies between; severe-fulminant means fever, cachexia, obstruction and peritoneal signs despite steroids.\nObjectives are endoscopic mucosal healing and prevention of strictures and fistulae.\nDrugs: antibiotics, corticosteroids with their dependency risk, 5-ASA, immunomodulators and biologics such as infliximab, adalimumab and certolizumab pegol."),
    X13: ("Crohn's Disease: Management by Severity",
         "Induction: oral budesonide 9 mg per day for mild-moderate, oral steroids for moderate-severe, intravenous steroids for severe-fulminant.\nMaintenance: none for mild-moderate, azathioprine or 6-mercaptopurine for moderate-severe, periodic anti-TNF for severe-fulminant.\nFistulizing disease needs anti-TNF with or without immunomodulators then surgery; avoid smoking and NSAIDs; never maintain with oral 5-ASA, corticosteroids or budesonide. Newer agents: natalizumab, ustekinumab and vedolizumab."),
    X14: ("Malignancy in IBD",
         "Risk exists in both ulcerative colitis and Crohn's disease: lymphoma, leukemia, myelodysplasia and cholangiocarcinoma from primary sclerosing cholangitis.\nIBD related carcinoma arises ten to fifteen years younger, in any segment of diseased colon, as a signet ring cell carcinoma.\nGenetics invert the sporadic pattern: sporadic is APC early and p53 late, IBD related is p53 early and APC late. Five year survival is 50% for both."),
}


def main():
    questions = []
    for index, (sec, page, fmt, stem, opts, ans, exp) in enumerate(RAW, 1):
        questions.append({
            "id": f"MED-C{CHAPTER}-{index:02d}",
            "sec": sec,
            "page": page,
            "fmt": fmt,
            "q": stem,
            "opts": opts,
            "ans": ans,
            "exp": exp,
        })
    ordered = []
    for sec, *_ in RAW:
        if sec not in ordered:
            ordered.append(sec)
    units = []
    for n, sec in enumerate(ordered, 1):
        title_text, guide = GUIDES[sec]
        units.append({
            "id": f"MED-U{CHAPTER}-{n}",
            "ch": CHAPTER,
            "n": n,
            "title": title_text,
            "sec": sec,
            "guide": guide,
            "qs": [q["id"] for q in questions if q["sec"] == sec],
        })
    out = DATA / f"ch{CHAPTER:02d}.json"
    out.write_text(json.dumps({
        "chapter": CHAPTER, "title": TITLE, "pageRange": PAGES,
        "questions": questions, "units": units,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out.name}: {len(questions)} questions / {len(units)} units")


if __name__ == "__main__":
    main()
