#!/usr/bin/env python3
"""Generate Chapter 3 Clinical Features And Tests For Malabsorption (Book p14-17).

Source: uploads/01.pdf PDF26-29 = Book p14-17, read sheet by sheet in printed order.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DATA.mkdir(exist_ok=True)

CHAPTER = 3
TITLE = "Clinical Features And Tests For Malabsorption"
PAGES = "14-17"

T1 = "Steps for Evaluating Malabsorption"
T2 = "Clinical Features: Gastrointestinal"
T3 = "Clinical Features: Musculoskeletal & Cutaneous"
T4 = "Clinical Features: Miscellaneous & Kidney Stones"
T5 = "Fat Malabsorption Tests"
T6 = "D-Xylose Test"
T7 = "False Positives & Hydrogen Breath Tests"
T8 = "Obsolete Tests & Biopsy Diagnoses"
T9 = "Schilling Test"

RAW = [
    # ----------------------------------------------------------------- p14
    (T1, 14, "recall", "The first step in evaluating malabsorption is to:",
     ["Confirm the diagnosis",
      "Confirm the aetiology",
      "Start a gluten-free diet",
      "Confirm global versus selective malabsorption"],
     0, "Steps for evaluating malabsorption: 1. confirm the diagnosis (clinically / by investigations). (Book p14)"),
    (T1, 14, "match",
     "Order the printed steps — 1) Step 1 2) Step 2 3) Step 3 … A) Confirm global vs selective malabsorption B) Confirm the diagnosis C) Confirm the aetiology",
     ["1-B, 2-A, 3-C", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-C, 3-A"],
     0, "1. Confirm the diagnosis, 2. confirm global vs selective malabsorption, 3. confirm the aetiology. (Book p14)"),
    (T1, 14, "recall", "The second step after confirming the diagnosis of malabsorption is to:",
     ["Confirm global versus selective malabsorption",
      "Confirm the aetiology",
      "Begin empirical antibiotics",
      "Repeat the stool fat test"],
     0, "2. Confirm global vs selective malabsorption. (Book p14)"),
    (T1, 14, "recall", "The final step in the book's evaluation sequence is to:",
     ["Confirm the aetiology", "Confirm the diagnosis", "Confirm global vs selective type", "Discharge with dietary advice"],
     0, "3. Confirm the aetiology. (Book p14)"),
    (T1, 14, "fillup", "The diagnosis of malabsorption is confirmed clinically and by ____.",
     ["investigations", "therapeutic trial alone", "radiology alone", "serology alone"],
     0, "Step 1: confirm the diagnosis — clinically and by investigations. (Book p14)"),

    (T2, 14, "recall", "In the clinical features table, the diarrhoea of malabsorption arises from which site?",
     ["Small intestine", "Colon", "Stomach", "Oesophagus"],
     0, "Clinical features — diarrhoea: site — small intestine. (Book p14)"),
    (T2, 14, "recall", "The duration of diarrhoea in the malabsorption table is:",
     [">4 weeks", "<2 weeks", ">2 weeks but <4 weeks", "<48 hours"],
     0, "Clinical features — duration: >4 weeks. (Book p14)"),
    (T2, 14, "recall", "The stool osmotic gap in malabsorption is:",
     ["Increased", "Decreased", "Normal", "Zero"],
     0, "Clinical features: stool osmotic gap ↑. (Book p14)"),
    (T2, 14, "fillup", "The diarrhoea of malabsorption is described as ____ diarrhoea and is the most consistent symptom.",
     ["osmotic", "secretory", "factitious", "inflammatory"],
     0, "Osmotic diarrhoea: most consistent symptom. (Book p14)"),
    (T2, 14, "recall", "On fasting, the diarrhoea of malabsorption:",
     ["Improves", "Worsens", "Is unchanged", "Becomes bloody"],
     0, "Clinical features: improves on fasting. (Book p14)"),
    (T2, 14, "recall", "Gastrointestinal — fat malabsorption presents as:",
     ["Steatorrhea",
      "Abdominal bloating and dyspeptic symptoms",
      "Foul smelling stools, ascites and edema",
      "Unexplained weight loss"],
     0, "Gastrointestinal: fat malabsorption → steatorrhea. (Book p14)"),
    (T2, 14, "recall", "Gastrointestinal — carbohydrate malabsorption presents as:",
     ["Abdominal bloating and dyspeptic symptoms",
      "Steatorrhea",
      "Foul smelling stools, ascites and edema",
      "Haematemesis"],
     0, "Gastrointestinal: carbohydrate malabsorption → abdominal bloating and dyspeptic symptoms. (Book p14)"),
    (T2, 14, "recall", "Gastrointestinal — protein malabsorption presents as:",
     ["Foul smelling stools, ascites and edema",
      "Steatorrhea",
      "Abdominal bloating and dyspeptic symptoms",
      "Painless rectal bleeding"],
     0, "Gastrointestinal: protein malabsorption → foul smelling stools, ascites, edema. (Book p14)"),
    (T2, 14, "match",
     "Match the macronutrient malabsorbed to the printed gut feature — 1) Fat 2) Carbohydrate 3) Protein … A) Foul smelling stools, ascites, edema B) Steatorrhea C) Abdominal bloating and dyspeptic symptoms",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Fat → steatorrhea; carbohydrate → abdominal bloating and dyspeptic symptoms; protein → foul smelling stools, ascites, edema. (Book p14)"),
    (T2, 14, "recall", "The fourth gastrointestinal feature listed is:",
     ["Unexplained weight loss", "Jaundice", "Haematemesis", "Constipation"],
     0, "Gastrointestinal: unexplained weight loss. (Book p14)"),

    (T3, 14, "recall", "Musculoskeletal features of malabsorption are attributed to:",
     ["Fat malabsorption due to impaired vitamin D and calcium absorption",
      "Protein malabsorption with myopathy",
      "Carbohydrate malabsorption with lactic acidosis",
      "Vitamin K deficiency with haemarthrosis"],
     0, "Musculoskeletal: fat malabsorption d/t impaired vitamin D and Ca2+ absorption. (Book p14)"),
    (T3, 14, "recall", "The musculoskeletal features listed are:",
     ["Tetany, fracture and bone pain",
      "Arthralgia, myalgia and stiffness",
      "Clubbing and hypertrophic osteoarthropathy",
      "Sacroiliitis and enthesitis"],
     0, "Musculoskeletal: tetany, fracture, bone pain. (Book p14)"),
    (T3, 14, "recall", "Cutaneous — hyperpigmentation is attributed to deficiency of:",
     ["Vitamin B3 / niacin", "Vitamin C", "Vitamin K", "Zinc and essential fatty acids"],
     0, "Cutaneous manifestations: vitamin B3 / niacin deficiency → hyperpigmentation. (Book p14)"),
    (T3, 14, "recall", "Cutaneous — perifollicular hemorrhage and curly (spiral) hair indicate deficiency of:",
     ["Vitamin C", "Vitamin A", "Vitamin K", "Vitamin B3"],
     0, "Cutaneous: vitamin C deficiency → perifollicular hemorrhage, curly hair / spiral hair. (Book p14)"),
    (T3, 14, "recall", "Cutaneous — bruisability and ecchymoses indicate deficiency of:",
     ["Vitamin K", "Vitamin C", "Vitamin A", "Niacin"],
     0, "Cutaneous: vitamin K deficiency → bruisability, ecchymoses. (Book p14)"),
    (T3, 14, "recall", "Cutaneous — acrodermatitis is attributed to deficiency of:",
     ["Zinc and essential fatty acids", "Vitamin A", "Vitamin K", "Vitamin C"],
     0, "Cutaneous: Zn / essential fatty acid deficiency → acrodermatitis. (Book p14)"),
    (T3, 14, "recall", "Cutaneous — follicular hyperkeratosis indicates deficiency of:",
     ["Vitamin A", "Vitamin K", "Niacin", "Vitamin C"],
     0, "Cutaneous: vitamin A deficiency → follicular hyperkeratosis. (Book p14)"),
    (T3, 14, "match",
     "Match the cutaneous sign to the printed deficiency — 1) Hyperpigmentation 2) Perifollicular hemorrhage, curly hair 3) Bruisability, ecchymoses 4) Acrodermatitis … A) Vitamin K B) Niacin (B3) C) Zinc / essential fatty acids D) Vitamin C",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-D, 2-C, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "Niacin → hyperpigmentation; vitamin C → perifollicular hemorrhage and curly hair; vitamin K → bruisability/ecchymoses; Zn and essential fatty acids → acrodermatitis. (Book p14)"),

    (T4, 14, "recall", "Miscellaneous — coeliac disease in the table presents with:",
     ["Growth retardation", "Peripheral neuropathy", "Night blindness", "Bruisability"],
     0, "Miscellaneous: coeliac disease → growth retardation. (Book p14)"),
    (T4, 14, "recall", "Anaemia due to intestinal malabsorption — distal pathology produces:",
     ["Vitamin B12 deficiency", "Folate deficiency", "Iron deficiency", "Pyridoxine deficiency"],
     0, "Anaemia (d/t intestinal malabsorption): distal pathology → vitamin B12 deficiency. (Book p14)"),
    (T4, 14, "recall", "Anaemia due to intestinal malabsorption — proximal pathology produces:",
     ["Folate / iron deficiency", "Vitamin B12 deficiency", "Vitamin E deficiency", "Copper deficiency"],
     0, "Anaemia: proximal pathology → folate / iron deficiency. (Book p14)"),
    (T4, 14, "match",
     "Match the level of intestinal pathology to the printed anaemia — 1) Proximal 2) Distal … A) Vitamin B12 deficiency B) Folate / iron deficiency",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Proximal pathology → folate / iron deficiency; distal pathology → vitamin B12 deficiency. (Book p14)"),
    (T4, 14, "recall", "Peripheral neuropathy and ataxia in the miscellaneous column are attributed to:",
     ["Vitamin B12 / E deficiency", "Vitamin A deficiency", "Folate deficiency", "Vitamin K deficiency"],
     0, "Miscellaneous: vitamin B12 / E deficiency → peripheral neuropathy, ataxia. (Book p14)"),
    (T4, 14, "recall", "Glossitis, cheliosis and stomatitis are attributed to:",
     ["Vitamin B12 deficiency", "Vitamin A deficiency", "Niacin deficiency", "Vitamin C deficiency"],
     0, "Miscellaneous: vitamin B12 deficiency → glossitis, cheliosis, stomatitis. (Book p14)"),
    (T4, 14, "recall", "Night blindness and xerophthalmia are attributed to:",
     ["Vitamin A deficiency", "Vitamin B12 deficiency", "Vitamin K deficiency", "Niacin deficiency"],
     0, "Miscellaneous: vitamin A deficiency → night blindness, xerophthalmia. (Book p14)"),
    (T4, 14, "oddoneout", "Pick the ODD ONE OUT — one of these is not a listed miscellaneous feature of malabsorption:",
     ["Arthralgia", "Growth retardation", "Peripheral neuropathy, ataxia", "Night blindness, xerophthalmia"],
     0, "Miscellaneous lists growth retardation, anaemia, peripheral neuropathy/ataxia, glossitis-cheliosis-stomatitis and night blindness. Arthralgia is not listed. (Book p14)"),

    # ----------------------------------------------------------------- p15
    (T4, 15, "recall", "In normal physiology, fatty acid binds calcium to form an ____ that is excreted.",
     ["insoluble complex", "osmotic load", "free oxalate", "bile salt"],
     0, "Normal physiology: fatty acid + Ca2+ → insoluble → excreted. (Book p15)"),
    (T4, 15, "recall", "In malabsorption, unbound oxalate in the gut is:",
     ["Absorbed in the colon producing oxaluria",
      "Excreted unchanged in the stool",
      "Converted to citrate",
      "Metabolised by colonic bacteria to lactate"],
     0, "In malabsorption: free oxalate in gut → oxalate absorbed in colon → oxaluria. (Book p15)"),
    (T4, 15, "match",
     "Order the printed kidney stone pathway — 1) Free oxalate in gut 2) Oxalate absorbed in colon 3) Oxaluria 4) Ca2+ oxalate stones … A) Oxaluria B) Free oxalate in gut C) Ca2+ oxalate stones D) Oxalate absorbed in colon",
     ["1-B, 2-D, 3-A, 4-C", "1-A, 2-B, 3-C, 4-D", "1-C, 2-D, 3-B, 4-A", "1-B, 2-A, 3-D, 4-C"],
     0, "Free oxalate in gut → oxalate absorbed in colon → oxaluria → Ca2+ oxalate stones. (Book p15)"),
    (T4, 15, "recall", "The kidney stones of malabsorption are composed of:",
     ["Calcium oxalate", "Uric acid", "Struvite", "Cystine"],
     0, "Malabsorption → Ca2+ oxalate stones in urine. (Book p15)"),
    (T4, 15, "oddoneout", "All of the following are listed as NOT seen in malabsorption EXCEPT:",
     ["Steatorrhea", "Abdominal pain", "Constipation", "Fever"],
     0, "Note: symptoms not seen in malabsorption — abdominal pain, constipation, fever. Steatorrhea is a feature. (Book p15)"),
    (T4, 15, "recall", "The note lists symptoms that are not seen in malabsorption as:",
     ["Abdominal pain, constipation and fever",
      "Steatorrhea, weight loss and edema",
      "Bloating, belching and flatus",
      "Glossitis, cheliosis and stomatitis"],
     0, "Note: symptoms not seen in malabsorption — abdominal pain, constipation, fever. (Book p15)"),
    (T4, 15, "match",
     "Match the differential of malabsorption to the printed similarity — 1) TB 2) Nephrotic syndrome … A) Protein loss B) Weight loss, long standing diarrhoea, edema/ascites",
     ["1-B, 2-A", "1-A, 2-B", "1-A, 2-A", "1-B, 2-B"],
     0, "Differentials of malabsorption (similar symptoms): TB — weight loss, long standing diarrhoea, edema/ascites; nephrotic syndrome — protein loss. (Book p15)"),
    (T4, 15, "scenario",
     "A patient has chronic diarrhoea, weight loss and ascites. Before calling it malabsorption the book asks you to exclude:",
     ["Tuberculosis", "Coeliac disease", "Tropical sprue", "Cystinuria"],
     0, "Differentials of malabsorption with similar symptoms: TB — weight loss, long standing diarrhoea, edema/ascites. (Book p15)"),

    (T5, 15, "recall", "The qualitative test for fat malabsorption listed is:",
     ["Sudan III", "Sudan IV", "Oil red O", "Acid steatocrit"],
     0, "Fat malabsorption: qualitative test — Sudan III. (Book p15)"),
    (T5, 15, "recall", "The quantitative test for fat malabsorption is:",
     ["Fecal fat excretion", "Lactose hydrogen breath test", "D-xylose test", "Schilling test"],
     0, "Quantitative test (gold standard): fecal fat excretion >7 g/day. (Book p15)"),
    (T5, 15, "numeric", "The quantitative fecal fat test is abnormal above:",
     [">7 g/day", ">3 g/day", ">14 g/day", ">21 g/day"],
     0, "Quantitative test (gold standard): fecal fat excretion >7 g/day. (Book p15)"),
    (T5, 15, "recall", "The book calls the fecal fat excretion test:",
     ["The gold standard investigation for malabsorption",
      "An obsolete screening test",
      "A test of pancreatic function only",
      "A test of colonic transit"],
     0, "Note: fecal fat excretion test is the gold standard investigation for malabsorption. (Book p15)"),
    (T5, 15, "truefalse",
     "TRUE or FALSE — Sudan III is listed as the qualitative stool fat test in this chapter's investigations.",
     ["True — qualitative test: Sudan III",
      "False — Sudan black is used",
      "False — Oil red O is the only listed stain",
      "True — but it is the gold standard"],
     0, "Fat malabsorption: qualitative test — Sudan III; quantitative test (gold standard) — fecal fat excretion >7 g/day. (Book p15)"),

    (T6, 15, "recall", "The D-xylose test is described as:",
     ["The best and most specific test for carbohydrate malabsorption",
      "The gold standard for fat malabsorption",
      "A test of pancreatic exocrine function",
      "An obsolete test of bile acid absorption"],
     0, "Carbohydrate malabsorption: 1. D-xylose test — best and most specific test. (Book p15)"),
    (T6, 15, "recall", "D-xylose is composed of:",
     ["A pentose monosaccharide", "A disaccharide of glucose and galactose", "A hexose polysaccharide", "An amino sugar"],
     0, "Composition of D-xylose: pentose monosaccharide. (Book p15)"),
    (T6, 15, "recall", "The D-xylose test is used to assess:",
     ["Intact small intestinal mucosa",
      "Pancreatic lipase output",
      "Ileal bile acid transport",
      "Gastric acid secretion"],
     0, "Used to assess intact small intestinal mucosa (D-xylose absorbed here). (Book p15)"),
    (T6, 15, "numeric", "The dose of D-xylose given orally after fasting is:",
     ["25 g", "2.5 g", "50 g", "100 g"],
     0, "Procedure: 25 g of D-xylose given orally after fasting (early morning). (Book p15)"),
    (T6, 15, "recall", "After the oral dose, urine is collected for how long?",
     ["4-6 hours", "30 minutes", "24 hours", "72 hours"],
     0, "Collect urine sample (entire volume passed) after 4-6 hours and check D-xylose levels. (Book p15)"),
    (T6, 15, "numeric", "A normal D-xylose excretion result is:",
     ["≥4.5 g", "≥45 g", "<4.5 g", "≥7 g"],
     0, "Interpretation: normal ≥4.5 g. (Book p15)"),
    (T6, 15, "numeric", "A positive (abnormal) D-xylose test is reported below:",
     ["<4.5 g", "<7 g", ">4.5 g", "<25 g"],
     0, "<4.5 g (positive) → small intestinal mucosal pathology. (Book p15)"),
    (T6, 15, "fillup", "A positive D-xylose test indicates ____ pathology.",
     ["small intestinal mucosal", "pancreatic", "ileal bile acid", "gastric"],
     0, "<4.5 g (positive) → small intestinal mucosal pathology. (Book p15)"),

    # ----------------------------------------------------------------- p16
    (T7, 16, "match",
     "Match the clinical scenario to the printed reason for a false positive D-xylose — 1) Renal failure 2) Rapid intestinal transit 3) SIBO 4) Ascites … A) Reduced absorption B) Defective excretion C) Organisms utilise D-xylose → reduced absorption D) Reduced absorption",
     ["1-B, 2-A, 3-C, 4-D", "1-A, 2-B, 3-C, 4-D", "1-C, 2-D, 3-A, 4-B", "1-B, 2-C, 3-D, 4-A"],
     0, "Renal failure → defective excretion; rapid intestinal transit (hyperthyroidism, vomiting) → reduced absorption; SIBO → organisms utilise D-xylose → reduced absorption; ascites → reduced absorption. (Book p16)"),
    (T7, 16, "recall", "Renal failure causes a false positive D-xylose test because of:",
     ["Defective excretion", "Reduced absorption", "Bacterial consumption of D-xylose", "Enhanced renal reabsorption"],
     0, "Renal failure: defective excretion → false positive. (Book p16)"),
    (T7, 16, "recall", "Rapid intestinal transit causing a false positive D-xylose is listed with:",
     ["Hyperthyroidism and vomiting", "Hypothyroidism and constipation", "Diabetes and gastroparesis", "Coeliac disease and sprue"],
     0, "Rapid intestinal transit (hyperthyroidism, vomiting) → reduced absorption → false positive. (Book p16)"),
    (T7, 16, "recall", "SIBO produces a false positive D-xylose test because:",
     ["Organisms utilise D-xylose, so absorption is reduced",
      "Organisms synthesise D-xylose",
      "Bacteria block renal excretion",
      "Bacteria damage the ileal mucosa"],
     0, "SIBO: organisms utilise D-xylose → reduced absorption → false positive. (Book p16)"),
    (T7, 16, "recall", "The lactose tolerance test is described as:",
     ["Obsolete", "The gold standard", "The preferred screening test", "The most specific test"],
     0, "2. Lactose tolerance test: obsolete. (Book p16)"),
    (T7, 16, "recall", "The lactose hydrogen breath test is done for:",
     ["Lactase deficiency", "Pancreatic insufficiency", "Bile acid diarrhea", "SIBO"],
     0, "3. Lactose H2 breath test: done for lactase deficiency. (Book p16)"),
    (T7, 16, "match",
     "Order the printed principle of the lactose H2 breath test — 1) Deficiency of lactase 2) Accumulation of lactose in large intestine 3) Bacterial action on lactose 4) H2 production … A) H2 production B) Deficiency of lactase C) Bacterial action on lactose D) Accumulation of lactose in large intestine",
     ["1-B, 2-D, 3-C, 4-A", "1-A, 2-B, 3-C, 4-D", "1-C, 2-D, 3-A, 4-B", "1-B, 2-C, 3-D, 4-A"],
     0, "Deficiency of lactase → accumulation of lactose in large intestine → bacterial action on lactose → H2 production. (Book p16)"),
    (T7, 16, "numeric", "Diagnosis on the lactose hydrogen breath test is a rise in breath H2 of:",
     ["> 20 ppm", "> 90 ppm", "> 4.5 ppm", "> 7 ppm"],
     0, "Diagnosis: ↑ in breath H2 > 20 ppm. (Book p16)"),
    (T7, 16, "recall", "The lactulose H2 breath test is used to detect:",
     ["Bacterial overgrowth of the small intestine",
      "Lactase deficiency",
      "Fat malabsorption",
      "Vitamin B12 malabsorption"],
     0, "4. Lactulose H2 breath test: H2 produced within 90 minutes (early peaking) = SIBO. (Book p16)"),
    (T7, 16, "numeric", "On the lactulose H2 breath test, an early peak of H2 within what time indicates SIBO?",
     ["Within 90 minutes", "Within 30 minutes", "After 120 minutes", "After 4-6 hours"],
     0, "H2 produced within 90 minutes (early peaking) → SIBO. (Book p16)"),
    (T7, 16, "recall", "On the lactulose H2 breath test, H2 appearing after 90 minutes indicates:",
     ["Normal physiology", "SIBO", "Coeliac disease", "Pancreatic insufficiency"],
     0, ">90 minutes = normal physiology. (Book p16)"),

    (T8, 16, "match",
     "Match the obsolete test to the printed malabsorption it was used for — 1) Acid steatocrit test 2) C-14 triolein breath test 3) C-13 egg white breath test … A) Protein malabsorption B) Fat malabsorption C) Fat malabsorption",
     ["1-B, 2-C, 3-A", "1-A, 2-B, 3-C", "1-C, 2-A, 3-B", "1-B, 2-A, 3-C"],
     0, "Obsolete tests: acid steatocrit test and C-14 triolein breath test for fat malabsorption; C-13 egg white breath test (phenol and p-cresol in urine) for protein malabsorption. (Book p16)"),
    (T8, 16, "recall", "The acid steatocrit test was an obsolete test for:",
     ["Fat malabsorption", "Protein malabsorption", "Carbohydrate malabsorption", "Bile acid malabsorption"],
     0, "Obsolete tests for malabsorption: acid steatocrit test — fat malabsorption. (Book p16)"),
    (T8, 16, "recall", "The C-14 triolein breath test was an obsolete test for:",
     ["Fat malabsorption", "Protein malabsorption", "Vitamin B12 malabsorption", "Carbohydrate malabsorption"],
     0, "Obsolete: C-14 triolein breath test — fat malabsorption. (Book p16)"),
    (T8, 16, "recall", "The C-13 egg white breath test detects protein malabsorption by measuring:",
     ["Phenol and p-cresol in urine", "Urea in breath", "Ammonia in stool", "Indican in serum"],
     0, "C-13 egg white breath test (phenol and p-cresol in urine) — protein malabsorption. (Book p16)"),
    (T8, 16, "recall", "Stool elastase and chymotrypsin are noted as tests for:",
     ["Pancreatic insufficiency",
      "Primary intestinal lymphangiectasia",
      "Small intestinal mucosal damage",
      "Bile acid diarrhea"],
     0, "Note: stool elastase, chymotrypsin — pancreatic insufficiency. (Book p16)"),
    (T8, 16, "recall", "Fecal α-1 antitrypsin is the noted test for:",
     ["Primary intestinal lymphangiectasia", "Pancreatic insufficiency", "Coeliac disease", "SIBO"],
     0, "Note: fecal α-1 antitrypsin — primary intestinal lymphangiectasia. (Book p16)"),
    (T8, 16, "recall", "NIRA (near infrared reflectance analysis) is described as:",
     ["A newer test for malabsorption", "An obsolete test for fat malabsorption", "A test of pancreatic function", "A test of ileal bile acid transport"],
     0, "Note: NIRA (near infrared reflectance analysis) — newer test for malabsorption. (Book p16)"),
    (T8, 16, "recall", "The diseases the book says are diagnosed on biopsy are:",
     ["Whipple's disease, agammaglobulinaemia and abetalipoproteinaemia",
      "Coeliac disease, tropical sprue and SIBO",
      "Crohn's disease and ulcerative colitis",
      "Cystinuria and Hartnup disease"],
     0, "Diseases diagnosed on biopsy: 1. Whipple's disease, 2. agammaglobulinaemia, 3. abetalipoproteinaemia. (Book p16)"),

    # ----------------------------------------------------------------- p17
    (T9, 17, "recall", "Phase I of the Schilling test begins with unlabelled vitamin B12 given:",
     ["1000 μg intramuscularly to saturate stores",
      "1 μg orally",
      "1000 μg orally",
      "1 μg intramuscularly"],
     0, "Phase I: 1000 μg of unlabelled vitamin B12 I.M. to saturate stores. (Book p17)"),
    (T9, 17, "numeric", "The dose of oral radiolabelled vitamin B12 in the Schilling test is:",
     ["1 μg", "10 μg", "100 μg", "1000 μg"],
     0, "Give 1 μg of oral radiolabelled vitamin B12. (Book p17)"),
    (T9, 17, "recall", "After the doses, the Schilling test measures vitamin B12 in:",
     ["Urine", "Serum", "Stool", "Breath"],
     0, "Check vitamin B12 level in urine. (Book p17)"),
    (T9, 17, "numeric", "A urinary vitamin B12 excretion below what value is a positive Schilling test?",
     ["<7%", "<1%", "<10%", "<4.5%"],
     0, "<7% = positive test (malabsorption aetiology). (Book p17)"),
    (T9, 17, "recall", "Urinary vitamin B12 excretion of 7-10% in the Schilling test is:",
     ["Normal", "Positive for malabsorption", "Diagnostic of ileal disease", "Diagnostic of pernicious anaemia"],
     0, "7-10% = normal. (Book p17)"),
    (T9, 17, "match",
     "Match phase II of the Schilling test to the diagnosis when urine B12 rises above 10% — 1) Intrinsic factor 2) Pancreatic enzymes 3) Antibiotics … A) Chronic pancreatitis B) SIBO C) Pernicious anaemia",
     ["1-C, 2-A, 3-B", "1-A, 2-B, 3-C", "1-B, 2-C, 3-A", "1-C, 2-B, 3-A"],
     0, "Phase II: administer intrinsic factor / pancreatic enzymes / antibiotics; if urine B12 >10% → pernicious anaemia (IF), chronic pancreatitis, SIBO respectively. (Book p17)"),
    (T9, 17, "recall", "After phase I and II, persistent urine B12 below 7% indicates:",
     ["Ileal disease", "Pernicious anaemia", "Chronic pancreatitis", "SIBO"],
     0, "After phase I and II, if urine B12 <7% = ileal disease. (Book p17)"),
    (T9, 17, "scenario",
     "A patient's Schilling test corrects after oral intrinsic factor is added in phase II. The book's diagnosis is:",
     ["Pernicious anaemia", "Chronic pancreatitis", "SIBO", "Ileal resection"],
     0, "Phase II: intrinsic factor → urine B12 >10% → pernicious anaemia (IF). (Book p17)"),
    (T9, 17, "scenario",
     "A patient's Schilling test corrects after antibiotics in phase II. The book's diagnosis is:",
     ["SIBO", "Pernicious anaemia", "Chronic pancreatitis", "Ileal disease"],
     0, "Phase II: antibiotics → urine B12 >10% → SIBO. (Book p17)"),
]


GUIDES = {
    T1: ("Steps for Evaluating Malabsorption",
         "Confirm the diagnosis (clinically and by investigations).\nThen confirm global versus selective malabsorption.\nFinally confirm the aetiology."),
    T2: ("Clinical Features: Gastrointestinal",
         "Small intestinal, >4 weeks, osmotic, improves on fasting — the most consistent symptom.\nFat → steatorrhea; carbohydrate → bloating and dyspepsia.\nProtein → foul smelling stools, ascites, edema; plus unexplained weight loss."),
    T3: ("Clinical Features: Musculoskeletal & Cutaneous",
         "Musculoskeletal: fat malabsorption with impaired vitamin D and Ca2+ → tetany, fracture, bone pain.\nNiacin → hyperpigmentation; vitamin C → perifollicular hemorrhage and curly hair.\nVitamin K → bruisability; Zn/EFA → acrodermatitis; vitamin A → follicular hyperkeratosis."),
    T4: ("Clinical Features: Miscellaneous & Kidney Stones",
         "Coeliac → growth retardation; proximal disease → folate/iron deficiency; distal → B12 deficiency.\nB12/E → neuropathy and ataxia; B12 → glossitis, cheliosis, stomatitis; vitamin A → night blindness.\nFree oxalate is absorbed in the colon → oxaluria → Ca2+ oxalate stones; pain, constipation and fever are NOT features."),
    T5: ("Fat Malabsorption Tests",
         "Qualitative: Sudan III.\nQuantitative (gold standard): fecal fat excretion >7 g/day.\nThe fecal fat excretion test is the gold standard investigation for malabsorption."),
    T6: ("D-Xylose Test",
         "Best and most specific test; D-xylose is a pentose monosaccharide.\nIt assesses intact small intestinal mucosa.\n25 g orally after fasting; urine collected over 4-6 hours; normal ≥4.5 g, <4.5 g positive."),
    T7: ("False Positives & Hydrogen Breath Tests",
         "False positives: renal failure (defective excretion), rapid transit (hyperthyroidism, vomiting), SIBO (organisms utilise D-xylose), ascites.\nLactose H2 breath test: for lactase deficiency, positive >20 ppm.\nLactulose H2 breath test: H2 within 90 minutes = SIBO; after 90 minutes = normal."),
    T8: ("Obsolete Tests & Biopsy Diagnoses",
         "Obsolete: acid steatocrit and C-14 triolein breath test (fat); C-13 egg white breath test (protein).\nStool elastase/chymotrypsin → pancreatic insufficiency; fecal α-1 antitrypsin → lymphangiectasia; NIRA is newer.\nBiopsy diagnoses: Whipple's disease, agammaglobulinaemia, abetalipoproteinaemia."),
    T9: ("Schilling Test",
         "Phase I: 1000 μg unlabelled B12 IM to saturate stores, then 1 μg oral radiolabelled B12, then urine B12.\n<7% positive, 7-10% normal.\nPhase II: intrinsic factor → pernicious anaemia; pancreatic enzymes → chronic pancreatitis; antibiotics → SIBO; still <7% = ileal disease."),
}


def main():
    questions = []
    for index, (sec, page, fmt, stem, opts, ans, exp) in enumerate(RAW, 1):
        questions.append({
            "id": f"MED-C{CHAPTER}-{index:02d}",
            "sec": sec,
            "page": page,
            "fmt": fmt,
            "q": stem,
            "opts": opts,
            "ans": ans,
            "exp": exp,
        })
    ordered = []
    for sec, *_ in RAW:
        if sec not in ordered:
            ordered.append(sec)
    units = []
    for n, sec in enumerate(ordered, 1):
        title_text, guide = GUIDES[sec]
        units.append({
            "id": f"MED-U{CHAPTER}-{n}",
            "ch": CHAPTER,
            "n": n,
            "title": title_text,
            "sec": sec,
            "guide": guide,
            "qs": [q["id"] for q in questions if q["sec"] == sec],
        })
    out = DATA / f"ch{CHAPTER:02d}.json"
    out.write_text(json.dumps({
        "chapter": CHAPTER, "title": TITLE, "pageRange": PAGES,
        "questions": questions, "units": units,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out.name}: {len(questions)} questions / {len(units)} units")


if __name__ == "__main__":
    main()
